//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.12.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.Linq;
using System.Collections.Generic;
using SD.LLBLGen.Pro.LinqSupportClasses;
using SD.LLBLGen.Pro.ORMSupportClasses;
using DATN.EntityClasses;
using DATN.FactoryClasses;

namespace DATN.Linq
{
	/// <summary>Meta-data class for the construction of Linq queries which are to be executed using LLBLGen Pro code.</summary>
	public partial class LinqMetaData: ILinqMetaData
	{
		/// <summary>CTor. Using this ctor will leave the IDataAccessAdapter object to use empty. To be able to execute the query, an IDataAccessAdapter instance
		/// is required, and has to be set on the LLBLGenProProvider2 object in the query to execute. </summary>
		public LinqMetaData() : this(null, null) { }
		
		/// <summary>CTor which accepts an IDataAccessAdapter implementing object, which will be used to execute queries created with this metadata class.</summary>
		/// <param name="adapterToUse">the IDataAccessAdapter to use in queries created with this meta data</param>
		/// <remarks> Be aware that the IDataAccessAdapter object set via this property is kept alive by the LLBLGenProQuery objects created with this meta data till they go out of scope.</remarks>
		public LinqMetaData(IDataAccessAdapter adapterToUse) : this (adapterToUse, null) { }

		/// <summary>CTor which accepts an IDataAccessAdapter implementing object, which will be used to execute queries created with this metadata class.</summary>
		/// <param name="adapterToUse">the IDataAccessAdapter to use in queries created with this meta data</param>
		/// <param name="customFunctionMappings">The custom function mappings to use. These take higher precedence than the ones in the DQE to use.</param>
		/// <remarks> Be aware that the IDataAccessAdapter object set via this property is kept alive by the LLBLGenProQuery objects created with this meta data till they go out of scope.</remarks>
		public LinqMetaData(IDataAccessAdapter adapterToUse, FunctionMappingStore customFunctionMappings)
		{
			this.AdapterToUse = adapterToUse;
			this.CustomFunctionMappings = customFunctionMappings;
		}
	
		/// <summary>returns the datasource to use in a Linq query for the entity type specified</summary>
		/// <param name="typeOfEntity">the type of the entity to get the datasource for</param>
		/// <returns>the requested datasource</returns>
		public IDataSource GetQueryableForEntity(int typeOfEntity)
		{
			switch((DATN.EntityType)typeOfEntity)
			{
				case DATN.EntityType.LoginAttemptEntity:
					return this.LoginAttempt;
				case DATN.EntityType.UserAuditLogEntity:
					return this.UserAuditLog;
				case DATN.EntityType.PermissionEntity:
					return this.Permission;
				case DATN.EntityType.RefreshTokenEntity:
					return this.RefreshToken;
				case DATN.EntityType.RoleEntity:
					return this.Role;
				case DATN.EntityType.RolePermissionEntity:
					return this.RolePermission;
				case DATN.EntityType.UserEntity:
					return this.User;
				case DATN.EntityType.UserRoleEntity:
					return this.UserRole;
				case DATN.EntityType.UserSessionEntity:
					return this.UserSession;
				case DATN.EntityType.BrandEntity:
					return this.Brand;
				case DATN.EntityType.CategoryEntity:
					return this.Category;
				case DATN.EntityType.ProductEntity:
					return this.Product;
				case DATN.EntityType.ProductImageEntity:
					return this.ProductImage;
				case DATN.EntityType.ProductVariantEntity:
					return this.ProductVariant;
				case DATN.EntityType.engagementReviewEntity:
					return this.engagementReview;
				case DATN.EntityType.NotificationEntity:
					return this.Notification;
				case DATN.EntityType.salesCartEntity:
					return this.salesCart;
				case DATN.EntityType.salesOrderEntity:
					return this.salesOrder;
				case DATN.EntityType.salesOrderItemEntity:
					return this.salesOrderItem;
				case DATN.EntityType.TransactionEntity:
					return this.Transaction;
				case DATN.EntityType.CartEntity:
					return this.Cart;
				case DATN.EntityType.DiscountEntity:
					return this.Discount;
				case DATN.EntityType.GameEntity:
					return this.Game;
				case DATN.EntityType.GameTagEntity:
					return this.GameTag;
				case DATN.EntityType.OrderEntity:
					return this.Order;
				case DATN.EntityType.OrderItemEntity:
					return this.OrderItem;
				case DATN.EntityType.PublisherEntity:
					return this.Publisher;
				case DATN.EntityType.ReviewEntity:
					return this.Review;
				case DATN.EntityType.TagEntity:
					return this.Tag;
				case DATN.EntityType.UserGameEntity:
					return this.UserGame;
				case DATN.EntityType.WishlistEntity:
					return this.Wishlist;
				default:
					return null;
			}
		}

		/// <summary>returns the datasource to use in a Linq query which wraps the specified SQL query and projects it to instances of type T</summary>
		/// <param name="sqlQuery">The SQL query to execute. Has to follow one of the parameter specification patterns for Plain SQL queries in the LLBLGen Pro Runtime Framework</param>
		/// <param name="parameterValues">The object which will provide the parameter values for the SQL query specified. Has to follow one of the parameter specification patterns for Plain SQL queries in the LLBLGen Pro Runtime Framework</param>
		/// <typeparam name="T">The type of the instances to project the rows into, returned by the SQL query specified</typeparam>
		/// <returns>the requested datasource</returns>
		[InMemoryCandidate]
		public DataSource2<T> FromSql<T>(string sqlQuery, object parameterValues)
			where T : class
		{
			return new DataSource2<T>(this.AdapterToUse, new ElementCreator(), this.CustomFunctionMappings, this.ContextToUse).SetWrappedPlainSQLQuerySpecification(sqlQuery, parameterValues);
		}

		/// <summary>returns the datasource to use in a Linq query for the entity type specified</summary>
		/// <typeparam name="TEntity">the type of the entity to get the datasource for</typeparam>
		/// <returns>the requested datasource</returns>
		public DataSource2<TEntity> GetQueryableForEntity<TEntity>()
				where TEntity : class
		{
			return new DataSource2<TEntity>(this.AdapterToUse, new ElementCreator(), this.CustomFunctionMappings, this.ContextToUse);
		}

		/// <summary>returns the datasource to use in a Linq query when targeting LoginAttemptEntity instances in the database.</summary>
		public DataSource2<LoginAttemptEntity> LoginAttempt {	get { return new DataSource2<LoginAttemptEntity>(this.AdapterToUse, new ElementCreator(), this.CustomFunctionMappings, this.ContextToUse); } }
		
		/// <summary>returns the datasource to use in a Linq query when targeting UserAuditLogEntity instances in the database.</summary>
		public DataSource2<UserAuditLogEntity> UserAuditLog {	get { return new DataSource2<UserAuditLogEntity>(this.AdapterToUse, new ElementCreator(), this.CustomFunctionMappings, this.ContextToUse); } }
		
		/// <summary>returns the datasource to use in a Linq query when targeting PermissionEntity instances in the database.</summary>
		public DataSource2<PermissionEntity> Permission {	get { return new DataSource2<PermissionEntity>(this.AdapterToUse, new ElementCreator(), this.CustomFunctionMappings, this.ContextToUse); } }
		
		/// <summary>returns the datasource to use in a Linq query when targeting RefreshTokenEntity instances in the database.</summary>
		public DataSource2<RefreshTokenEntity> RefreshToken {	get { return new DataSource2<RefreshTokenEntity>(this.AdapterToUse, new ElementCreator(), this.CustomFunctionMappings, this.ContextToUse); } }
		
		/// <summary>returns the datasource to use in a Linq query when targeting RoleEntity instances in the database.</summary>
		public DataSource2<RoleEntity> Role {	get { return new DataSource2<RoleEntity>(this.AdapterToUse, new ElementCreator(), this.CustomFunctionMappings, this.ContextToUse); } }
		
		/// <summary>returns the datasource to use in a Linq query when targeting RolePermissionEntity instances in the database.</summary>
		public DataSource2<RolePermissionEntity> RolePermission {	get { return new DataSource2<RolePermissionEntity>(this.AdapterToUse, new ElementCreator(), this.CustomFunctionMappings, this.ContextToUse); } }
		
		/// <summary>returns the datasource to use in a Linq query when targeting UserEntity instances in the database.</summary>
		public DataSource2<UserEntity> User {	get { return new DataSource2<UserEntity>(this.AdapterToUse, new ElementCreator(), this.CustomFunctionMappings, this.ContextToUse); } }
		
		/// <summary>returns the datasource to use in a Linq query when targeting UserRoleEntity instances in the database.</summary>
		public DataSource2<UserRoleEntity> UserRole {	get { return new DataSource2<UserRoleEntity>(this.AdapterToUse, new ElementCreator(), this.CustomFunctionMappings, this.ContextToUse); } }
		
		/// <summary>returns the datasource to use in a Linq query when targeting UserSessionEntity instances in the database.</summary>
		public DataSource2<UserSessionEntity> UserSession {	get { return new DataSource2<UserSessionEntity>(this.AdapterToUse, new ElementCreator(), this.CustomFunctionMappings, this.ContextToUse); } }
		
		/// <summary>returns the datasource to use in a Linq query when targeting BrandEntity instances in the database.</summary>
		public DataSource2<BrandEntity> Brand {	get { return new DataSource2<BrandEntity>(this.AdapterToUse, new ElementCreator(), this.CustomFunctionMappings, this.ContextToUse); } }
		
		/// <summary>returns the datasource to use in a Linq query when targeting CategoryEntity instances in the database.</summary>
		public DataSource2<CategoryEntity> Category {	get { return new DataSource2<CategoryEntity>(this.AdapterToUse, new ElementCreator(), this.CustomFunctionMappings, this.ContextToUse); } }
		
		/// <summary>returns the datasource to use in a Linq query when targeting ProductEntity instances in the database.</summary>
		public DataSource2<ProductEntity> Product {	get { return new DataSource2<ProductEntity>(this.AdapterToUse, new ElementCreator(), this.CustomFunctionMappings, this.ContextToUse); } }
		
		/// <summary>returns the datasource to use in a Linq query when targeting ProductImageEntity instances in the database.</summary>
		public DataSource2<ProductImageEntity> ProductImage {	get { return new DataSource2<ProductImageEntity>(this.AdapterToUse, new ElementCreator(), this.CustomFunctionMappings, this.ContextToUse); } }
		
		/// <summary>returns the datasource to use in a Linq query when targeting ProductVariantEntity instances in the database.</summary>
		public DataSource2<ProductVariantEntity> ProductVariant {	get { return new DataSource2<ProductVariantEntity>(this.AdapterToUse, new ElementCreator(), this.CustomFunctionMappings, this.ContextToUse); } }
		
		/// <summary>returns the datasource to use in a Linq query when targeting engagementReviewEntity instances in the database.</summary>
		public DataSource2<engagementReviewEntity> engagementReview {	get { return new DataSource2<engagementReviewEntity>(this.AdapterToUse, new ElementCreator(), this.CustomFunctionMappings, this.ContextToUse); } }
		
		/// <summary>returns the datasource to use in a Linq query when targeting NotificationEntity instances in the database.</summary>
		public DataSource2<NotificationEntity> Notification {	get { return new DataSource2<NotificationEntity>(this.AdapterToUse, new ElementCreator(), this.CustomFunctionMappings, this.ContextToUse); } }
		
		/// <summary>returns the datasource to use in a Linq query when targeting salesCartEntity instances in the database.</summary>
		public DataSource2<salesCartEntity> salesCart {	get { return new DataSource2<salesCartEntity>(this.AdapterToUse, new ElementCreator(), this.CustomFunctionMappings, this.ContextToUse); } }
		
		/// <summary>returns the datasource to use in a Linq query when targeting salesOrderEntity instances in the database.</summary>
		public DataSource2<salesOrderEntity> salesOrder {	get { return new DataSource2<salesOrderEntity>(this.AdapterToUse, new ElementCreator(), this.CustomFunctionMappings, this.ContextToUse); } }
		
		/// <summary>returns the datasource to use in a Linq query when targeting salesOrderItemEntity instances in the database.</summary>
		public DataSource2<salesOrderItemEntity> salesOrderItem {	get { return new DataSource2<salesOrderItemEntity>(this.AdapterToUse, new ElementCreator(), this.CustomFunctionMappings, this.ContextToUse); } }
		
		/// <summary>returns the datasource to use in a Linq query when targeting TransactionEntity instances in the database.</summary>
		public DataSource2<TransactionEntity> Transaction {	get { return new DataSource2<TransactionEntity>(this.AdapterToUse, new ElementCreator(), this.CustomFunctionMappings, this.ContextToUse); } }
		
		/// <summary>returns the datasource to use in a Linq query when targeting CartEntity instances in the database.</summary>
		public DataSource2<CartEntity> Cart {	get { return new DataSource2<CartEntity>(this.AdapterToUse, new ElementCreator(), this.CustomFunctionMappings, this.ContextToUse); } }
		
		/// <summary>returns the datasource to use in a Linq query when targeting DiscountEntity instances in the database.</summary>
		public DataSource2<DiscountEntity> Discount {	get { return new DataSource2<DiscountEntity>(this.AdapterToUse, new ElementCreator(), this.CustomFunctionMappings, this.ContextToUse); } }
		
		/// <summary>returns the datasource to use in a Linq query when targeting GameEntity instances in the database.</summary>
		public DataSource2<GameEntity> Game {	get { return new DataSource2<GameEntity>(this.AdapterToUse, new ElementCreator(), this.CustomFunctionMappings, this.ContextToUse); } }
		
		/// <summary>returns the datasource to use in a Linq query when targeting GameTagEntity instances in the database.</summary>
		public DataSource2<GameTagEntity> GameTag {	get { return new DataSource2<GameTagEntity>(this.AdapterToUse, new ElementCreator(), this.CustomFunctionMappings, this.ContextToUse); } }
		
		/// <summary>returns the datasource to use in a Linq query when targeting OrderEntity instances in the database.</summary>
		public DataSource2<OrderEntity> Order {	get { return new DataSource2<OrderEntity>(this.AdapterToUse, new ElementCreator(), this.CustomFunctionMappings, this.ContextToUse); } }
		
		/// <summary>returns the datasource to use in a Linq query when targeting OrderItemEntity instances in the database.</summary>
		public DataSource2<OrderItemEntity> OrderItem {	get { return new DataSource2<OrderItemEntity>(this.AdapterToUse, new ElementCreator(), this.CustomFunctionMappings, this.ContextToUse); } }
		
		/// <summary>returns the datasource to use in a Linq query when targeting PublisherEntity instances in the database.</summary>
		public DataSource2<PublisherEntity> Publisher {	get { return new DataSource2<PublisherEntity>(this.AdapterToUse, new ElementCreator(), this.CustomFunctionMappings, this.ContextToUse); } }
		
		/// <summary>returns the datasource to use in a Linq query when targeting ReviewEntity instances in the database.</summary>
		public DataSource2<ReviewEntity> Review {	get { return new DataSource2<ReviewEntity>(this.AdapterToUse, new ElementCreator(), this.CustomFunctionMappings, this.ContextToUse); } }
		
		/// <summary>returns the datasource to use in a Linq query when targeting TagEntity instances in the database.</summary>
		public DataSource2<TagEntity> Tag {	get { return new DataSource2<TagEntity>(this.AdapterToUse, new ElementCreator(), this.CustomFunctionMappings, this.ContextToUse); } }
		
		/// <summary>returns the datasource to use in a Linq query when targeting UserGameEntity instances in the database.</summary>
		public DataSource2<UserGameEntity> UserGame {	get { return new DataSource2<UserGameEntity>(this.AdapterToUse, new ElementCreator(), this.CustomFunctionMappings, this.ContextToUse); } }
		
		/// <summary>returns the datasource to use in a Linq query when targeting WishlistEntity instances in the database.</summary>
		public DataSource2<WishlistEntity> Wishlist {	get { return new DataSource2<WishlistEntity>(this.AdapterToUse, new ElementCreator(), this.CustomFunctionMappings, this.ContextToUse); } }
		


		/// <summary> Gets / sets the IDataAccessAdapter to use for the queries created with this meta data object.</summary>
		/// <remarks> Be aware that the IDataAccessAdapter object set via this property is kept alive by the LLBLGenProQuery objects created with this meta data
		/// till they go out of scope.</remarks>
		public IDataAccessAdapter AdapterToUse { get; set; }
		
		/// <summary>Gets or sets the custom function mappings to use. These take higher precedence than the ones in the DQE to use</summary>
		public FunctionMappingStore CustomFunctionMappings { get; set; }
		
		/// <summary>Gets or sets the Context instance to use for entity fetches.</summary>
		public Context ContextToUse { get; set; }
	}
}