//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.12.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
////////////////////////////////////////////////////////////// 
using System;
using System.Linq;
using DATN_2026.EntityClasses;
using DATN_2026.HelperClasses;
using SD.LLBLGen.Pro.ORMSupportClasses;
using SD.LLBLGen.Pro.QuerySpec.AdapterSpecific;
using SD.LLBLGen.Pro.QuerySpec;

namespace DATN_2026.FactoryClasses
{
	/// <summary>Factory class to produce DynamicQuery instances and EntityQuery instances</summary>
	public partial class QueryFactory : QueryFactoryBase2
	{
		/// <summary>Creates and returns a new EntityQuery for the LoginAttempt entity</summary>
		public EntityQuery<LoginAttemptEntity> LoginAttempt { get { return Create<LoginAttemptEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the UserAuditLog entity</summary>
		public EntityQuery<UserAuditLogEntity> UserAuditLog { get { return Create<UserAuditLogEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the Permission entity</summary>
		public EntityQuery<PermissionEntity> Permission { get { return Create<PermissionEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the RefreshToken entity</summary>
		public EntityQuery<RefreshTokenEntity> RefreshToken { get { return Create<RefreshTokenEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the Role entity</summary>
		public EntityQuery<RoleEntity> Role { get { return Create<RoleEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the RolePermission entity</summary>
		public EntityQuery<RolePermissionEntity> RolePermission { get { return Create<RolePermissionEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the User entity</summary>
		public EntityQuery<UserEntity> User { get { return Create<UserEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the UserAddress entity</summary>
		public EntityQuery<UserAddressEntity> UserAddress { get { return Create<UserAddressEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the UserRole entity</summary>
		public EntityQuery<UserRoleEntity> UserRole { get { return Create<UserRoleEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the UserSession entity</summary>
		public EntityQuery<UserSessionEntity> UserSession { get { return Create<UserSessionEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the Brand entity</summary>
		public EntityQuery<BrandEntity> Brand { get { return Create<BrandEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the Category entity</summary>
		public EntityQuery<CategoryEntity> Category { get { return Create<CategoryEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the Product entity</summary>
		public EntityQuery<ProductEntity> Product { get { return Create<ProductEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the ProductImage entity</summary>
		public EntityQuery<ProductImageEntity> ProductImage { get { return Create<ProductImageEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the ProductVariant entity</summary>
		public EntityQuery<ProductVariantEntity> ProductVariant { get { return Create<ProductVariantEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the Shop entity</summary>
		public EntityQuery<ShopEntity> Shop { get { return Create<ShopEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the ChatBox entity</summary>
		public EntityQuery<ChatBoxEntity> ChatBox { get { return Create<ChatBoxEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the ChatMessage entity</summary>
		public EntityQuery<ChatMessageEntity> ChatMessage { get { return Create<ChatMessageEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the Notification entity</summary>
		public EntityQuery<NotificationEntity> Notification { get { return Create<NotificationEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the Review entity</summary>
		public EntityQuery<ReviewEntity> Review { get { return Create<ReviewEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the Wishlist entity</summary>
		public EntityQuery<WishlistEntity> Wishlist { get { return Create<WishlistEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the Stock entity</summary>
		public EntityQuery<StockEntity> Stock { get { return Create<StockEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the StockTransaction entity</summary>
		public EntityQuery<StockTransactionEntity> StockTransaction { get { return Create<StockTransactionEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the UserVoucher entity</summary>
		public EntityQuery<UserVoucherEntity> UserVoucher { get { return Create<UserVoucherEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the Voucher entity</summary>
		public EntityQuery<VoucherEntity> Voucher { get { return Create<VoucherEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the Cart entity</summary>
		public EntityQuery<CartEntity> Cart { get { return Create<CartEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the Order entity</summary>
		public EntityQuery<OrderEntity> Order { get { return Create<OrderEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the OrderItem entity</summary>
		public EntityQuery<OrderItemEntity> OrderItem { get { return Create<OrderItemEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the ShippingTracking entity</summary>
		public EntityQuery<ShippingTrackingEntity> ShippingTracking { get { return Create<ShippingTrackingEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the Transaction entity</summary>
		public EntityQuery<TransactionEntity> Transaction { get { return Create<TransactionEntity>(); } }

		/// <inheritdoc/>
		protected override IElementCreatorCore CreateElementCreator() { return new ElementCreator(); }
 
		/// <summary>Creates and returns the query to fetch the typed view Audit.auditLoginAttempt</summary>
		public DynamicQuery<DATN_2026.TypedViewClasses.auditLoginAttemptRow> auditLoginAttempt
		{
			get { return this.Create().Select<DATN_2026.TypedViewClasses.auditLoginAttemptRow, DATN_2026.HelperClasses.auditLoginAttemptFields>(); }
		}

		/// <summary>Creates and returns the query to fetch the typed view Audit.auditUserAuditLog</summary>
		public DynamicQuery<DATN_2026.TypedViewClasses.auditUserAuditLogRow> auditUserAuditLog
		{
			get { return this.Create().Select<DATN_2026.TypedViewClasses.auditUserAuditLogRow, DATN_2026.HelperClasses.auditUserAuditLogFields>(); }
		}

		/// <summary>Creates and returns the query to fetch the typed view Auth2.auth2Permission</summary>
		public DynamicQuery<DATN_2026.TypedViewClasses.auth2PermissionRow> auth2Permission
		{
			get { return this.Create().Select<DATN_2026.TypedViewClasses.auth2PermissionRow, DATN_2026.HelperClasses.auth2PermissionFields>(); }
		}

		/// <summary>Creates and returns the query to fetch the typed view Auth2.auth2RefreshToken</summary>
		public DynamicQuery<DATN_2026.TypedViewClasses.auth2RefreshTokenRow> auth2RefreshToken
		{
			get { return this.Create().Select<DATN_2026.TypedViewClasses.auth2RefreshTokenRow, DATN_2026.HelperClasses.auth2RefreshTokenFields>(); }
		}

		/// <summary>Creates and returns the query to fetch the typed view Auth2.auth2Role</summary>
		public DynamicQuery<DATN_2026.TypedViewClasses.auth2RoleRow> auth2Role
		{
			get { return this.Create().Select<DATN_2026.TypedViewClasses.auth2RoleRow, DATN_2026.HelperClasses.auth2RoleFields>(); }
		}

		/// <summary>Creates and returns the query to fetch the typed view Auth2.auth2RolePermission</summary>
		public DynamicQuery<DATN_2026.TypedViewClasses.auth2RolePermissionRow> auth2RolePermission
		{
			get { return this.Create().Select<DATN_2026.TypedViewClasses.auth2RolePermissionRow, DATN_2026.HelperClasses.auth2RolePermissionFields>(); }
		}

		/// <summary>Creates and returns the query to fetch the typed view Auth2.auth2User</summary>
		public DynamicQuery<DATN_2026.TypedViewClasses.auth2UserRow> auth2User
		{
			get { return this.Create().Select<DATN_2026.TypedViewClasses.auth2UserRow, DATN_2026.HelperClasses.auth2UserFields>(); }
		}

		/// <summary>Creates and returns the query to fetch the typed view Auth2.auth2UserAddress</summary>
		public DynamicQuery<DATN_2026.TypedViewClasses.auth2UserAddressRow> auth2UserAddress
		{
			get { return this.Create().Select<DATN_2026.TypedViewClasses.auth2UserAddressRow, DATN_2026.HelperClasses.auth2UserAddressFields>(); }
		}

		/// <summary>Creates and returns the query to fetch the typed view Auth2.auth2UserRole</summary>
		public DynamicQuery<DATN_2026.TypedViewClasses.auth2UserRoleRow> auth2UserRole
		{
			get { return this.Create().Select<DATN_2026.TypedViewClasses.auth2UserRoleRow, DATN_2026.HelperClasses.auth2UserRoleFields>(); }
		}

		/// <summary>Creates and returns the query to fetch the typed view Auth2.auth2UserSession</summary>
		public DynamicQuery<DATN_2026.TypedViewClasses.auth2UserSessionRow> auth2UserSession
		{
			get { return this.Create().Select<DATN_2026.TypedViewClasses.auth2UserSessionRow, DATN_2026.HelperClasses.auth2UserSessionFields>(); }
		}

		/// <summary>Creates and returns the query to fetch the typed view Catalog.catalogBrand</summary>
		public DynamicQuery<DATN_2026.TypedViewClasses.catalogBrandRow> catalogBrand
		{
			get { return this.Create().Select<DATN_2026.TypedViewClasses.catalogBrandRow, DATN_2026.HelperClasses.catalogBrandFields>(); }
		}

		/// <summary>Creates and returns the query to fetch the typed view Catalog.catalogCategory</summary>
		public DynamicQuery<DATN_2026.TypedViewClasses.catalogCategoryRow> catalogCategory
		{
			get { return this.Create().Select<DATN_2026.TypedViewClasses.catalogCategoryRow, DATN_2026.HelperClasses.catalogCategoryFields>(); }
		}

		/// <summary>Creates and returns the query to fetch the typed view Catalog.catalogProduct</summary>
		public DynamicQuery<DATN_2026.TypedViewClasses.catalogProductRow> catalogProduct
		{
			get { return this.Create().Select<DATN_2026.TypedViewClasses.catalogProductRow, DATN_2026.HelperClasses.catalogProductFields>(); }
		}

		/// <summary>Creates and returns the query to fetch the typed view Catalog.catalogProductImage</summary>
		public DynamicQuery<DATN_2026.TypedViewClasses.catalogProductImageRow> catalogProductImage
		{
			get { return this.Create().Select<DATN_2026.TypedViewClasses.catalogProductImageRow, DATN_2026.HelperClasses.catalogProductImageFields>(); }
		}

		/// <summary>Creates and returns the query to fetch the typed view Catalog.catalogProductVariant</summary>
		public DynamicQuery<DATN_2026.TypedViewClasses.catalogProductVariantRow> catalogProductVariant
		{
			get { return this.Create().Select<DATN_2026.TypedViewClasses.catalogProductVariantRow, DATN_2026.HelperClasses.catalogProductVariantFields>(); }
		}

		/// <summary>Creates and returns the query to fetch the typed view Catalog.catalogShop</summary>
		public DynamicQuery<DATN_2026.TypedViewClasses.catalogShopRow> catalogShop
		{
			get { return this.Create().Select<DATN_2026.TypedViewClasses.catalogShopRow, DATN_2026.HelperClasses.catalogShopFields>(); }
		}

		/// <summary>Creates and returns the query to fetch the typed view Engagement.engagementChatBox</summary>
		public DynamicQuery<DATN_2026.TypedViewClasses.engagementChatBoxRow> engagementChatBox
		{
			get { return this.Create().Select<DATN_2026.TypedViewClasses.engagementChatBoxRow, DATN_2026.HelperClasses.engagementChatBoxFields>(); }
		}

		/// <summary>Creates and returns the query to fetch the typed view Engagement.engagementChatMessage</summary>
		public DynamicQuery<DATN_2026.TypedViewClasses.engagementChatMessageRow> engagementChatMessage
		{
			get { return this.Create().Select<DATN_2026.TypedViewClasses.engagementChatMessageRow, DATN_2026.HelperClasses.engagementChatMessageFields>(); }
		}

		/// <summary>Creates and returns the query to fetch the typed view Engagement.engagementNotification</summary>
		public DynamicQuery<DATN_2026.TypedViewClasses.engagementNotificationRow> engagementNotification
		{
			get { return this.Create().Select<DATN_2026.TypedViewClasses.engagementNotificationRow, DATN_2026.HelperClasses.engagementNotificationFields>(); }
		}

		/// <summary>Creates and returns the query to fetch the typed view Engagement.engagementReview</summary>
		public DynamicQuery<DATN_2026.TypedViewClasses.engagementReviewRow> engagementReview
		{
			get { return this.Create().Select<DATN_2026.TypedViewClasses.engagementReviewRow, DATN_2026.HelperClasses.engagementReviewFields>(); }
		}

		/// <summary>Creates and returns the query to fetch the typed view Engagement.engagementWishlist</summary>
		public DynamicQuery<DATN_2026.TypedViewClasses.engagementWishlistRow> engagementWishlist
		{
			get { return this.Create().Select<DATN_2026.TypedViewClasses.engagementWishlistRow, DATN_2026.HelperClasses.engagementWishlistFields>(); }
		}

		/// <summary>Creates and returns the query to fetch the typed view Inventory.inventoryStock</summary>
		public DynamicQuery<DATN_2026.TypedViewClasses.inventoryStockRow> inventoryStock
		{
			get { return this.Create().Select<DATN_2026.TypedViewClasses.inventoryStockRow, DATN_2026.HelperClasses.inventoryStockFields>(); }
		}

		/// <summary>Creates and returns the query to fetch the typed view Inventory.inventoryStockTransaction</summary>
		public DynamicQuery<DATN_2026.TypedViewClasses.inventoryStockTransactionRow> inventoryStockTransaction
		{
			get { return this.Create().Select<DATN_2026.TypedViewClasses.inventoryStockTransactionRow, DATN_2026.HelperClasses.inventoryStockTransactionFields>(); }
		}

		/// <summary>Creates and returns the query to fetch the typed view Marketing.marketingUserVoucher</summary>
		public DynamicQuery<DATN_2026.TypedViewClasses.marketingUserVoucherRow> marketingUserVoucher
		{
			get { return this.Create().Select<DATN_2026.TypedViewClasses.marketingUserVoucherRow, DATN_2026.HelperClasses.marketingUserVoucherFields>(); }
		}

		/// <summary>Creates and returns the query to fetch the typed view Marketing.marketingVoucher</summary>
		public DynamicQuery<DATN_2026.TypedViewClasses.marketingVoucherRow> marketingVoucher
		{
			get { return this.Create().Select<DATN_2026.TypedViewClasses.marketingVoucherRow, DATN_2026.HelperClasses.marketingVoucherFields>(); }
		}

		/// <summary>Creates and returns the query to fetch the typed view Sales.salesCart</summary>
		public DynamicQuery<DATN_2026.TypedViewClasses.salesCartRow> salesCart
		{
			get { return this.Create().Select<DATN_2026.TypedViewClasses.salesCartRow, DATN_2026.HelperClasses.salesCartFields>(); }
		}

		/// <summary>Creates and returns the query to fetch the typed view Sales.salesOrder</summary>
		public DynamicQuery<DATN_2026.TypedViewClasses.salesOrderRow> salesOrder
		{
			get { return this.Create().Select<DATN_2026.TypedViewClasses.salesOrderRow, DATN_2026.HelperClasses.salesOrderFields>(); }
		}

		/// <summary>Creates and returns the query to fetch the typed view Sales.salesOrderItem</summary>
		public DynamicQuery<DATN_2026.TypedViewClasses.salesOrderItemRow> salesOrderItem
		{
			get { return this.Create().Select<DATN_2026.TypedViewClasses.salesOrderItemRow, DATN_2026.HelperClasses.salesOrderItemFields>(); }
		}

		/// <summary>Creates and returns the query to fetch the typed view Sales.salesShippingTracking</summary>
		public DynamicQuery<DATN_2026.TypedViewClasses.salesShippingTrackingRow> salesShippingTracking
		{
			get { return this.Create().Select<DATN_2026.TypedViewClasses.salesShippingTrackingRow, DATN_2026.HelperClasses.salesShippingTrackingFields>(); }
		}

		/// <summary>Creates and returns the query to fetch the typed view Sales.salesTransaction</summary>
		public DynamicQuery<DATN_2026.TypedViewClasses.salesTransactionRow> salesTransaction
		{
			get { return this.Create().Select<DATN_2026.TypedViewClasses.salesTransactionRow, DATN_2026.HelperClasses.salesTransactionFields>(); }
		}

	}
}