//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.12.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
////////////////////////////////////////////////////////////// 
using System;
using System.Linq;
using DATN.EntityClasses;
using DATN.HelperClasses;
using SD.LLBLGen.Pro.ORMSupportClasses;
using SD.LLBLGen.Pro.QuerySpec.AdapterSpecific;
using SD.LLBLGen.Pro.QuerySpec;

namespace DATN.FactoryClasses
{
	/// <summary>Factory class to produce DynamicQuery instances and EntityQuery instances</summary>
	public partial class QueryFactory : QueryFactoryBase2
	{
		/// <summary>Creates and returns a new EntityQuery for the LoginAttempt entity</summary>
		public EntityQuery<LoginAttemptEntity> LoginAttempt { get { return Create<LoginAttemptEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the UserAuditLog entity</summary>
		public EntityQuery<UserAuditLogEntity> UserAuditLog { get { return Create<UserAuditLogEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the Permission entity</summary>
		public EntityQuery<PermissionEntity> Permission { get { return Create<PermissionEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the RefreshToken entity</summary>
		public EntityQuery<RefreshTokenEntity> RefreshToken { get { return Create<RefreshTokenEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the Role entity</summary>
		public EntityQuery<RoleEntity> Role { get { return Create<RoleEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the RolePermission entity</summary>
		public EntityQuery<RolePermissionEntity> RolePermission { get { return Create<RolePermissionEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the User entity</summary>
		public EntityQuery<UserEntity> User { get { return Create<UserEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the UserRole entity</summary>
		public EntityQuery<UserRoleEntity> UserRole { get { return Create<UserRoleEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the UserSession entity</summary>
		public EntityQuery<UserSessionEntity> UserSession { get { return Create<UserSessionEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the Brand entity</summary>
		public EntityQuery<BrandEntity> Brand { get { return Create<BrandEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the Category entity</summary>
		public EntityQuery<CategoryEntity> Category { get { return Create<CategoryEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the Product entity</summary>
		public EntityQuery<ProductEntity> Product { get { return Create<ProductEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the ProductImage entity</summary>
		public EntityQuery<ProductImageEntity> ProductImage { get { return Create<ProductImageEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the ProductVariant entity</summary>
		public EntityQuery<ProductVariantEntity> ProductVariant { get { return Create<ProductVariantEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the engagementReview entity</summary>
		public EntityQuery<engagementReviewEntity> engagementReview { get { return Create<engagementReviewEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the Notification entity</summary>
		public EntityQuery<NotificationEntity> Notification { get { return Create<NotificationEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the salesCart entity</summary>
		public EntityQuery<salesCartEntity> salesCart { get { return Create<salesCartEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the salesOrder entity</summary>
		public EntityQuery<salesOrderEntity> salesOrder { get { return Create<salesOrderEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the salesOrderItem entity</summary>
		public EntityQuery<salesOrderItemEntity> salesOrderItem { get { return Create<salesOrderItemEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the Transaction entity</summary>
		public EntityQuery<TransactionEntity> Transaction { get { return Create<TransactionEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the Cart entity</summary>
		public EntityQuery<CartEntity> Cart { get { return Create<CartEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the Discount entity</summary>
		public EntityQuery<DiscountEntity> Discount { get { return Create<DiscountEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the Game entity</summary>
		public EntityQuery<GameEntity> Game { get { return Create<GameEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the GameTag entity</summary>
		public EntityQuery<GameTagEntity> GameTag { get { return Create<GameTagEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the Order entity</summary>
		public EntityQuery<OrderEntity> Order { get { return Create<OrderEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the OrderItem entity</summary>
		public EntityQuery<OrderItemEntity> OrderItem { get { return Create<OrderItemEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the Publisher entity</summary>
		public EntityQuery<PublisherEntity> Publisher { get { return Create<PublisherEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the Review entity</summary>
		public EntityQuery<ReviewEntity> Review { get { return Create<ReviewEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the Tag entity</summary>
		public EntityQuery<TagEntity> Tag { get { return Create<TagEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the UserGame entity</summary>
		public EntityQuery<UserGameEntity> UserGame { get { return Create<UserGameEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the Wishlist entity</summary>
		public EntityQuery<WishlistEntity> Wishlist { get { return Create<WishlistEntity>(); } }

		/// <inheritdoc/>
		protected override IElementCreatorCore CreateElementCreator() { return new ElementCreator(); }
 
		/// <summary>Creates and returns the query to fetch the typed view Audit.auditLoginAttempt</summary>
		public DynamicQuery<DATN.TypedViewClasses.auditLoginAttemptRow> auditLoginAttempt
		{
			get { return this.Create().Select<DATN.TypedViewClasses.auditLoginAttemptRow, DATN.HelperClasses.auditLoginAttemptFields>(); }
		}

		/// <summary>Creates and returns the query to fetch the typed view Audit.auditUserAuditLog</summary>
		public DynamicQuery<DATN.TypedViewClasses.auditUserAuditLogRow> auditUserAuditLog
		{
			get { return this.Create().Select<DATN.TypedViewClasses.auditUserAuditLogRow, DATN.HelperClasses.auditUserAuditLogFields>(); }
		}

		/// <summary>Creates and returns the query to fetch the typed view Auth2.auth2Permission</summary>
		public DynamicQuery<DATN.TypedViewClasses.auth2PermissionRow> auth2Permission
		{
			get { return this.Create().Select<DATN.TypedViewClasses.auth2PermissionRow, DATN.HelperClasses.auth2PermissionFields>(); }
		}

		/// <summary>Creates and returns the query to fetch the typed view Auth2.auth2RefreshToken</summary>
		public DynamicQuery<DATN.TypedViewClasses.auth2RefreshTokenRow> auth2RefreshToken
		{
			get { return this.Create().Select<DATN.TypedViewClasses.auth2RefreshTokenRow, DATN.HelperClasses.auth2RefreshTokenFields>(); }
		}

		/// <summary>Creates and returns the query to fetch the typed view Auth2.auth2Role</summary>
		public DynamicQuery<DATN.TypedViewClasses.auth2RoleRow> auth2Role
		{
			get { return this.Create().Select<DATN.TypedViewClasses.auth2RoleRow, DATN.HelperClasses.auth2RoleFields>(); }
		}

		/// <summary>Creates and returns the query to fetch the typed view Auth2.auth2RolePermission</summary>
		public DynamicQuery<DATN.TypedViewClasses.auth2RolePermissionRow> auth2RolePermission
		{
			get { return this.Create().Select<DATN.TypedViewClasses.auth2RolePermissionRow, DATN.HelperClasses.auth2RolePermissionFields>(); }
		}

		/// <summary>Creates and returns the query to fetch the typed view Auth2.auth2User</summary>
		public DynamicQuery<DATN.TypedViewClasses.auth2UserRow> auth2User
		{
			get { return this.Create().Select<DATN.TypedViewClasses.auth2UserRow, DATN.HelperClasses.auth2UserFields>(); }
		}

		/// <summary>Creates and returns the query to fetch the typed view Auth2.auth2UserRole</summary>
		public DynamicQuery<DATN.TypedViewClasses.auth2UserRoleRow> auth2UserRole
		{
			get { return this.Create().Select<DATN.TypedViewClasses.auth2UserRoleRow, DATN.HelperClasses.auth2UserRoleFields>(); }
		}

		/// <summary>Creates and returns the query to fetch the typed view Auth2.auth2UserSession</summary>
		public DynamicQuery<DATN.TypedViewClasses.auth2UserSessionRow> auth2UserSession
		{
			get { return this.Create().Select<DATN.TypedViewClasses.auth2UserSessionRow, DATN.HelperClasses.auth2UserSessionFields>(); }
		}

		/// <summary>Creates and returns the query to fetch the typed view Catalog.catalogBrand</summary>
		public DynamicQuery<DATN.TypedViewClasses.catalogBrandRow> catalogBrand
		{
			get { return this.Create().Select<DATN.TypedViewClasses.catalogBrandRow, DATN.HelperClasses.catalogBrandFields>(); }
		}

		/// <summary>Creates and returns the query to fetch the typed view Catalog.catalogCategory</summary>
		public DynamicQuery<DATN.TypedViewClasses.catalogCategoryRow> catalogCategory
		{
			get { return this.Create().Select<DATN.TypedViewClasses.catalogCategoryRow, DATN.HelperClasses.catalogCategoryFields>(); }
		}

		/// <summary>Creates and returns the query to fetch the typed view Catalog.catalogProduct</summary>
		public DynamicQuery<DATN.TypedViewClasses.catalogProductRow> catalogProduct
		{
			get { return this.Create().Select<DATN.TypedViewClasses.catalogProductRow, DATN.HelperClasses.catalogProductFields>(); }
		}

		/// <summary>Creates and returns the query to fetch the typed view Catalog.catalogProductImage</summary>
		public DynamicQuery<DATN.TypedViewClasses.catalogProductImageRow> catalogProductImage
		{
			get { return this.Create().Select<DATN.TypedViewClasses.catalogProductImageRow, DATN.HelperClasses.catalogProductImageFields>(); }
		}

		/// <summary>Creates and returns the query to fetch the typed view Catalog.catalogProductVariant</summary>
		public DynamicQuery<DATN.TypedViewClasses.catalogProductVariantRow> catalogProductVariant
		{
			get { return this.Create().Select<DATN.TypedViewClasses.catalogProductVariantRow, DATN.HelperClasses.catalogProductVariantFields>(); }
		}

		/// <summary>Creates and returns the query to fetch the typed view Engagement.engagementNotification</summary>
		public DynamicQuery<DATN.TypedViewClasses.engagementNotificationRow> engagementNotification
		{
			get { return this.Create().Select<DATN.TypedViewClasses.engagementNotificationRow, DATN.HelperClasses.engagementNotificationFields>(); }
		}

		/// <summary>Creates and returns the query to fetch the typed view Engagement.engagementReview1</summary>
		public DynamicQuery<DATN.TypedViewClasses.engagementReview1Row> engagementReview1
		{
			get { return this.Create().Select<DATN.TypedViewClasses.engagementReview1Row, DATN.HelperClasses.engagementReview1Fields>(); }
		}

		/// <summary>Creates and returns the query to fetch the typed view Sales.salesCart1</summary>
		public DynamicQuery<DATN.TypedViewClasses.salesCart1Row> salesCart1
		{
			get { return this.Create().Select<DATN.TypedViewClasses.salesCart1Row, DATN.HelperClasses.salesCart1Fields>(); }
		}

		/// <summary>Creates and returns the query to fetch the typed view Sales.salesOrder1</summary>
		public DynamicQuery<DATN.TypedViewClasses.salesOrder1Row> salesOrder1
		{
			get { return this.Create().Select<DATN.TypedViewClasses.salesOrder1Row, DATN.HelperClasses.salesOrder1Fields>(); }
		}

		/// <summary>Creates and returns the query to fetch the typed view Sales.salesOrderItem1</summary>
		public DynamicQuery<DATN.TypedViewClasses.salesOrderItem1Row> salesOrderItem1
		{
			get { return this.Create().Select<DATN.TypedViewClasses.salesOrderItem1Row, DATN.HelperClasses.salesOrderItem1Fields>(); }
		}

		/// <summary>Creates and returns the query to fetch the typed view Sales.salesTransaction</summary>
		public DynamicQuery<DATN.TypedViewClasses.salesTransactionRow> salesTransaction
		{
			get { return this.Create().Select<DATN.TypedViewClasses.salesTransactionRow, DATN.HelperClasses.salesTransactionFields>(); }
		}

		/// <summary>Creates and returns the query to fetch the typed view Store.storeCart</summary>
		public DynamicQuery<DATN.TypedViewClasses.storeCartRow> storeCart
		{
			get { return this.Create().Select<DATN.TypedViewClasses.storeCartRow, DATN.HelperClasses.storeCartFields>(); }
		}

		/// <summary>Creates and returns the query to fetch the typed view Store.storeDiscount</summary>
		public DynamicQuery<DATN.TypedViewClasses.storeDiscountRow> storeDiscount
		{
			get { return this.Create().Select<DATN.TypedViewClasses.storeDiscountRow, DATN.HelperClasses.storeDiscountFields>(); }
		}

		/// <summary>Creates and returns the query to fetch the typed view Store.storeGame</summary>
		public DynamicQuery<DATN.TypedViewClasses.storeGameRow> storeGame
		{
			get { return this.Create().Select<DATN.TypedViewClasses.storeGameRow, DATN.HelperClasses.storeGameFields>(); }
		}

		/// <summary>Creates and returns the query to fetch the typed view Store.storeGameTag</summary>
		public DynamicQuery<DATN.TypedViewClasses.storeGameTagRow> storeGameTag
		{
			get { return this.Create().Select<DATN.TypedViewClasses.storeGameTagRow, DATN.HelperClasses.storeGameTagFields>(); }
		}

		/// <summary>Creates and returns the query to fetch the typed view Store.storeOrder</summary>
		public DynamicQuery<DATN.TypedViewClasses.storeOrderRow> storeOrder
		{
			get { return this.Create().Select<DATN.TypedViewClasses.storeOrderRow, DATN.HelperClasses.storeOrderFields>(); }
		}

		/// <summary>Creates and returns the query to fetch the typed view Store.storeOrderItem</summary>
		public DynamicQuery<DATN.TypedViewClasses.storeOrderItemRow> storeOrderItem
		{
			get { return this.Create().Select<DATN.TypedViewClasses.storeOrderItemRow, DATN.HelperClasses.storeOrderItemFields>(); }
		}

		/// <summary>Creates and returns the query to fetch the typed view Store.storePublisher</summary>
		public DynamicQuery<DATN.TypedViewClasses.storePublisherRow> storePublisher
		{
			get { return this.Create().Select<DATN.TypedViewClasses.storePublisherRow, DATN.HelperClasses.storePublisherFields>(); }
		}

		/// <summary>Creates and returns the query to fetch the typed view Store.storeReview</summary>
		public DynamicQuery<DATN.TypedViewClasses.storeReviewRow> storeReview
		{
			get { return this.Create().Select<DATN.TypedViewClasses.storeReviewRow, DATN.HelperClasses.storeReviewFields>(); }
		}

		/// <summary>Creates and returns the query to fetch the typed view Store.storeTag</summary>
		public DynamicQuery<DATN.TypedViewClasses.storeTagRow> storeTag
		{
			get { return this.Create().Select<DATN.TypedViewClasses.storeTagRow, DATN.HelperClasses.storeTagFields>(); }
		}

		/// <summary>Creates and returns the query to fetch the typed view Store.storeUserGame</summary>
		public DynamicQuery<DATN.TypedViewClasses.storeUserGameRow> storeUserGame
		{
			get { return this.Create().Select<DATN.TypedViewClasses.storeUserGameRow, DATN.HelperClasses.storeUserGameFields>(); }
		}

		/// <summary>Creates and returns the query to fetch the typed view Store.storeWishlist</summary>
		public DynamicQuery<DATN.TypedViewClasses.storeWishlistRow> storeWishlist
		{
			get { return this.Create().Select<DATN.TypedViewClasses.storeWishlistRow, DATN.HelperClasses.storeWishlistFields>(); }
		}

	}
}