//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.12.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using DATN_2026.HelperClasses;
using DATN_2026.FactoryClasses;
using DATN_2026.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace DATN_2026.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END
	/// <summary>Entity class which represents the entity 'Category'.<br/><br/></summary>
	[Serializable]
	public partial class CategoryEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END	
	{
		private EntityCollection<CategoryEntity> _categories;
		private EntityCollection<ProductEntity> _products;
		private CategoryEntity _category;

		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END
		private static CategoryEntityStaticMetaData _staticMetaData = new CategoryEntityStaticMetaData();
		private static CategoryRelations _relationsFactory = new CategoryRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name Category</summary>
			public static readonly string Category = "Category";
			/// <summary>Member name Categories</summary>
			public static readonly string Categories = "Categories";
			/// <summary>Member name Products</summary>
			public static readonly string Products = "Products";
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class CategoryEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public CategoryEntityStaticMetaData()
			{
				SetEntityCoreInfo("CategoryEntity", InheritanceHierarchyType.None, false, (int)DATN_2026.EntityType.CategoryEntity, typeof(CategoryEntity), typeof(CategoryEntityFactory), false);
				AddNavigatorMetaData<CategoryEntity, EntityCollection<CategoryEntity>>("Categories", a => a._categories, (a, b) => a._categories = b, a => a.Categories, () => new CategoryRelations().CategoryEntityUsingParentId, typeof(CategoryEntity), (int)DATN_2026.EntityType.CategoryEntity);
				AddNavigatorMetaData<CategoryEntity, EntityCollection<ProductEntity>>("Products", a => a._products, (a, b) => a._products = b, a => a.Products, () => new CategoryRelations().ProductEntityUsingCategoryId, typeof(ProductEntity), (int)DATN_2026.EntityType.ProductEntity);
				AddNavigatorMetaData<CategoryEntity, CategoryEntity>("Category", "Categories", (a, b) => a._category = b, a => a._category, (a, b) => a.Category = b, DATN_2026.RelationClasses.StaticCategoryRelations.CategoryEntityUsingIdParentIdStatic, ()=>new CategoryRelations().CategoryEntityUsingIdParentId, null, new int[] { (int)CategoryFieldIndex.ParentId }, null, true, (int)DATN_2026.EntityType.CategoryEntity);
			}
		}

		/// <summary>Static ctor</summary>
		static CategoryEntity()
		{
		}

		/// <summary> CTor</summary>
		public CategoryEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public CategoryEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this CategoryEntity</param>
		public CategoryEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for Category which data should be fetched into this Category object</param>
		public CategoryEntity(System.Guid id) : this(id, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for Category which data should be fetched into this Category object</param>
		/// <param name="validator">The custom validator object for this CategoryEntity</param>
		public CategoryEntity(System.Guid id, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.Id = id;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected CategoryEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		/// <summary>Method which will construct a filter (predicate expression) for the unique constraint defined on the fields: Slug .</summary>
		/// <returns>true if succeeded and the contents is read, false otherwise</returns>
		public IPredicateExpression ConstructFilterForUCSlug()
		{
			var filter = new PredicateExpression();
			filter.Add(DATN_2026.HelperClasses.CategoryFields.Slug == this.Fields.GetCurrentValue((int)CategoryFieldIndex.Slug));
 			return filter;
		}

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'Category' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoCategories() { return CreateRelationInfoForNavigator("Categories"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'Product' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoProducts() { return CreateRelationInfoForNavigator("Products"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'Category' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoCategory() { return CreateRelationInfoForNavigator("Category"); }
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END
			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this CategoryEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static CategoryRelations Relations { get { return _relationsFactory; } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'Category' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathCategories { get { return _staticMetaData.GetPrefetchPathElement("Categories", CommonEntityBase.CreateEntityCollection<CategoryEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'Product' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathProducts { get { return _staticMetaData.GetPrefetchPathElement("Products", CommonEntityBase.CreateEntityCollection<ProductEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'Category' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathCategory { get { return _staticMetaData.GetPrefetchPathElement("Category", CommonEntityBase.CreateEntityCollection<CategoryEntity>()); } }

		/// <summary>The CreatedAt property of the Entity Category<br/><br/></summary>
		/// <remarks>Mapped on  table field: "categories"."created_at".<br/>Table field type characteristics (type, precision, scale, length): TimestampTz, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.DateTime> CreatedAt
		{
			get { return (Nullable<System.DateTime>)GetValue((int)CategoryFieldIndex.CreatedAt, false); }
			set { SetValue((int)CategoryFieldIndex.CreatedAt, value); }
		}

		/// <summary>The DisplayOrder property of the Entity Category<br/><br/></summary>
		/// <remarks>Mapped on  table field: "categories"."display_order".<br/>Table field type characteristics (type, precision, scale, length): Integer, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> DisplayOrder
		{
			get { return (Nullable<System.Int32>)GetValue((int)CategoryFieldIndex.DisplayOrder, false); }
			set { SetValue((int)CategoryFieldIndex.DisplayOrder, value); }
		}

		/// <summary>The IconUrl property of the Entity Category<br/><br/></summary>
		/// <remarks>Mapped on  table field: "categories"."icon_url".<br/>Table field type characteristics (type, precision, scale, length): Text, 0, 0, 1073741824.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String IconUrl
		{
			get { return (System.String)GetValue((int)CategoryFieldIndex.IconUrl, true); }
			set { SetValue((int)CategoryFieldIndex.IconUrl, value); }
		}

		/// <summary>The Id property of the Entity Category<br/><br/></summary>
		/// <remarks>Mapped on  table field: "categories"."id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, false</remarks>
		public virtual System.Guid Id
		{
			get { return (System.Guid)GetValue((int)CategoryFieldIndex.Id, true); }
			set { SetValue((int)CategoryFieldIndex.Id, value); }
		}

		/// <summary>The IsActive property of the Entity Category<br/><br/></summary>
		/// <remarks>Mapped on  table field: "categories"."is_active".<br/>Table field type characteristics (type, precision, scale, length): Boolean, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Boolean> IsActive
		{
			get { return (Nullable<System.Boolean>)GetValue((int)CategoryFieldIndex.IsActive, false); }
			set { SetValue((int)CategoryFieldIndex.IsActive, value); }
		}

		/// <summary>The Name property of the Entity Category<br/><br/></summary>
		/// <remarks>Mapped on  table field: "categories"."name".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 255.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String Name
		{
			get { return (System.String)GetValue((int)CategoryFieldIndex.Name, true); }
			set { SetValue((int)CategoryFieldIndex.Name, value); }
		}

		/// <summary>The ParentId property of the Entity Category<br/><br/></summary>
		/// <remarks>Mapped on  table field: "categories"."parent_id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Guid> ParentId
		{
			get { return (Nullable<System.Guid>)GetValue((int)CategoryFieldIndex.ParentId, false); }
			set { SetValue((int)CategoryFieldIndex.ParentId, value); }
		}

		/// <summary>The Slug property of the Entity Category<br/><br/></summary>
		/// <remarks>Mapped on  table field: "categories"."slug".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 255.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String Slug
		{
			get { return (System.String)GetValue((int)CategoryFieldIndex.Slug, true); }
			set { SetValue((int)CategoryFieldIndex.Slug, value); }
		}

		/// <summary>Gets the EntityCollection with the related entities of type 'CategoryEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(CategoryEntity))]
		public virtual EntityCollection<CategoryEntity> Categories { get { return GetOrCreateEntityCollection<CategoryEntity, CategoryEntityFactory>("Category", true, false, ref _categories); } }

		/// <summary>Gets the EntityCollection with the related entities of type 'ProductEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(ProductEntity))]
		public virtual EntityCollection<ProductEntity> Products { get { return GetOrCreateEntityCollection<ProductEntity, ProductEntityFactory>("Category", true, false, ref _products); } }

		/// <summary>Gets / sets related entity of type 'CategoryEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual CategoryEntity Category
		{
			get { return _category; }
			set { SetSingleRelatedEntityNavigator(value, "Category"); }
		}

		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END

	}
}

namespace DATN_2026
{
	public enum CategoryFieldIndex
	{
		///<summary>CreatedAt. </summary>
		CreatedAt,
		///<summary>DisplayOrder. </summary>
		DisplayOrder,
		///<summary>IconUrl. </summary>
		IconUrl,
		///<summary>Id. </summary>
		Id,
		///<summary>IsActive. </summary>
		IsActive,
		///<summary>Name. </summary>
		Name,
		///<summary>ParentId. </summary>
		ParentId,
		///<summary>Slug. </summary>
		Slug,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace DATN_2026.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: Category. </summary>
	public partial class CategoryRelations: RelationFactory
	{
		/// <summary>Returns a new IEntityRelation object, between CategoryEntity and CategoryEntity over the 1:n relation they have, using the relation between the fields: Category.Id - Category.ParentId</summary>
		public virtual IEntityRelation CategoryEntityUsingParentId
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "Categories", true, new[] { CategoryFields.Id, CategoryFields.ParentId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between CategoryEntity and ProductEntity over the 1:n relation they have, using the relation between the fields: Category.Id - Product.CategoryId</summary>
		public virtual IEntityRelation ProductEntityUsingCategoryId
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "Products", true, new[] { CategoryFields.Id, ProductFields.CategoryId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between CategoryEntity and CategoryEntity over the m:1 relation they have, using the relation between the fields: Category.ParentId - Category.Id</summary>
		public virtual IEntityRelation CategoryEntityUsingIdParentId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "Category", false, new[] { CategoryFields.Id, CategoryFields.ParentId }); }
		}

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticCategoryRelations
	{
		internal static readonly IEntityRelation CategoryEntityUsingParentIdStatic = new CategoryRelations().CategoryEntityUsingParentId;
		internal static readonly IEntityRelation ProductEntityUsingCategoryIdStatic = new CategoryRelations().ProductEntityUsingCategoryId;
		internal static readonly IEntityRelation CategoryEntityUsingIdParentIdStatic = new CategoryRelations().CategoryEntityUsingIdParentId;

		/// <summary>CTor</summary>
		static StaticCategoryRelations() { }
	}
}
