//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.12.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using DATN_2026.HelperClasses;
using DATN_2026.FactoryClasses;
using DATN_2026.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace DATN_2026.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END

	/// <summary>Entity class which represents the entity 'ChatBox'.<br/><br/></summary>
	[Serializable]
	public partial class ChatBoxEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END
	
	{
		private EntityCollection<ChatMessageEntity> _chatMessages;
		private UserEntity _user;
		private ShopEntity _shop;
		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END

		private static ChatBoxEntityStaticMetaData _staticMetaData = new ChatBoxEntityStaticMetaData();
		private static ChatBoxRelations _relationsFactory = new ChatBoxRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name User</summary>
			public static readonly string User = "User";
			/// <summary>Member name Shop</summary>
			public static readonly string Shop = "Shop";
			/// <summary>Member name ChatMessages</summary>
			public static readonly string ChatMessages = "ChatMessages";
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class ChatBoxEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public ChatBoxEntityStaticMetaData()
			{
				SetEntityCoreInfo("ChatBoxEntity", InheritanceHierarchyType.None, false, (int)DATN_2026.EntityType.ChatBoxEntity, typeof(ChatBoxEntity), typeof(ChatBoxEntityFactory), false);
				AddNavigatorMetaData<ChatBoxEntity, EntityCollection<ChatMessageEntity>>("ChatMessages", a => a._chatMessages, (a, b) => a._chatMessages = b, a => a.ChatMessages, () => new ChatBoxRelations().ChatMessageEntityUsingRoomId, typeof(ChatMessageEntity), (int)DATN_2026.EntityType.ChatMessageEntity);
				AddNavigatorMetaData<ChatBoxEntity, UserEntity>("User", "ChatBoxes", (a, b) => a._user = b, a => a._user, (a, b) => a.User = b, DATN_2026.RelationClasses.StaticChatBoxRelations.UserEntityUsingUserIdStatic, ()=>new ChatBoxRelations().UserEntityUsingUserId, null, new int[] { (int)ChatBoxFieldIndex.UserId }, null, true, (int)DATN_2026.EntityType.UserEntity);
				AddNavigatorMetaData<ChatBoxEntity, ShopEntity>("Shop", "ChatBoxes", (a, b) => a._shop = b, a => a._shop, (a, b) => a.Shop = b, DATN_2026.RelationClasses.StaticChatBoxRelations.ShopEntityUsingShopIdStatic, ()=>new ChatBoxRelations().ShopEntityUsingShopId, null, new int[] { (int)ChatBoxFieldIndex.ShopId }, null, true, (int)DATN_2026.EntityType.ShopEntity);
			}
		}

		/// <summary>Static ctor</summary>
		static ChatBoxEntity()
		{
		}

		/// <summary> CTor</summary>
		public ChatBoxEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public ChatBoxEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this ChatBoxEntity</param>
		public ChatBoxEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for ChatBox which data should be fetched into this ChatBox object</param>
		public ChatBoxEntity(System.Guid id) : this(id, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for ChatBox which data should be fetched into this ChatBox object</param>
		/// <param name="validator">The custom validator object for this ChatBoxEntity</param>
		public ChatBoxEntity(System.Guid id, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.Id = id;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected ChatBoxEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		/// <summary>Method which will construct a filter (predicate expression) for the unique constraint defined on the fields: ShopId , UserId .</summary>
		/// <returns>true if succeeded and the contents is read, false otherwise</returns>
		public IPredicateExpression ConstructFilterForUCShopIdUserId()
		{
			var filter = new PredicateExpression();
			filter.Add(DATN_2026.HelperClasses.ChatBoxFields.ShopId == this.Fields.GetCurrentValue((int)ChatBoxFieldIndex.ShopId));
			filter.Add(DATN_2026.HelperClasses.ChatBoxFields.UserId == this.Fields.GetCurrentValue((int)ChatBoxFieldIndex.UserId));
 			return filter;
		}

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'ChatMessage' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoChatMessages() { return CreateRelationInfoForNavigator("ChatMessages"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'User' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoUser() { return CreateRelationInfoForNavigator("User"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'Shop' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoShop() { return CreateRelationInfoForNavigator("Shop"); }
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this ChatBoxEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END


			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static ChatBoxRelations Relations { get { return _relationsFactory; } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'ChatMessage' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathChatMessages { get { return _staticMetaData.GetPrefetchPathElement("ChatMessages", CommonEntityBase.CreateEntityCollection<ChatMessageEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'User' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathUser { get { return _staticMetaData.GetPrefetchPathElement("User", CommonEntityBase.CreateEntityCollection<UserEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'Shop' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathShop { get { return _staticMetaData.GetPrefetchPathElement("Shop", CommonEntityBase.CreateEntityCollection<ShopEntity>()); } }

		/// <summary>The Id property of the Entity ChatBox<br/><br/></summary>
		/// <remarks>Mapped on  table field: "chat_box"."id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, false</remarks>
		public virtual System.Guid Id
		{
			get { return (System.Guid)GetValue((int)ChatBoxFieldIndex.Id, true); }
			set { SetValue((int)ChatBoxFieldIndex.Id, value); }
		}

		/// <summary>The LastActivity property of the Entity ChatBox<br/><br/></summary>
		/// <remarks>Mapped on  table field: "chat_box"."last_activity".<br/>Table field type characteristics (type, precision, scale, length): TimestampTz, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.DateTime> LastActivity
		{
			get { return (Nullable<System.DateTime>)GetValue((int)ChatBoxFieldIndex.LastActivity, false); }
			set { SetValue((int)ChatBoxFieldIndex.LastActivity, value); }
		}

		/// <summary>The LastMessage property of the Entity ChatBox<br/><br/></summary>
		/// <remarks>Mapped on  table field: "chat_box"."last_message".<br/>Table field type characteristics (type, precision, scale, length): Text, 0, 0, 1073741824.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String LastMessage
		{
			get { return (System.String)GetValue((int)ChatBoxFieldIndex.LastMessage, true); }
			set { SetValue((int)ChatBoxFieldIndex.LastMessage, value); }
		}

		/// <summary>The ShopId property of the Entity ChatBox<br/><br/></summary>
		/// <remarks>Mapped on  table field: "chat_box"."shop_id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Guid> ShopId
		{
			get { return (Nullable<System.Guid>)GetValue((int)ChatBoxFieldIndex.ShopId, false); }
			set { SetValue((int)ChatBoxFieldIndex.ShopId, value); }
		}

		/// <summary>The UserId property of the Entity ChatBox<br/><br/></summary>
		/// <remarks>Mapped on  table field: "chat_box"."user_id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Guid> UserId
		{
			get { return (Nullable<System.Guid>)GetValue((int)ChatBoxFieldIndex.UserId, false); }
			set { SetValue((int)ChatBoxFieldIndex.UserId, value); }
		}

		/// <summary>Gets the EntityCollection with the related entities of type 'ChatMessageEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(ChatMessageEntity))]
		public virtual EntityCollection<ChatMessageEntity> ChatMessages { get { return GetOrCreateEntityCollection<ChatMessageEntity, ChatMessageEntityFactory>("ChatBox", true, false, ref _chatMessages); } }

		/// <summary>Gets / sets related entity of type 'UserEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual UserEntity User
		{
			get { return _user; }
			set { SetSingleRelatedEntityNavigator(value, "User"); }
		}

		/// <summary>Gets / sets related entity of type 'ShopEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual ShopEntity Shop
		{
			get { return _shop; }
			set { SetSingleRelatedEntityNavigator(value, "Shop"); }
		}
		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END


	}
}

namespace DATN_2026
{
	public enum ChatBoxFieldIndex
	{
		///<summary>Id. </summary>
		Id,
		///<summary>LastActivity. </summary>
		LastActivity,
		///<summary>LastMessage. </summary>
		LastMessage,
		///<summary>ShopId. </summary>
		ShopId,
		///<summary>UserId. </summary>
		UserId,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace DATN_2026.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: ChatBox. </summary>
	public partial class ChatBoxRelations: RelationFactory
	{
		/// <summary>Returns a new IEntityRelation object, between ChatBoxEntity and ChatMessageEntity over the 1:n relation they have, using the relation between the fields: ChatBox.Id - ChatMessage.RoomId</summary>
		public virtual IEntityRelation ChatMessageEntityUsingRoomId
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "ChatMessages", true, new[] { ChatBoxFields.Id, ChatMessageFields.RoomId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between ChatBoxEntity and UserEntity over the m:1 relation they have, using the relation between the fields: ChatBox.UserId - User.Id</summary>
		public virtual IEntityRelation UserEntityUsingUserId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "User", false, new[] { UserFields.Id, ChatBoxFields.UserId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between ChatBoxEntity and ShopEntity over the m:1 relation they have, using the relation between the fields: ChatBox.ShopId - Shop.Id</summary>
		public virtual IEntityRelation ShopEntityUsingShopId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "Shop", false, new[] { ShopFields.Id, ChatBoxFields.ShopId }); }
		}

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticChatBoxRelations
	{
		internal static readonly IEntityRelation ChatMessageEntityUsingRoomIdStatic = new ChatBoxRelations().ChatMessageEntityUsingRoomId;
		internal static readonly IEntityRelation UserEntityUsingUserIdStatic = new ChatBoxRelations().UserEntityUsingUserId;
		internal static readonly IEntityRelation ShopEntityUsingShopIdStatic = new ChatBoxRelations().ShopEntityUsingShopId;

		/// <summary>CTor</summary>
		static StaticChatBoxRelations() { }
	}
}
