//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.12.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using DATN.HelperClasses;
using DATN.FactoryClasses;
using DATN.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace DATN.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END
	/// <summary>Entity class which represents the entity 'Discount'.<br/><br/></summary>
	[Serializable]
	public partial class DiscountEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END	
	{
		private GameEntity _game;

		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END
		private static DiscountEntityStaticMetaData _staticMetaData = new DiscountEntityStaticMetaData();
		private static DiscountRelations _relationsFactory = new DiscountRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name Game</summary>
			public static readonly string Game = "Game";
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class DiscountEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public DiscountEntityStaticMetaData()
			{
				SetEntityCoreInfo("DiscountEntity", InheritanceHierarchyType.None, false, (int)DATN.EntityType.DiscountEntity, typeof(DiscountEntity), typeof(DiscountEntityFactory), false);
				AddNavigatorMetaData<DiscountEntity, GameEntity>("Game", "Discounts", (a, b) => a._game = b, a => a._game, (a, b) => a.Game = b, DATN.RelationClasses.StaticDiscountRelations.GameEntityUsingGameIdStatic, ()=>new DiscountRelations().GameEntityUsingGameId, null, new int[] { (int)DiscountFieldIndex.GameId }, null, true, (int)DATN.EntityType.GameEntity);
			}
		}

		/// <summary>Static ctor</summary>
		static DiscountEntity()
		{
		}

		/// <summary> CTor</summary>
		public DiscountEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public DiscountEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this DiscountEntity</param>
		public DiscountEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for Discount which data should be fetched into this Discount object</param>
		public DiscountEntity(System.Guid id) : this(id, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for Discount which data should be fetched into this Discount object</param>
		/// <param name="validator">The custom validator object for this DiscountEntity</param>
		public DiscountEntity(System.Guid id, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.Id = id;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected DiscountEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'Game' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoGame() { return CreateRelationInfoForNavigator("Game"); }
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END
			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this DiscountEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static DiscountRelations Relations { get { return _relationsFactory; } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'Game' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathGame { get { return _staticMetaData.GetPrefetchPathElement("Game", CommonEntityBase.CreateEntityCollection<GameEntity>()); } }

		/// <summary>The DiscountPercent property of the Entity Discount<br/><br/></summary>
		/// <remarks>Mapped on  table field: "discounts"."discount_percent".<br/>Table field type characteristics (type, precision, scale, length): Integer, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Int32 DiscountPercent
		{
			get { return (System.Int32)GetValue((int)DiscountFieldIndex.DiscountPercent, true); }
			set { SetValue((int)DiscountFieldIndex.DiscountPercent, value); }
		}

		/// <summary>The EndDate property of the Entity Discount<br/><br/></summary>
		/// <remarks>Mapped on  table field: "discounts"."end_date".<br/>Table field type characteristics (type, precision, scale, length): Timestamp, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.DateTime EndDate
		{
			get { return (System.DateTime)GetValue((int)DiscountFieldIndex.EndDate, true); }
			set { SetValue((int)DiscountFieldIndex.EndDate, value); }
		}

		/// <summary>The GameId property of the Entity Discount<br/><br/></summary>
		/// <remarks>Mapped on  table field: "discounts"."game_id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Guid GameId
		{
			get { return (System.Guid)GetValue((int)DiscountFieldIndex.GameId, true); }
			set { SetValue((int)DiscountFieldIndex.GameId, value); }
		}

		/// <summary>The Id property of the Entity Discount<br/><br/></summary>
		/// <remarks>Mapped on  table field: "discounts"."id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, false</remarks>
		public virtual System.Guid Id
		{
			get { return (System.Guid)GetValue((int)DiscountFieldIndex.Id, true); }
			set { SetValue((int)DiscountFieldIndex.Id, value); }
		}

		/// <summary>The StartDate property of the Entity Discount<br/><br/></summary>
		/// <remarks>Mapped on  table field: "discounts"."start_date".<br/>Table field type characteristics (type, precision, scale, length): Timestamp, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.DateTime StartDate
		{
			get { return (System.DateTime)GetValue((int)DiscountFieldIndex.StartDate, true); }
			set { SetValue((int)DiscountFieldIndex.StartDate, value); }
		}

		/// <summary>Gets / sets related entity of type 'GameEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual GameEntity Game
		{
			get { return _game; }
			set { SetSingleRelatedEntityNavigator(value, "Game"); }
		}

		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END

	}
}

namespace DATN
{
	public enum DiscountFieldIndex
	{
		///<summary>DiscountPercent. </summary>
		DiscountPercent,
		///<summary>EndDate. </summary>
		EndDate,
		///<summary>GameId. </summary>
		GameId,
		///<summary>Id. </summary>
		Id,
		///<summary>StartDate. </summary>
		StartDate,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace DATN.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: Discount. </summary>
	public partial class DiscountRelations: RelationFactory
	{

		/// <summary>Returns a new IEntityRelation object, between DiscountEntity and GameEntity over the m:1 relation they have, using the relation between the fields: Discount.GameId - Game.Id</summary>
		public virtual IEntityRelation GameEntityUsingGameId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "Game", false, new[] { GameFields.Id, DiscountFields.GameId }); }
		}

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticDiscountRelations
	{
		internal static readonly IEntityRelation GameEntityUsingGameIdStatic = new DiscountRelations().GameEntityUsingGameId;

		/// <summary>CTor</summary>
		static StaticDiscountRelations() { }
	}
}
