//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.12.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using DATN.HelperClasses;
using DATN.FactoryClasses;
using DATN.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace DATN.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END
	/// <summary>Entity class which represents the entity 'engagementReview'.<br/><br/></summary>
	[Serializable]
	public partial class engagementReviewEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END	
	{
		private UserEntity _user;
		private ProductVariantEntity _productVariant;
		private salesOrderEntity _salesOrder;

		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END
		private static engagementReviewEntityStaticMetaData _staticMetaData = new engagementReviewEntityStaticMetaData();
		private static engagementReviewRelations _relationsFactory = new engagementReviewRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name User</summary>
			public static readonly string User = "User";
			/// <summary>Member name ProductVariant</summary>
			public static readonly string ProductVariant = "ProductVariant";
			/// <summary>Member name salesOrder</summary>
			public static readonly string salesOrder = "salesOrder";
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class engagementReviewEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public engagementReviewEntityStaticMetaData()
			{
				SetEntityCoreInfo("engagementReviewEntity", InheritanceHierarchyType.None, false, (int)DATN.EntityType.engagementReviewEntity, typeof(engagementReviewEntity), typeof(engagementReviewEntityFactory), false);
				AddNavigatorMetaData<engagementReviewEntity, UserEntity>("User", "engagementReviews", (a, b) => a._user = b, a => a._user, (a, b) => a.User = b, DATN.RelationClasses.StaticengagementReviewRelations.UserEntityUsingUserIdStatic, ()=>new engagementReviewRelations().UserEntityUsingUserId, null, new int[] { (int)engagementReviewFieldIndex.UserId }, null, true, (int)DATN.EntityType.UserEntity);
				AddNavigatorMetaData<engagementReviewEntity, ProductVariantEntity>("ProductVariant", "engagementReviews", (a, b) => a._productVariant = b, a => a._productVariant, (a, b) => a.ProductVariant = b, DATN.RelationClasses.StaticengagementReviewRelations.ProductVariantEntityUsingVariantIdStatic, ()=>new engagementReviewRelations().ProductVariantEntityUsingVariantId, null, new int[] { (int)engagementReviewFieldIndex.VariantId }, null, true, (int)DATN.EntityType.ProductVariantEntity);
				AddNavigatorMetaData<engagementReviewEntity, salesOrderEntity>("salesOrder", "engagementReviews", (a, b) => a._salesOrder = b, a => a._salesOrder, (a, b) => a.salesOrder = b, DATN.RelationClasses.StaticengagementReviewRelations.salesOrderEntityUsingOrderIdStatic, ()=>new engagementReviewRelations().salesOrderEntityUsingOrderId, null, new int[] { (int)engagementReviewFieldIndex.OrderId }, null, true, (int)DATN.EntityType.salesOrderEntity);
			}
		}

		/// <summary>Static ctor</summary>
		static engagementReviewEntity()
		{
		}

		/// <summary> CTor</summary>
		public engagementReviewEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public engagementReviewEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this engagementReviewEntity</param>
		public engagementReviewEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for engagementReview which data should be fetched into this engagementReview object</param>
		public engagementReviewEntity(System.Guid id) : this(id, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for engagementReview which data should be fetched into this engagementReview object</param>
		/// <param name="validator">The custom validator object for this engagementReviewEntity</param>
		public engagementReviewEntity(System.Guid id, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.Id = id;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected engagementReviewEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'User' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoUser() { return CreateRelationInfoForNavigator("User"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'ProductVariant' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoProductVariant() { return CreateRelationInfoForNavigator("ProductVariant"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'salesOrder' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfosalesOrder() { return CreateRelationInfoForNavigator("salesOrder"); }
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END
			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this engagementReviewEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static engagementReviewRelations Relations { get { return _relationsFactory; } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'User' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathUser { get { return _staticMetaData.GetPrefetchPathElement("User", CommonEntityBase.CreateEntityCollection<UserEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'ProductVariant' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathProductVariant { get { return _staticMetaData.GetPrefetchPathElement("ProductVariant", CommonEntityBase.CreateEntityCollection<ProductVariantEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'salesOrder' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathsalesOrder { get { return _staticMetaData.GetPrefetchPathElement("salesOrder", CommonEntityBase.CreateEntityCollection<salesOrderEntity>()); } }

		/// <summary>The Comment property of the Entity engagementReview<br/><br/></summary>
		/// <remarks>Mapped on  table field: "reviews"."comment".<br/>Table field type characteristics (type, precision, scale, length): Text, 0, 0, 1073741824.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Comment
		{
			get { return (System.String)GetValue((int)engagementReviewFieldIndex.Comment, true); }
			set { SetValue((int)engagementReviewFieldIndex.Comment, value); }
		}

		/// <summary>The CreatedAt property of the Entity engagementReview<br/><br/></summary>
		/// <remarks>Mapped on  table field: "reviews"."created_at".<br/>Table field type characteristics (type, precision, scale, length): TimestampTz, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.DateTime> CreatedAt
		{
			get { return (Nullable<System.DateTime>)GetValue((int)engagementReviewFieldIndex.CreatedAt, false); }
			set { SetValue((int)engagementReviewFieldIndex.CreatedAt, value); }
		}

		/// <summary>The Id property of the Entity engagementReview<br/><br/></summary>
		/// <remarks>Mapped on  table field: "reviews"."id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, false</remarks>
		public virtual System.Guid Id
		{
			get { return (System.Guid)GetValue((int)engagementReviewFieldIndex.Id, true); }
			set { SetValue((int)engagementReviewFieldIndex.Id, value); }
		}

		/// <summary>The Images property of the Entity engagementReview<br/><br/></summary>
		/// <remarks>Mapped on  table field: "reviews"."images".<br/>Table field type characteristics (type, precision, scale, length): Jsonb, 0, 0, 2147483647.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Images
		{
			get { return (System.String)GetValue((int)engagementReviewFieldIndex.Images, true); }
			set { SetValue((int)engagementReviewFieldIndex.Images, value); }
		}

		/// <summary>The OrderId property of the Entity engagementReview<br/><br/></summary>
		/// <remarks>Mapped on  table field: "reviews"."order_id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Guid> OrderId
		{
			get { return (Nullable<System.Guid>)GetValue((int)engagementReviewFieldIndex.OrderId, false); }
			set { SetValue((int)engagementReviewFieldIndex.OrderId, value); }
		}

		/// <summary>The Rating property of the Entity engagementReview<br/><br/></summary>
		/// <remarks>Mapped on  table field: "reviews"."rating".<br/>Table field type characteristics (type, precision, scale, length): Integer, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> Rating
		{
			get { return (Nullable<System.Int32>)GetValue((int)engagementReviewFieldIndex.Rating, false); }
			set { SetValue((int)engagementReviewFieldIndex.Rating, value); }
		}

		/// <summary>The UserId property of the Entity engagementReview<br/><br/></summary>
		/// <remarks>Mapped on  table field: "reviews"."user_id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Guid> UserId
		{
			get { return (Nullable<System.Guid>)GetValue((int)engagementReviewFieldIndex.UserId, false); }
			set { SetValue((int)engagementReviewFieldIndex.UserId, value); }
		}

		/// <summary>The VariantId property of the Entity engagementReview<br/><br/></summary>
		/// <remarks>Mapped on  table field: "reviews"."variant_id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Guid> VariantId
		{
			get { return (Nullable<System.Guid>)GetValue((int)engagementReviewFieldIndex.VariantId, false); }
			set { SetValue((int)engagementReviewFieldIndex.VariantId, value); }
		}

		/// <summary>Gets / sets related entity of type 'UserEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual UserEntity User
		{
			get { return _user; }
			set { SetSingleRelatedEntityNavigator(value, "User"); }
		}

		/// <summary>Gets / sets related entity of type 'ProductVariantEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual ProductVariantEntity ProductVariant
		{
			get { return _productVariant; }
			set { SetSingleRelatedEntityNavigator(value, "ProductVariant"); }
		}

		/// <summary>Gets / sets related entity of type 'salesOrderEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual salesOrderEntity salesOrder
		{
			get { return _salesOrder; }
			set { SetSingleRelatedEntityNavigator(value, "salesOrder"); }
		}

		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END

	}
}

namespace DATN
{
	public enum engagementReviewFieldIndex
	{
		///<summary>Comment. </summary>
		Comment,
		///<summary>CreatedAt. </summary>
		CreatedAt,
		///<summary>Id. </summary>
		Id,
		///<summary>Images. </summary>
		Images,
		///<summary>OrderId. </summary>
		OrderId,
		///<summary>Rating. </summary>
		Rating,
		///<summary>UserId. </summary>
		UserId,
		///<summary>VariantId. </summary>
		VariantId,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace DATN.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: engagementReview. </summary>
	public partial class engagementReviewRelations: RelationFactory
	{

		/// <summary>Returns a new IEntityRelation object, between engagementReviewEntity and UserEntity over the m:1 relation they have, using the relation between the fields: engagementReview.UserId - User.Id</summary>
		public virtual IEntityRelation UserEntityUsingUserId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "User", false, new[] { UserFields.Id, engagementReviewFields.UserId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between engagementReviewEntity and ProductVariantEntity over the m:1 relation they have, using the relation between the fields: engagementReview.VariantId - ProductVariant.Id</summary>
		public virtual IEntityRelation ProductVariantEntityUsingVariantId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "ProductVariant", false, new[] { ProductVariantFields.Id, engagementReviewFields.VariantId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between engagementReviewEntity and salesOrderEntity over the m:1 relation they have, using the relation between the fields: engagementReview.OrderId - salesOrder.Id</summary>
		public virtual IEntityRelation salesOrderEntityUsingOrderId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "salesOrder", false, new[] { salesOrderFields.Id, engagementReviewFields.OrderId }); }
		}

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticengagementReviewRelations
	{
		internal static readonly IEntityRelation UserEntityUsingUserIdStatic = new engagementReviewRelations().UserEntityUsingUserId;
		internal static readonly IEntityRelation ProductVariantEntityUsingVariantIdStatic = new engagementReviewRelations().ProductVariantEntityUsingVariantId;
		internal static readonly IEntityRelation salesOrderEntityUsingOrderIdStatic = new engagementReviewRelations().salesOrderEntityUsingOrderId;

		/// <summary>CTor</summary>
		static StaticengagementReviewRelations() { }
	}
}
