//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.12.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using DATN.HelperClasses;
using DATN.FactoryClasses;
using DATN.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace DATN.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END
	/// <summary>Entity class which represents the entity 'GameTag'.<br/><br/></summary>
	[Serializable]
	public partial class GameTagEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END	
	{
		private GameEntity _game;
		private TagEntity _tag;

		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END
		private static GameTagEntityStaticMetaData _staticMetaData = new GameTagEntityStaticMetaData();
		private static GameTagRelations _relationsFactory = new GameTagRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name Game</summary>
			public static readonly string Game = "Game";
			/// <summary>Member name Tag</summary>
			public static readonly string Tag = "Tag";
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class GameTagEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public GameTagEntityStaticMetaData()
			{
				SetEntityCoreInfo("GameTagEntity", InheritanceHierarchyType.None, false, (int)DATN.EntityType.GameTagEntity, typeof(GameTagEntity), typeof(GameTagEntityFactory), false);
				AddNavigatorMetaData<GameTagEntity, GameEntity>("Game", "GameTags", (a, b) => a._game = b, a => a._game, (a, b) => a.Game = b, DATN.RelationClasses.StaticGameTagRelations.GameEntityUsingGameIdStatic, ()=>new GameTagRelations().GameEntityUsingGameId, null, new int[] { (int)GameTagFieldIndex.GameId }, null, true, (int)DATN.EntityType.GameEntity);
				AddNavigatorMetaData<GameTagEntity, TagEntity>("Tag", "GameTags", (a, b) => a._tag = b, a => a._tag, (a, b) => a.Tag = b, DATN.RelationClasses.StaticGameTagRelations.TagEntityUsingTagIdStatic, ()=>new GameTagRelations().TagEntityUsingTagId, null, new int[] { (int)GameTagFieldIndex.TagId }, null, true, (int)DATN.EntityType.TagEntity);
			}
		}

		/// <summary>Static ctor</summary>
		static GameTagEntity()
		{
		}

		/// <summary> CTor</summary>
		public GameTagEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public GameTagEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this GameTagEntity</param>
		public GameTagEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="gameId">PK value for GameTag which data should be fetched into this GameTag object</param>
		/// <param name="tagId">PK value for GameTag which data should be fetched into this GameTag object</param>
		public GameTagEntity(System.Guid gameId, System.Guid tagId) : this(gameId, tagId, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="gameId">PK value for GameTag which data should be fetched into this GameTag object</param>
		/// <param name="tagId">PK value for GameTag which data should be fetched into this GameTag object</param>
		/// <param name="validator">The custom validator object for this GameTagEntity</param>
		public GameTagEntity(System.Guid gameId, System.Guid tagId, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.GameId = gameId;
			this.TagId = tagId;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected GameTagEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'Game' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoGame() { return CreateRelationInfoForNavigator("Game"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'Tag' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoTag() { return CreateRelationInfoForNavigator("Tag"); }
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END
			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this GameTagEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static GameTagRelations Relations { get { return _relationsFactory; } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'Game' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathGame { get { return _staticMetaData.GetPrefetchPathElement("Game", CommonEntityBase.CreateEntityCollection<GameEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'Tag' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathTag { get { return _staticMetaData.GetPrefetchPathElement("Tag", CommonEntityBase.CreateEntityCollection<TagEntity>()); } }

		/// <summary>The GameId property of the Entity GameTag<br/><br/></summary>
		/// <remarks>Mapped on  table field: "game_tags"."game_id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, false</remarks>
		public virtual System.Guid GameId
		{
			get { return (System.Guid)GetValue((int)GameTagFieldIndex.GameId, true); }
			set { SetValue((int)GameTagFieldIndex.GameId, value); }
		}

		/// <summary>The TagId property of the Entity GameTag<br/><br/></summary>
		/// <remarks>Mapped on  table field: "game_tags"."tag_id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, false</remarks>
		public virtual System.Guid TagId
		{
			get { return (System.Guid)GetValue((int)GameTagFieldIndex.TagId, true); }
			set { SetValue((int)GameTagFieldIndex.TagId, value); }
		}

		/// <summary>Gets / sets related entity of type 'GameEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual GameEntity Game
		{
			get { return _game; }
			set { SetSingleRelatedEntityNavigator(value, "Game"); }
		}

		/// <summary>Gets / sets related entity of type 'TagEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual TagEntity Tag
		{
			get { return _tag; }
			set { SetSingleRelatedEntityNavigator(value, "Tag"); }
		}

		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END

	}
}

namespace DATN
{
	public enum GameTagFieldIndex
	{
		///<summary>GameId. </summary>
		GameId,
		///<summary>TagId. </summary>
		TagId,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace DATN.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: GameTag. </summary>
	public partial class GameTagRelations: RelationFactory
	{

		/// <summary>Returns a new IEntityRelation object, between GameTagEntity and GameEntity over the m:1 relation they have, using the relation between the fields: GameTag.GameId - Game.Id</summary>
		public virtual IEntityRelation GameEntityUsingGameId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "Game", false, new[] { GameFields.Id, GameTagFields.GameId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between GameTagEntity and TagEntity over the m:1 relation they have, using the relation between the fields: GameTag.TagId - Tag.Id</summary>
		public virtual IEntityRelation TagEntityUsingTagId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "Tag", false, new[] { TagFields.Id, GameTagFields.TagId }); }
		}

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticGameTagRelations
	{
		internal static readonly IEntityRelation GameEntityUsingGameIdStatic = new GameTagRelations().GameEntityUsingGameId;
		internal static readonly IEntityRelation TagEntityUsingTagIdStatic = new GameTagRelations().TagEntityUsingTagId;

		/// <summary>CTor</summary>
		static StaticGameTagRelations() { }
	}
}
