//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.12.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using DATN.HelperClasses;
using DATN.FactoryClasses;
using DATN.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace DATN.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END
	/// <summary>Entity class which represents the entity 'Notification'.<br/><br/></summary>
	[Serializable]
	public partial class NotificationEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END	
	{
		private UserEntity _user;

		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END
		private static NotificationEntityStaticMetaData _staticMetaData = new NotificationEntityStaticMetaData();
		private static NotificationRelations _relationsFactory = new NotificationRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name User</summary>
			public static readonly string User = "User";
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class NotificationEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public NotificationEntityStaticMetaData()
			{
				SetEntityCoreInfo("NotificationEntity", InheritanceHierarchyType.None, false, (int)DATN.EntityType.NotificationEntity, typeof(NotificationEntity), typeof(NotificationEntityFactory), false);
				AddNavigatorMetaData<NotificationEntity, UserEntity>("User", "Notifications", (a, b) => a._user = b, a => a._user, (a, b) => a.User = b, DATN.RelationClasses.StaticNotificationRelations.UserEntityUsingUserIdStatic, ()=>new NotificationRelations().UserEntityUsingUserId, null, new int[] { (int)NotificationFieldIndex.UserId }, null, true, (int)DATN.EntityType.UserEntity);
			}
		}

		/// <summary>Static ctor</summary>
		static NotificationEntity()
		{
		}

		/// <summary> CTor</summary>
		public NotificationEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public NotificationEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this NotificationEntity</param>
		public NotificationEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for Notification which data should be fetched into this Notification object</param>
		public NotificationEntity(System.Guid id) : this(id, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for Notification which data should be fetched into this Notification object</param>
		/// <param name="validator">The custom validator object for this NotificationEntity</param>
		public NotificationEntity(System.Guid id, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.Id = id;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected NotificationEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'User' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoUser() { return CreateRelationInfoForNavigator("User"); }
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END
			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this NotificationEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static NotificationRelations Relations { get { return _relationsFactory; } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'User' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathUser { get { return _staticMetaData.GetPrefetchPathElement("User", CommonEntityBase.CreateEntityCollection<UserEntity>()); } }

		/// <summary>The Body property of the Entity Notification<br/><br/></summary>
		/// <remarks>Mapped on  table field: "notifications"."body".<br/>Table field type characteristics (type, precision, scale, length): Text, 0, 0, 1073741824.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String Body
		{
			get { return (System.String)GetValue((int)NotificationFieldIndex.Body, true); }
			set { SetValue((int)NotificationFieldIndex.Body, value); }
		}

		/// <summary>The CreatedAt property of the Entity Notification<br/><br/></summary>
		/// <remarks>Mapped on  table field: "notifications"."created_at".<br/>Table field type characteristics (type, precision, scale, length): TimestampTz, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.DateTime> CreatedAt
		{
			get { return (Nullable<System.DateTime>)GetValue((int)NotificationFieldIndex.CreatedAt, false); }
			set { SetValue((int)NotificationFieldIndex.CreatedAt, value); }
		}

		/// <summary>The Id property of the Entity Notification<br/><br/></summary>
		/// <remarks>Mapped on  table field: "notifications"."id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, false</remarks>
		public virtual System.Guid Id
		{
			get { return (System.Guid)GetValue((int)NotificationFieldIndex.Id, true); }
			set { SetValue((int)NotificationFieldIndex.Id, value); }
		}

		/// <summary>The IsRead property of the Entity Notification<br/><br/></summary>
		/// <remarks>Mapped on  table field: "notifications"."is_read".<br/>Table field type characteristics (type, precision, scale, length): Boolean, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Boolean> IsRead
		{
			get { return (Nullable<System.Boolean>)GetValue((int)NotificationFieldIndex.IsRead, false); }
			set { SetValue((int)NotificationFieldIndex.IsRead, value); }
		}

		/// <summary>The Metadata property of the Entity Notification<br/><br/></summary>
		/// <remarks>Mapped on  table field: "notifications"."metadata".<br/>Table field type characteristics (type, precision, scale, length): Jsonb, 0, 0, 2147483647.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Metadata
		{
			get { return (System.String)GetValue((int)NotificationFieldIndex.Metadata, true); }
			set { SetValue((int)NotificationFieldIndex.Metadata, value); }
		}

		/// <summary>The Title property of the Entity Notification<br/><br/></summary>
		/// <remarks>Mapped on  table field: "notifications"."title".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 255.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String Title
		{
			get { return (System.String)GetValue((int)NotificationFieldIndex.Title, true); }
			set { SetValue((int)NotificationFieldIndex.Title, value); }
		}

		/// <summary>The Type property of the Entity Notification<br/><br/></summary>
		/// <remarks>Mapped on  table field: "notifications"."type".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 20.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Type
		{
			get { return (System.String)GetValue((int)NotificationFieldIndex.Type, true); }
			set { SetValue((int)NotificationFieldIndex.Type, value); }
		}

		/// <summary>The UserId property of the Entity Notification<br/><br/></summary>
		/// <remarks>Mapped on  table field: "notifications"."user_id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Guid> UserId
		{
			get { return (Nullable<System.Guid>)GetValue((int)NotificationFieldIndex.UserId, false); }
			set { SetValue((int)NotificationFieldIndex.UserId, value); }
		}

		/// <summary>Gets / sets related entity of type 'UserEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual UserEntity User
		{
			get { return _user; }
			set { SetSingleRelatedEntityNavigator(value, "User"); }
		}

		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END

	}
}

namespace DATN
{
	public enum NotificationFieldIndex
	{
		///<summary>Body. </summary>
		Body,
		///<summary>CreatedAt. </summary>
		CreatedAt,
		///<summary>Id. </summary>
		Id,
		///<summary>IsRead. </summary>
		IsRead,
		///<summary>Metadata. </summary>
		Metadata,
		///<summary>Title. </summary>
		Title,
		///<summary>Type. </summary>
		Type,
		///<summary>UserId. </summary>
		UserId,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace DATN.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: Notification. </summary>
	public partial class NotificationRelations: RelationFactory
	{

		/// <summary>Returns a new IEntityRelation object, between NotificationEntity and UserEntity over the m:1 relation they have, using the relation between the fields: Notification.UserId - User.Id</summary>
		public virtual IEntityRelation UserEntityUsingUserId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "User", false, new[] { UserFields.Id, NotificationFields.UserId }); }
		}

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticNotificationRelations
	{
		internal static readonly IEntityRelation UserEntityUsingUserIdStatic = new NotificationRelations().UserEntityUsingUserId;

		/// <summary>CTor</summary>
		static StaticNotificationRelations() { }
	}
}
