//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.12.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using DATN_2026.HelperClasses;
using DATN_2026.FactoryClasses;
using DATN_2026.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace DATN_2026.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END
	/// <summary>Entity class which represents the entity 'OrderItem'.<br/><br/></summary>
	[Serializable]
	public partial class OrderItemEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END	
	{
		private ProductVariantEntity _productVariant;
		private OrderEntity _order;

		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END
		private static OrderItemEntityStaticMetaData _staticMetaData = new OrderItemEntityStaticMetaData();
		private static OrderItemRelations _relationsFactory = new OrderItemRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name ProductVariant</summary>
			public static readonly string ProductVariant = "ProductVariant";
			/// <summary>Member name Order</summary>
			public static readonly string Order = "Order";
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class OrderItemEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public OrderItemEntityStaticMetaData()
			{
				SetEntityCoreInfo("OrderItemEntity", InheritanceHierarchyType.None, false, (int)DATN_2026.EntityType.OrderItemEntity, typeof(OrderItemEntity), typeof(OrderItemEntityFactory), false);
				AddNavigatorMetaData<OrderItemEntity, ProductVariantEntity>("ProductVariant", "OrderItems", (a, b) => a._productVariant = b, a => a._productVariant, (a, b) => a.ProductVariant = b, DATN_2026.RelationClasses.StaticOrderItemRelations.ProductVariantEntityUsingVariantIdStatic, ()=>new OrderItemRelations().ProductVariantEntityUsingVariantId, null, new int[] { (int)OrderItemFieldIndex.VariantId }, null, true, (int)DATN_2026.EntityType.ProductVariantEntity);
				AddNavigatorMetaData<OrderItemEntity, OrderEntity>("Order", "OrderItems", (a, b) => a._order = b, a => a._order, (a, b) => a.Order = b, DATN_2026.RelationClasses.StaticOrderItemRelations.OrderEntityUsingOrderIdStatic, ()=>new OrderItemRelations().OrderEntityUsingOrderId, null, new int[] { (int)OrderItemFieldIndex.OrderId }, null, true, (int)DATN_2026.EntityType.OrderEntity);
			}
		}

		/// <summary>Static ctor</summary>
		static OrderItemEntity()
		{
		}

		/// <summary> CTor</summary>
		public OrderItemEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public OrderItemEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this OrderItemEntity</param>
		public OrderItemEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for OrderItem which data should be fetched into this OrderItem object</param>
		public OrderItemEntity(System.Guid id) : this(id, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for OrderItem which data should be fetched into this OrderItem object</param>
		/// <param name="validator">The custom validator object for this OrderItemEntity</param>
		public OrderItemEntity(System.Guid id, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.Id = id;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected OrderItemEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'ProductVariant' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoProductVariant() { return CreateRelationInfoForNavigator("ProductVariant"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'Order' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoOrder() { return CreateRelationInfoForNavigator("Order"); }
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END
			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this OrderItemEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static OrderItemRelations Relations { get { return _relationsFactory; } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'ProductVariant' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathProductVariant { get { return _staticMetaData.GetPrefetchPathElement("ProductVariant", CommonEntityBase.CreateEntityCollection<ProductVariantEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'Order' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathOrder { get { return _staticMetaData.GetPrefetchPathElement("Order", CommonEntityBase.CreateEntityCollection<OrderEntity>()); } }

		/// <summary>The Id property of the Entity OrderItem<br/><br/></summary>
		/// <remarks>Mapped on  table field: "order_items"."id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, false</remarks>
		public virtual System.Guid Id
		{
			get { return (System.Guid)GetValue((int)OrderItemFieldIndex.Id, true); }
			set { SetValue((int)OrderItemFieldIndex.Id, value); }
		}

		/// <summary>The OrderId property of the Entity OrderItem<br/><br/></summary>
		/// <remarks>Mapped on  table field: "order_items"."order_id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Guid> OrderId
		{
			get { return (Nullable<System.Guid>)GetValue((int)OrderItemFieldIndex.OrderId, false); }
			set { SetValue((int)OrderItemFieldIndex.OrderId, value); }
		}

		/// <summary>The ProductNameSnapshot property of the Entity OrderItem<br/><br/></summary>
		/// <remarks>Mapped on  table field: "order_items"."product_name_snapshot".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 255.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String ProductNameSnapshot
		{
			get { return (System.String)GetValue((int)OrderItemFieldIndex.ProductNameSnapshot, true); }
			set { SetValue((int)OrderItemFieldIndex.ProductNameSnapshot, value); }
		}

		/// <summary>The Quantity property of the Entity OrderItem<br/><br/></summary>
		/// <remarks>Mapped on  table field: "order_items"."quantity".<br/>Table field type characteristics (type, precision, scale, length): Integer, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Int32 Quantity
		{
			get { return (System.Int32)GetValue((int)OrderItemFieldIndex.Quantity, true); }
			set { SetValue((int)OrderItemFieldIndex.Quantity, value); }
		}

		/// <summary>The UnitPrice property of the Entity OrderItem<br/><br/></summary>
		/// <remarks>Mapped on  table field: "order_items"."unit_price".<br/>Table field type characteristics (type, precision, scale, length): Numeric, 18, 2, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Decimal UnitPrice
		{
			get { return (System.Decimal)GetValue((int)OrderItemFieldIndex.UnitPrice, true); }
			set { SetValue((int)OrderItemFieldIndex.UnitPrice, value); }
		}

		/// <summary>The VariantId property of the Entity OrderItem<br/><br/></summary>
		/// <remarks>Mapped on  table field: "order_items"."variant_id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Guid> VariantId
		{
			get { return (Nullable<System.Guid>)GetValue((int)OrderItemFieldIndex.VariantId, false); }
			set { SetValue((int)OrderItemFieldIndex.VariantId, value); }
		}

		/// <summary>Gets / sets related entity of type 'ProductVariantEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual ProductVariantEntity ProductVariant
		{
			get { return _productVariant; }
			set { SetSingleRelatedEntityNavigator(value, "ProductVariant"); }
		}

		/// <summary>Gets / sets related entity of type 'OrderEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual OrderEntity Order
		{
			get { return _order; }
			set { SetSingleRelatedEntityNavigator(value, "Order"); }
		}

		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END

	}
}

namespace DATN_2026
{
	public enum OrderItemFieldIndex
	{
		///<summary>Id. </summary>
		Id,
		///<summary>OrderId. </summary>
		OrderId,
		///<summary>ProductNameSnapshot. </summary>
		ProductNameSnapshot,
		///<summary>Quantity. </summary>
		Quantity,
		///<summary>UnitPrice. </summary>
		UnitPrice,
		///<summary>VariantId. </summary>
		VariantId,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace DATN_2026.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: OrderItem. </summary>
	public partial class OrderItemRelations: RelationFactory
	{

		/// <summary>Returns a new IEntityRelation object, between OrderItemEntity and ProductVariantEntity over the m:1 relation they have, using the relation between the fields: OrderItem.VariantId - ProductVariant.Id</summary>
		public virtual IEntityRelation ProductVariantEntityUsingVariantId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "ProductVariant", false, new[] { ProductVariantFields.Id, OrderItemFields.VariantId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between OrderItemEntity and OrderEntity over the m:1 relation they have, using the relation between the fields: OrderItem.OrderId - Order.Id</summary>
		public virtual IEntityRelation OrderEntityUsingOrderId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "Order", false, new[] { OrderFields.Id, OrderItemFields.OrderId }); }
		}

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticOrderItemRelations
	{
		internal static readonly IEntityRelation ProductVariantEntityUsingVariantIdStatic = new OrderItemRelations().ProductVariantEntityUsingVariantId;
		internal static readonly IEntityRelation OrderEntityUsingOrderIdStatic = new OrderItemRelations().OrderEntityUsingOrderId;

		/// <summary>CTor</summary>
		static StaticOrderItemRelations() { }
	}
}
