//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.12.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using DATN.HelperClasses;
using DATN.FactoryClasses;
using DATN.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace DATN.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END
	/// <summary>Entity class which represents the entity 'OrderItem'.<br/><br/></summary>
	[Serializable]
	public partial class OrderItemEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END	
	{
		private GameEntity _game;
		private OrderEntity _order;

		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END
		private static OrderItemEntityStaticMetaData _staticMetaData = new OrderItemEntityStaticMetaData();
		private static OrderItemRelations _relationsFactory = new OrderItemRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name Game</summary>
			public static readonly string Game = "Game";
			/// <summary>Member name Order</summary>
			public static readonly string Order = "Order";
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class OrderItemEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public OrderItemEntityStaticMetaData()
			{
				SetEntityCoreInfo("OrderItemEntity", InheritanceHierarchyType.None, false, (int)DATN.EntityType.OrderItemEntity, typeof(OrderItemEntity), typeof(OrderItemEntityFactory), false);
				AddNavigatorMetaData<OrderItemEntity, GameEntity>("Game", "OrderItems", (a, b) => a._game = b, a => a._game, (a, b) => a.Game = b, DATN.RelationClasses.StaticOrderItemRelations.GameEntityUsingGameIdStatic, ()=>new OrderItemRelations().GameEntityUsingGameId, null, new int[] { (int)OrderItemFieldIndex.GameId }, null, true, (int)DATN.EntityType.GameEntity);
				AddNavigatorMetaData<OrderItemEntity, OrderEntity>("Order", "OrderItems", (a, b) => a._order = b, a => a._order, (a, b) => a.Order = b, DATN.RelationClasses.StaticOrderItemRelations.OrderEntityUsingOrderIdStatic, ()=>new OrderItemRelations().OrderEntityUsingOrderId, null, new int[] { (int)OrderItemFieldIndex.OrderId }, null, true, (int)DATN.EntityType.OrderEntity);
			}
		}

		/// <summary>Static ctor</summary>
		static OrderItemEntity()
		{
		}

		/// <summary> CTor</summary>
		public OrderItemEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public OrderItemEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this OrderItemEntity</param>
		public OrderItemEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="gameId">PK value for OrderItem which data should be fetched into this OrderItem object</param>
		/// <param name="orderId">PK value for OrderItem which data should be fetched into this OrderItem object</param>
		public OrderItemEntity(System.Guid gameId, System.Guid orderId) : this(gameId, orderId, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="gameId">PK value for OrderItem which data should be fetched into this OrderItem object</param>
		/// <param name="orderId">PK value for OrderItem which data should be fetched into this OrderItem object</param>
		/// <param name="validator">The custom validator object for this OrderItemEntity</param>
		public OrderItemEntity(System.Guid gameId, System.Guid orderId, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.GameId = gameId;
			this.OrderId = orderId;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected OrderItemEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'Game' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoGame() { return CreateRelationInfoForNavigator("Game"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'Order' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoOrder() { return CreateRelationInfoForNavigator("Order"); }
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END
			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this OrderItemEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static OrderItemRelations Relations { get { return _relationsFactory; } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'Game' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathGame { get { return _staticMetaData.GetPrefetchPathElement("Game", CommonEntityBase.CreateEntityCollection<GameEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'Order' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathOrder { get { return _staticMetaData.GetPrefetchPathElement("Order", CommonEntityBase.CreateEntityCollection<OrderEntity>()); } }

		/// <summary>The GameId property of the Entity OrderItem<br/><br/></summary>
		/// <remarks>Mapped on  table field: "order_items"."game_id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, false</remarks>
		public virtual System.Guid GameId
		{
			get { return (System.Guid)GetValue((int)OrderItemFieldIndex.GameId, true); }
			set { SetValue((int)OrderItemFieldIndex.GameId, value); }
		}

		/// <summary>The OrderId property of the Entity OrderItem<br/><br/></summary>
		/// <remarks>Mapped on  table field: "order_items"."order_id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, false</remarks>
		public virtual System.Guid OrderId
		{
			get { return (System.Guid)GetValue((int)OrderItemFieldIndex.OrderId, true); }
			set { SetValue((int)OrderItemFieldIndex.OrderId, value); }
		}

		/// <summary>The Price property of the Entity OrderItem<br/><br/></summary>
		/// <remarks>Mapped on  table field: "order_items"."price".<br/>Table field type characteristics (type, precision, scale, length): Numeric, 10, 2, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Decimal Price
		{
			get { return (System.Decimal)GetValue((int)OrderItemFieldIndex.Price, true); }
			set { SetValue((int)OrderItemFieldIndex.Price, value); }
		}

		/// <summary>Gets / sets related entity of type 'GameEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual GameEntity Game
		{
			get { return _game; }
			set { SetSingleRelatedEntityNavigator(value, "Game"); }
		}

		/// <summary>Gets / sets related entity of type 'OrderEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual OrderEntity Order
		{
			get { return _order; }
			set { SetSingleRelatedEntityNavigator(value, "Order"); }
		}

		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END

	}
}

namespace DATN
{
	public enum OrderItemFieldIndex
	{
		///<summary>GameId. </summary>
		GameId,
		///<summary>OrderId. </summary>
		OrderId,
		///<summary>Price. </summary>
		Price,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace DATN.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: OrderItem. </summary>
	public partial class OrderItemRelations: RelationFactory
	{

		/// <summary>Returns a new IEntityRelation object, between OrderItemEntity and GameEntity over the m:1 relation they have, using the relation between the fields: OrderItem.GameId - Game.Id</summary>
		public virtual IEntityRelation GameEntityUsingGameId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "Game", false, new[] { GameFields.Id, OrderItemFields.GameId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between OrderItemEntity and OrderEntity over the m:1 relation they have, using the relation between the fields: OrderItem.OrderId - Order.Id</summary>
		public virtual IEntityRelation OrderEntityUsingOrderId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "Order", false, new[] { OrderFields.Id, OrderItemFields.OrderId }); }
		}

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticOrderItemRelations
	{
		internal static readonly IEntityRelation GameEntityUsingGameIdStatic = new OrderItemRelations().GameEntityUsingGameId;
		internal static readonly IEntityRelation OrderEntityUsingOrderIdStatic = new OrderItemRelations().OrderEntityUsingOrderId;

		/// <summary>CTor</summary>
		static StaticOrderItemRelations() { }
	}
}
