//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.12.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using DATN_2026.HelperClasses;
using DATN_2026.FactoryClasses;
using DATN_2026.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace DATN_2026.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END

	/// <summary>Entity class which represents the entity 'PasswordResetToken'.<br/><br/></summary>
	[Serializable]
	public partial class PasswordResetTokenEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END
	
	{
		private UserEntity _user;
		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END

		private static PasswordResetTokenEntityStaticMetaData _staticMetaData = new PasswordResetTokenEntityStaticMetaData();
		private static PasswordResetTokenRelations _relationsFactory = new PasswordResetTokenRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name User</summary>
			public static readonly string User = "User";
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class PasswordResetTokenEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public PasswordResetTokenEntityStaticMetaData()
			{
				SetEntityCoreInfo("PasswordResetTokenEntity", InheritanceHierarchyType.None, false, (int)DATN_2026.EntityType.PasswordResetTokenEntity, typeof(PasswordResetTokenEntity), typeof(PasswordResetTokenEntityFactory), false);
				AddNavigatorMetaData<PasswordResetTokenEntity, UserEntity>("User", "PasswordResetTokens", (a, b) => a._user = b, a => a._user, (a, b) => a.User = b, DATN_2026.RelationClasses.StaticPasswordResetTokenRelations.UserEntityUsingUserIdStatic, ()=>new PasswordResetTokenRelations().UserEntityUsingUserId, null, new int[] { (int)PasswordResetTokenFieldIndex.UserId }, null, true, (int)DATN_2026.EntityType.UserEntity);
			}
		}

		/// <summary>Static ctor</summary>
		static PasswordResetTokenEntity()
		{
		}

		/// <summary> CTor</summary>
		public PasswordResetTokenEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public PasswordResetTokenEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this PasswordResetTokenEntity</param>
		public PasswordResetTokenEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for PasswordResetToken which data should be fetched into this PasswordResetToken object</param>
		public PasswordResetTokenEntity(System.Guid id) : this(id, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for PasswordResetToken which data should be fetched into this PasswordResetToken object</param>
		/// <param name="validator">The custom validator object for this PasswordResetTokenEntity</param>
		public PasswordResetTokenEntity(System.Guid id, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.Id = id;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected PasswordResetTokenEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		/// <summary>Method which will construct a filter (predicate expression) for the unique constraint defined on the fields: TokenHash .</summary>
		/// <returns>true if succeeded and the contents is read, false otherwise</returns>
		public IPredicateExpression ConstructFilterForUCTokenHash()
		{
			var filter = new PredicateExpression();
			filter.Add(DATN_2026.HelperClasses.PasswordResetTokenFields.TokenHash == this.Fields.GetCurrentValue((int)PasswordResetTokenFieldIndex.TokenHash));
 			return filter;
		}

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'User' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoUser() { return CreateRelationInfoForNavigator("User"); }
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this PasswordResetTokenEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END


			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static PasswordResetTokenRelations Relations { get { return _relationsFactory; } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'User' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathUser { get { return _staticMetaData.GetPrefetchPathElement("User", CommonEntityBase.CreateEntityCollection<UserEntity>()); } }

		/// <summary>The CreatedAt property of the Entity PasswordResetToken<br/><br/></summary>
		/// <remarks>Mapped on  table field: "password_reset_tokens"."created_at".<br/>Table field type characteristics (type, precision, scale, length): Timestamp, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.DateTime CreatedAt
		{
			get { return (System.DateTime)GetValue((int)PasswordResetTokenFieldIndex.CreatedAt, true); }
			set { SetValue((int)PasswordResetTokenFieldIndex.CreatedAt, value); }
		}

		/// <summary>The ExpiresAt property of the Entity PasswordResetToken<br/><br/></summary>
		/// <remarks>Mapped on  table field: "password_reset_tokens"."expires_at".<br/>Table field type characteristics (type, precision, scale, length): Timestamp, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.DateTime ExpiresAt
		{
			get { return (System.DateTime)GetValue((int)PasswordResetTokenFieldIndex.ExpiresAt, true); }
			set { SetValue((int)PasswordResetTokenFieldIndex.ExpiresAt, value); }
		}

		/// <summary>The Id property of the Entity PasswordResetToken<br/><br/></summary>
		/// <remarks>Mapped on  table field: "password_reset_tokens"."id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, false</remarks>
		public virtual System.Guid Id
		{
			get { return (System.Guid)GetValue((int)PasswordResetTokenFieldIndex.Id, true); }
			set { SetValue((int)PasswordResetTokenFieldIndex.Id, value); }
		}

		/// <summary>The IpAddress property of the Entity PasswordResetToken<br/><br/></summary>
		/// <remarks>Mapped on  table field: "password_reset_tokens"."ip_address".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 45.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String IpAddress
		{
			get { return (System.String)GetValue((int)PasswordResetTokenFieldIndex.IpAddress, true); }
			set { SetValue((int)PasswordResetTokenFieldIndex.IpAddress, value); }
		}

		/// <summary>The IsUsed property of the Entity PasswordResetToken<br/><br/></summary>
		/// <remarks>Mapped on  table field: "password_reset_tokens"."is_used".<br/>Table field type characteristics (type, precision, scale, length): Boolean, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Boolean IsUsed
		{
			get { return (System.Boolean)GetValue((int)PasswordResetTokenFieldIndex.IsUsed, true); }
			set { SetValue((int)PasswordResetTokenFieldIndex.IsUsed, value); }
		}

		/// <summary>The TokenHash property of the Entity PasswordResetToken<br/><br/></summary>
		/// <remarks>Mapped on  table field: "password_reset_tokens"."token_hash".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 255.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String TokenHash
		{
			get { return (System.String)GetValue((int)PasswordResetTokenFieldIndex.TokenHash, true); }
			set { SetValue((int)PasswordResetTokenFieldIndex.TokenHash, value); }
		}

		/// <summary>The UsedAt property of the Entity PasswordResetToken<br/><br/></summary>
		/// <remarks>Mapped on  table field: "password_reset_tokens"."used_at".<br/>Table field type characteristics (type, precision, scale, length): Timestamp, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.DateTime> UsedAt
		{
			get { return (Nullable<System.DateTime>)GetValue((int)PasswordResetTokenFieldIndex.UsedAt, false); }
			set { SetValue((int)PasswordResetTokenFieldIndex.UsedAt, value); }
		}

		/// <summary>The UserId property of the Entity PasswordResetToken<br/><br/></summary>
		/// <remarks>Mapped on  table field: "password_reset_tokens"."user_id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Guid UserId
		{
			get { return (System.Guid)GetValue((int)PasswordResetTokenFieldIndex.UserId, true); }
			set { SetValue((int)PasswordResetTokenFieldIndex.UserId, value); }
		}

		/// <summary>Gets / sets related entity of type 'UserEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual UserEntity User
		{
			get { return _user; }
			set { SetSingleRelatedEntityNavigator(value, "User"); }
		}
		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END


	}
}

namespace DATN_2026
{
	public enum PasswordResetTokenFieldIndex
	{
		///<summary>CreatedAt. </summary>
		CreatedAt,
		///<summary>ExpiresAt. </summary>
		ExpiresAt,
		///<summary>Id. </summary>
		Id,
		///<summary>IpAddress. </summary>
		IpAddress,
		///<summary>IsUsed. </summary>
		IsUsed,
		///<summary>TokenHash. </summary>
		TokenHash,
		///<summary>UsedAt. </summary>
		UsedAt,
		///<summary>UserId. </summary>
		UserId,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace DATN_2026.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: PasswordResetToken. </summary>
	public partial class PasswordResetTokenRelations: RelationFactory
	{

		/// <summary>Returns a new IEntityRelation object, between PasswordResetTokenEntity and UserEntity over the m:1 relation they have, using the relation between the fields: PasswordResetToken.UserId - User.Id</summary>
		public virtual IEntityRelation UserEntityUsingUserId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "User", false, new[] { UserFields.Id, PasswordResetTokenFields.UserId }); }
		}

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticPasswordResetTokenRelations
	{
		internal static readonly IEntityRelation UserEntityUsingUserIdStatic = new PasswordResetTokenRelations().UserEntityUsingUserId;

		/// <summary>CTor</summary>
		static StaticPasswordResetTokenRelations() { }
	}
}
