//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.12.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using DATN.HelperClasses;
using DATN.FactoryClasses;
using DATN.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace DATN.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END
	/// <summary>Entity class which represents the entity 'ProductImage'.<br/><br/></summary>
	[Serializable]
	public partial class ProductImageEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END	
	{
		private ProductEntity _product;

		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END
		private static ProductImageEntityStaticMetaData _staticMetaData = new ProductImageEntityStaticMetaData();
		private static ProductImageRelations _relationsFactory = new ProductImageRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name Product</summary>
			public static readonly string Product = "Product";
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class ProductImageEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public ProductImageEntityStaticMetaData()
			{
				SetEntityCoreInfo("ProductImageEntity", InheritanceHierarchyType.None, false, (int)DATN.EntityType.ProductImageEntity, typeof(ProductImageEntity), typeof(ProductImageEntityFactory), false);
				AddNavigatorMetaData<ProductImageEntity, ProductEntity>("Product", "ProductImages", (a, b) => a._product = b, a => a._product, (a, b) => a.Product = b, DATN.RelationClasses.StaticProductImageRelations.ProductEntityUsingProductIdStatic, ()=>new ProductImageRelations().ProductEntityUsingProductId, null, new int[] { (int)ProductImageFieldIndex.ProductId }, null, true, (int)DATN.EntityType.ProductEntity);
			}
		}

		/// <summary>Static ctor</summary>
		static ProductImageEntity()
		{
		}

		/// <summary> CTor</summary>
		public ProductImageEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public ProductImageEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this ProductImageEntity</param>
		public ProductImageEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for ProductImage which data should be fetched into this ProductImage object</param>
		public ProductImageEntity(System.Guid id) : this(id, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for ProductImage which data should be fetched into this ProductImage object</param>
		/// <param name="validator">The custom validator object for this ProductImageEntity</param>
		public ProductImageEntity(System.Guid id, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.Id = id;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected ProductImageEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'Product' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoProduct() { return CreateRelationInfoForNavigator("Product"); }
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END
			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this ProductImageEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static ProductImageRelations Relations { get { return _relationsFactory; } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'Product' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathProduct { get { return _staticMetaData.GetPrefetchPathElement("Product", CommonEntityBase.CreateEntityCollection<ProductEntity>()); } }

		/// <summary>The DisplayOrder property of the Entity ProductImage<br/><br/></summary>
		/// <remarks>Mapped on  table field: "product_images"."display_order".<br/>Table field type characteristics (type, precision, scale, length): Integer, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> DisplayOrder
		{
			get { return (Nullable<System.Int32>)GetValue((int)ProductImageFieldIndex.DisplayOrder, false); }
			set { SetValue((int)ProductImageFieldIndex.DisplayOrder, value); }
		}

		/// <summary>The Id property of the Entity ProductImage<br/><br/></summary>
		/// <remarks>Mapped on  table field: "product_images"."id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, false</remarks>
		public virtual System.Guid Id
		{
			get { return (System.Guid)GetValue((int)ProductImageFieldIndex.Id, true); }
			set { SetValue((int)ProductImageFieldIndex.Id, value); }
		}

		/// <summary>The IsPrimary property of the Entity ProductImage<br/><br/></summary>
		/// <remarks>Mapped on  table field: "product_images"."is_primary".<br/>Table field type characteristics (type, precision, scale, length): Boolean, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Boolean> IsPrimary
		{
			get { return (Nullable<System.Boolean>)GetValue((int)ProductImageFieldIndex.IsPrimary, false); }
			set { SetValue((int)ProductImageFieldIndex.IsPrimary, value); }
		}

		/// <summary>The ProductId property of the Entity ProductImage<br/><br/></summary>
		/// <remarks>Mapped on  table field: "product_images"."product_id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Guid> ProductId
		{
			get { return (Nullable<System.Guid>)GetValue((int)ProductImageFieldIndex.ProductId, false); }
			set { SetValue((int)ProductImageFieldIndex.ProductId, value); }
		}

		/// <summary>The Url property of the Entity ProductImage<br/><br/></summary>
		/// <remarks>Mapped on  table field: "product_images"."url".<br/>Table field type characteristics (type, precision, scale, length): Text, 0, 0, 1073741824.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String Url
		{
			get { return (System.String)GetValue((int)ProductImageFieldIndex.Url, true); }
			set { SetValue((int)ProductImageFieldIndex.Url, value); }
		}

		/// <summary>Gets / sets related entity of type 'ProductEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual ProductEntity Product
		{
			get { return _product; }
			set { SetSingleRelatedEntityNavigator(value, "Product"); }
		}

		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END

	}
}

namespace DATN
{
	public enum ProductImageFieldIndex
	{
		///<summary>DisplayOrder. </summary>
		DisplayOrder,
		///<summary>Id. </summary>
		Id,
		///<summary>IsPrimary. </summary>
		IsPrimary,
		///<summary>ProductId. </summary>
		ProductId,
		///<summary>Url. </summary>
		Url,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace DATN.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: ProductImage. </summary>
	public partial class ProductImageRelations: RelationFactory
	{

		/// <summary>Returns a new IEntityRelation object, between ProductImageEntity and ProductEntity over the m:1 relation they have, using the relation between the fields: ProductImage.ProductId - Product.Id</summary>
		public virtual IEntityRelation ProductEntityUsingProductId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "Product", false, new[] { ProductFields.Id, ProductImageFields.ProductId }); }
		}

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticProductImageRelations
	{
		internal static readonly IEntityRelation ProductEntityUsingProductIdStatic = new ProductImageRelations().ProductEntityUsingProductId;

		/// <summary>CTor</summary>
		static StaticProductImageRelations() { }
	}
}
