//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.12.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using DATN.HelperClasses;
using DATN.FactoryClasses;
using DATN.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace DATN.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END
	/// <summary>Entity class which represents the entity 'RolePermission'.<br/><br/></summary>
	[Serializable]
	public partial class RolePermissionEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END	
	{
		private PermissionEntity _permission;
		private RoleEntity _role;

		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END
		private static RolePermissionEntityStaticMetaData _staticMetaData = new RolePermissionEntityStaticMetaData();
		private static RolePermissionRelations _relationsFactory = new RolePermissionRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name Permission</summary>
			public static readonly string Permission = "Permission";
			/// <summary>Member name Role</summary>
			public static readonly string Role = "Role";
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class RolePermissionEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public RolePermissionEntityStaticMetaData()
			{
				SetEntityCoreInfo("RolePermissionEntity", InheritanceHierarchyType.None, false, (int)DATN.EntityType.RolePermissionEntity, typeof(RolePermissionEntity), typeof(RolePermissionEntityFactory), false);
				AddNavigatorMetaData<RolePermissionEntity, PermissionEntity>("Permission", "RolePermissions", (a, b) => a._permission = b, a => a._permission, (a, b) => a.Permission = b, DATN.RelationClasses.StaticRolePermissionRelations.PermissionEntityUsingPermissionIdStatic, ()=>new RolePermissionRelations().PermissionEntityUsingPermissionId, null, new int[] { (int)RolePermissionFieldIndex.PermissionId }, null, true, (int)DATN.EntityType.PermissionEntity);
				AddNavigatorMetaData<RolePermissionEntity, RoleEntity>("Role", "RolePermissions", (a, b) => a._role = b, a => a._role, (a, b) => a.Role = b, DATN.RelationClasses.StaticRolePermissionRelations.RoleEntityUsingRoleIdStatic, ()=>new RolePermissionRelations().RoleEntityUsingRoleId, null, new int[] { (int)RolePermissionFieldIndex.RoleId }, null, true, (int)DATN.EntityType.RoleEntity);
			}
		}

		/// <summary>Static ctor</summary>
		static RolePermissionEntity()
		{
		}

		/// <summary> CTor</summary>
		public RolePermissionEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public RolePermissionEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this RolePermissionEntity</param>
		public RolePermissionEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="permissionId">PK value for RolePermission which data should be fetched into this RolePermission object</param>
		/// <param name="roleId">PK value for RolePermission which data should be fetched into this RolePermission object</param>
		public RolePermissionEntity(System.Guid permissionId, System.Guid roleId) : this(permissionId, roleId, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="permissionId">PK value for RolePermission which data should be fetched into this RolePermission object</param>
		/// <param name="roleId">PK value for RolePermission which data should be fetched into this RolePermission object</param>
		/// <param name="validator">The custom validator object for this RolePermissionEntity</param>
		public RolePermissionEntity(System.Guid permissionId, System.Guid roleId, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.PermissionId = permissionId;
			this.RoleId = roleId;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected RolePermissionEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'Permission' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoPermission() { return CreateRelationInfoForNavigator("Permission"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'Role' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoRole() { return CreateRelationInfoForNavigator("Role"); }
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END
			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this RolePermissionEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static RolePermissionRelations Relations { get { return _relationsFactory; } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'Permission' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathPermission { get { return _staticMetaData.GetPrefetchPathElement("Permission", CommonEntityBase.CreateEntityCollection<PermissionEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'Role' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathRole { get { return _staticMetaData.GetPrefetchPathElement("Role", CommonEntityBase.CreateEntityCollection<RoleEntity>()); } }

		/// <summary>The PermissionId property of the Entity RolePermission<br/><br/></summary>
		/// <remarks>Mapped on  table field: "role_permissions"."permission_id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, false</remarks>
		public virtual System.Guid PermissionId
		{
			get { return (System.Guid)GetValue((int)RolePermissionFieldIndex.PermissionId, true); }
			set { SetValue((int)RolePermissionFieldIndex.PermissionId, value); }
		}

		/// <summary>The RoleId property of the Entity RolePermission<br/><br/></summary>
		/// <remarks>Mapped on  table field: "role_permissions"."role_id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, false</remarks>
		public virtual System.Guid RoleId
		{
			get { return (System.Guid)GetValue((int)RolePermissionFieldIndex.RoleId, true); }
			set { SetValue((int)RolePermissionFieldIndex.RoleId, value); }
		}

		/// <summary>Gets / sets related entity of type 'PermissionEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual PermissionEntity Permission
		{
			get { return _permission; }
			set { SetSingleRelatedEntityNavigator(value, "Permission"); }
		}

		/// <summary>Gets / sets related entity of type 'RoleEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual RoleEntity Role
		{
			get { return _role; }
			set { SetSingleRelatedEntityNavigator(value, "Role"); }
		}

		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END

	}
}

namespace DATN
{
	public enum RolePermissionFieldIndex
	{
		///<summary>PermissionId. </summary>
		PermissionId,
		///<summary>RoleId. </summary>
		RoleId,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace DATN.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: RolePermission. </summary>
	public partial class RolePermissionRelations: RelationFactory
	{

		/// <summary>Returns a new IEntityRelation object, between RolePermissionEntity and PermissionEntity over the m:1 relation they have, using the relation between the fields: RolePermission.PermissionId - Permission.Id</summary>
		public virtual IEntityRelation PermissionEntityUsingPermissionId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "Permission", false, new[] { PermissionFields.Id, RolePermissionFields.PermissionId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between RolePermissionEntity and RoleEntity over the m:1 relation they have, using the relation between the fields: RolePermission.RoleId - Role.Id</summary>
		public virtual IEntityRelation RoleEntityUsingRoleId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "Role", false, new[] { RoleFields.Id, RolePermissionFields.RoleId }); }
		}

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticRolePermissionRelations
	{
		internal static readonly IEntityRelation PermissionEntityUsingPermissionIdStatic = new RolePermissionRelations().PermissionEntityUsingPermissionId;
		internal static readonly IEntityRelation RoleEntityUsingRoleIdStatic = new RolePermissionRelations().RoleEntityUsingRoleId;

		/// <summary>CTor</summary>
		static StaticRolePermissionRelations() { }
	}
}
