//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.12.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using DATN_2026.HelperClasses;
using DATN_2026.FactoryClasses;
using DATN_2026.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace DATN_2026.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END
	/// <summary>Entity class which represents the entity 'Shop'.<br/><br/></summary>
	[Serializable]
	public partial class ShopEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END	
	{
		private EntityCollection<ProductEntity> _products;
		private EntityCollection<ChatBoxEntity> _chatBoxes;
		private EntityCollection<StockTransactionEntity> _stockTransactions;
		private EntityCollection<VoucherEntity> _vouchers;
		private EntityCollection<OrderEntity> _orders;
		private EntityCollection<WalletLedgerEntity> _walletLedgers;
		private EntityCollection<WithdrawRequestEntity> _withdrawRequests;
		private UserEntity _user;

		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END
		private static ShopEntityStaticMetaData _staticMetaData = new ShopEntityStaticMetaData();
		private static ShopRelations _relationsFactory = new ShopRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name User</summary>
			public static readonly string User = "User";
			/// <summary>Member name Products</summary>
			public static readonly string Products = "Products";
			/// <summary>Member name ChatBoxes</summary>
			public static readonly string ChatBoxes = "ChatBoxes";
			/// <summary>Member name StockTransactions</summary>
			public static readonly string StockTransactions = "StockTransactions";
			/// <summary>Member name Vouchers</summary>
			public static readonly string Vouchers = "Vouchers";
			/// <summary>Member name Orders</summary>
			public static readonly string Orders = "Orders";
			/// <summary>Member name WalletLedgers</summary>
			public static readonly string WalletLedgers = "WalletLedgers";
			/// <summary>Member name WithdrawRequests</summary>
			public static readonly string WithdrawRequests = "WithdrawRequests";
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class ShopEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public ShopEntityStaticMetaData()
			{
				SetEntityCoreInfo("ShopEntity", InheritanceHierarchyType.None, false, (int)DATN_2026.EntityType.ShopEntity, typeof(ShopEntity), typeof(ShopEntityFactory), false);
				AddNavigatorMetaData<ShopEntity, EntityCollection<ProductEntity>>("Products", a => a._products, (a, b) => a._products = b, a => a.Products, () => new ShopRelations().ProductEntityUsingShopId, typeof(ProductEntity), (int)DATN_2026.EntityType.ProductEntity);
				AddNavigatorMetaData<ShopEntity, EntityCollection<ChatBoxEntity>>("ChatBoxes", a => a._chatBoxes, (a, b) => a._chatBoxes = b, a => a.ChatBoxes, () => new ShopRelations().ChatBoxEntityUsingShopId, typeof(ChatBoxEntity), (int)DATN_2026.EntityType.ChatBoxEntity);
				AddNavigatorMetaData<ShopEntity, EntityCollection<StockTransactionEntity>>("StockTransactions", a => a._stockTransactions, (a, b) => a._stockTransactions = b, a => a.StockTransactions, () => new ShopRelations().StockTransactionEntityUsingShopId, typeof(StockTransactionEntity), (int)DATN_2026.EntityType.StockTransactionEntity);
				AddNavigatorMetaData<ShopEntity, EntityCollection<VoucherEntity>>("Vouchers", a => a._vouchers, (a, b) => a._vouchers = b, a => a.Vouchers, () => new ShopRelations().VoucherEntityUsingShopId, typeof(VoucherEntity), (int)DATN_2026.EntityType.VoucherEntity);
				AddNavigatorMetaData<ShopEntity, EntityCollection<OrderEntity>>("Orders", a => a._orders, (a, b) => a._orders = b, a => a.Orders, () => new ShopRelations().OrderEntityUsingShopId, typeof(OrderEntity), (int)DATN_2026.EntityType.OrderEntity);
				AddNavigatorMetaData<ShopEntity, EntityCollection<WalletLedgerEntity>>("WalletLedgers", a => a._walletLedgers, (a, b) => a._walletLedgers = b, a => a.WalletLedgers, () => new ShopRelations().WalletLedgerEntityUsingShopId, typeof(WalletLedgerEntity), (int)DATN_2026.EntityType.WalletLedgerEntity);
				AddNavigatorMetaData<ShopEntity, EntityCollection<WithdrawRequestEntity>>("WithdrawRequests", a => a._withdrawRequests, (a, b) => a._withdrawRequests = b, a => a.WithdrawRequests, () => new ShopRelations().WithdrawRequestEntityUsingShopId, typeof(WithdrawRequestEntity), (int)DATN_2026.EntityType.WithdrawRequestEntity);
				AddNavigatorMetaData<ShopEntity, UserEntity>("User", "Shops", (a, b) => a._user = b, a => a._user, (a, b) => a.User = b, DATN_2026.RelationClasses.StaticShopRelations.UserEntityUsingOwnerIdStatic, ()=>new ShopRelations().UserEntityUsingOwnerId, null, new int[] { (int)ShopFieldIndex.OwnerId }, null, true, (int)DATN_2026.EntityType.UserEntity);
			}
		}

		/// <summary>Static ctor</summary>
		static ShopEntity()
		{
		}

		/// <summary> CTor</summary>
		public ShopEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public ShopEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this ShopEntity</param>
		public ShopEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for Shop which data should be fetched into this Shop object</param>
		public ShopEntity(System.Guid id) : this(id, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for Shop which data should be fetched into this Shop object</param>
		/// <param name="validator">The custom validator object for this ShopEntity</param>
		public ShopEntity(System.Guid id, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.Id = id;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected ShopEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		/// <summary>Method which will construct a filter (predicate expression) for the unique constraint defined on the fields: Slug .</summary>
		/// <returns>true if succeeded and the contents is read, false otherwise</returns>
		public IPredicateExpression ConstructFilterForUCSlug()
		{
			var filter = new PredicateExpression();
			filter.Add(DATN_2026.HelperClasses.ShopFields.Slug == this.Fields.GetCurrentValue((int)ShopFieldIndex.Slug));
 			return filter;
		}

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'Product' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoProducts() { return CreateRelationInfoForNavigator("Products"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'ChatBox' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoChatBoxes() { return CreateRelationInfoForNavigator("ChatBoxes"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'StockTransaction' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoStockTransactions() { return CreateRelationInfoForNavigator("StockTransactions"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'Voucher' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoVouchers() { return CreateRelationInfoForNavigator("Vouchers"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'Order' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoOrders() { return CreateRelationInfoForNavigator("Orders"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'WalletLedger' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoWalletLedgers() { return CreateRelationInfoForNavigator("WalletLedgers"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'WithdrawRequest' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoWithdrawRequests() { return CreateRelationInfoForNavigator("WithdrawRequests"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'User' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoUser() { return CreateRelationInfoForNavigator("User"); }
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END
			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this ShopEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static ShopRelations Relations { get { return _relationsFactory; } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'Product' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathProducts { get { return _staticMetaData.GetPrefetchPathElement("Products", CommonEntityBase.CreateEntityCollection<ProductEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'ChatBox' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathChatBoxes { get { return _staticMetaData.GetPrefetchPathElement("ChatBoxes", CommonEntityBase.CreateEntityCollection<ChatBoxEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'StockTransaction' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathStockTransactions { get { return _staticMetaData.GetPrefetchPathElement("StockTransactions", CommonEntityBase.CreateEntityCollection<StockTransactionEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'Voucher' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathVouchers { get { return _staticMetaData.GetPrefetchPathElement("Vouchers", CommonEntityBase.CreateEntityCollection<VoucherEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'Order' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathOrders { get { return _staticMetaData.GetPrefetchPathElement("Orders", CommonEntityBase.CreateEntityCollection<OrderEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'WalletLedger' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathWalletLedgers { get { return _staticMetaData.GetPrefetchPathElement("WalletLedgers", CommonEntityBase.CreateEntityCollection<WalletLedgerEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'WithdrawRequest' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathWithdrawRequests { get { return _staticMetaData.GetPrefetchPathElement("WithdrawRequests", CommonEntityBase.CreateEntityCollection<WithdrawRequestEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'User' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathUser { get { return _staticMetaData.GetPrefetchPathElement("User", CommonEntityBase.CreateEntityCollection<UserEntity>()); } }

		/// <summary>The AvailableBalance property of the Entity Shop<br/><br/></summary>
		/// <remarks>Mapped on  table field: "shops"."available_balance".<br/>Table field type characteristics (type, precision, scale, length): Numeric, 18, 2, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Decimal> AvailableBalance
		{
			get { return (Nullable<System.Decimal>)GetValue((int)ShopFieldIndex.AvailableBalance, false); }
			set { SetValue((int)ShopFieldIndex.AvailableBalance, value); }
		}

		/// <summary>The CoverUrl property of the Entity Shop<br/><br/></summary>
		/// <remarks>Mapped on  table field: "shops"."cover_url".<br/>Table field type characteristics (type, precision, scale, length): Text, 0, 0, 1073741824.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String CoverUrl
		{
			get { return (System.String)GetValue((int)ShopFieldIndex.CoverUrl, true); }
			set { SetValue((int)ShopFieldIndex.CoverUrl, value); }
		}

		/// <summary>The CreatedAt property of the Entity Shop<br/><br/></summary>
		/// <remarks>Mapped on  table field: "shops"."created_at".<br/>Table field type characteristics (type, precision, scale, length): TimestampTz, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.DateTime> CreatedAt
		{
			get { return (Nullable<System.DateTime>)GetValue((int)ShopFieldIndex.CreatedAt, false); }
			set { SetValue((int)ShopFieldIndex.CreatedAt, value); }
		}

		/// <summary>The Description property of the Entity Shop<br/><br/></summary>
		/// <remarks>Mapped on  table field: "shops"."description".<br/>Table field type characteristics (type, precision, scale, length): Text, 0, 0, 1073741824.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Description
		{
			get { return (System.String)GetValue((int)ShopFieldIndex.Description, true); }
			set { SetValue((int)ShopFieldIndex.Description, value); }
		}

		/// <summary>The DistrictId property of the Entity Shop<br/><br/></summary>
		/// <remarks>Mapped on  table field: "shops"."district_id".<br/>Table field type characteristics (type, precision, scale, length): Integer, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> DistrictId
		{
			get { return (Nullable<System.Int32>)GetValue((int)ShopFieldIndex.DistrictId, false); }
			set { SetValue((int)ShopFieldIndex.DistrictId, value); }
		}

		/// <summary>The Id property of the Entity Shop<br/><br/></summary>
		/// <remarks>Mapped on  table field: "shops"."id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, false</remarks>
		public virtual System.Guid Id
		{
			get { return (System.Guid)GetValue((int)ShopFieldIndex.Id, true); }
			set { SetValue((int)ShopFieldIndex.Id, value); }
		}

		/// <summary>The IsActive property of the Entity Shop<br/><br/></summary>
		/// <remarks>Mapped on  table field: "shops"."is_active".<br/>Table field type characteristics (type, precision, scale, length): Boolean, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Boolean> IsActive
		{
			get { return (Nullable<System.Boolean>)GetValue((int)ShopFieldIndex.IsActive, false); }
			set { SetValue((int)ShopFieldIndex.IsActive, value); }
		}

		/// <summary>The LockedBalance property of the Entity Shop<br/><br/></summary>
		/// <remarks>Mapped on  table field: "shops"."locked_balance".<br/>Table field type characteristics (type, precision, scale, length): Numeric, 18, 2, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Decimal> LockedBalance
		{
			get { return (Nullable<System.Decimal>)GetValue((int)ShopFieldIndex.LockedBalance, false); }
			set { SetValue((int)ShopFieldIndex.LockedBalance, value); }
		}

		/// <summary>The LogoUrl property of the Entity Shop<br/><br/></summary>
		/// <remarks>Mapped on  table field: "shops"."logo_url".<br/>Table field type characteristics (type, precision, scale, length): Text, 0, 0, 1073741824.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String LogoUrl
		{
			get { return (System.String)GetValue((int)ShopFieldIndex.LogoUrl, true); }
			set { SetValue((int)ShopFieldIndex.LogoUrl, value); }
		}

		/// <summary>The Name property of the Entity Shop<br/><br/></summary>
		/// <remarks>Mapped on  table field: "shops"."name".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 255.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String Name
		{
			get { return (System.String)GetValue((int)ShopFieldIndex.Name, true); }
			set { SetValue((int)ShopFieldIndex.Name, value); }
		}

		/// <summary>The OwnerId property of the Entity Shop<br/><br/></summary>
		/// <remarks>Mapped on  table field: "shops"."owner_id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Guid> OwnerId
		{
			get { return (Nullable<System.Guid>)GetValue((int)ShopFieldIndex.OwnerId, false); }
			set { SetValue((int)ShopFieldIndex.OwnerId, value); }
		}

		/// <summary>The PickupAddress property of the Entity Shop<br/><br/></summary>
		/// <remarks>Mapped on  table field: "shops"."pickup_address".<br/>Table field type characteristics (type, precision, scale, length): Text, 0, 0, 1073741824.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String PickupAddress
		{
			get { return (System.String)GetValue((int)ShopFieldIndex.PickupAddress, true); }
			set { SetValue((int)ShopFieldIndex.PickupAddress, value); }
		}

		/// <summary>The ProvinceId property of the Entity Shop<br/><br/></summary>
		/// <remarks>Mapped on  table field: "shops"."province_id".<br/>Table field type characteristics (type, precision, scale, length): Integer, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> ProvinceId
		{
			get { return (Nullable<System.Int32>)GetValue((int)ShopFieldIndex.ProvinceId, false); }
			set { SetValue((int)ShopFieldIndex.ProvinceId, value); }
		}

		/// <summary>The Rating property of the Entity Shop<br/><br/></summary>
		/// <remarks>Mapped on  table field: "shops"."rating".<br/>Table field type characteristics (type, precision, scale, length): Numeric, 3, 2, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Decimal> Rating
		{
			get { return (Nullable<System.Decimal>)GetValue((int)ShopFieldIndex.Rating, false); }
			set { SetValue((int)ShopFieldIndex.Rating, value); }
		}

		/// <summary>The Slug property of the Entity Shop<br/><br/></summary>
		/// <remarks>Mapped on  table field: "shops"."slug".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 255.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String Slug
		{
			get { return (System.String)GetValue((int)ShopFieldIndex.Slug, true); }
			set { SetValue((int)ShopFieldIndex.Slug, value); }
		}

		/// <summary>The WardId property of the Entity Shop<br/><br/></summary>
		/// <remarks>Mapped on  table field: "shops"."ward_id".<br/>Table field type characteristics (type, precision, scale, length): Integer, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> WardId
		{
			get { return (Nullable<System.Int32>)GetValue((int)ShopFieldIndex.WardId, false); }
			set { SetValue((int)ShopFieldIndex.WardId, value); }
		}

		/// <summary>Gets the EntityCollection with the related entities of type 'ProductEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(ProductEntity))]
		public virtual EntityCollection<ProductEntity> Products { get { return GetOrCreateEntityCollection<ProductEntity, ProductEntityFactory>("Shop", true, false, ref _products); } }

		/// <summary>Gets the EntityCollection with the related entities of type 'ChatBoxEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(ChatBoxEntity))]
		public virtual EntityCollection<ChatBoxEntity> ChatBoxes { get { return GetOrCreateEntityCollection<ChatBoxEntity, ChatBoxEntityFactory>("Shop", true, false, ref _chatBoxes); } }

		/// <summary>Gets the EntityCollection with the related entities of type 'StockTransactionEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(StockTransactionEntity))]
		public virtual EntityCollection<StockTransactionEntity> StockTransactions { get { return GetOrCreateEntityCollection<StockTransactionEntity, StockTransactionEntityFactory>("Shop", true, false, ref _stockTransactions); } }

		/// <summary>Gets the EntityCollection with the related entities of type 'VoucherEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(VoucherEntity))]
		public virtual EntityCollection<VoucherEntity> Vouchers { get { return GetOrCreateEntityCollection<VoucherEntity, VoucherEntityFactory>("Shop", true, false, ref _vouchers); } }

		/// <summary>Gets the EntityCollection with the related entities of type 'OrderEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(OrderEntity))]
		public virtual EntityCollection<OrderEntity> Orders { get { return GetOrCreateEntityCollection<OrderEntity, OrderEntityFactory>("Shop", true, false, ref _orders); } }

		/// <summary>Gets the EntityCollection with the related entities of type 'WalletLedgerEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(WalletLedgerEntity))]
		public virtual EntityCollection<WalletLedgerEntity> WalletLedgers { get { return GetOrCreateEntityCollection<WalletLedgerEntity, WalletLedgerEntityFactory>("Shop", true, false, ref _walletLedgers); } }

		/// <summary>Gets the EntityCollection with the related entities of type 'WithdrawRequestEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(WithdrawRequestEntity))]
		public virtual EntityCollection<WithdrawRequestEntity> WithdrawRequests { get { return GetOrCreateEntityCollection<WithdrawRequestEntity, WithdrawRequestEntityFactory>("Shop", true, false, ref _withdrawRequests); } }

		/// <summary>Gets / sets related entity of type 'UserEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual UserEntity User
		{
			get { return _user; }
			set { SetSingleRelatedEntityNavigator(value, "User"); }
		}

		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END

	}
}

namespace DATN_2026
{
	public enum ShopFieldIndex
	{
		///<summary>AvailableBalance. </summary>
		AvailableBalance,
		///<summary>CoverUrl. </summary>
		CoverUrl,
		///<summary>CreatedAt. </summary>
		CreatedAt,
		///<summary>Description. </summary>
		Description,
		///<summary>DistrictId. </summary>
		DistrictId,
		///<summary>Id. </summary>
		Id,
		///<summary>IsActive. </summary>
		IsActive,
		///<summary>LockedBalance. </summary>
		LockedBalance,
		///<summary>LogoUrl. </summary>
		LogoUrl,
		///<summary>Name. </summary>
		Name,
		///<summary>OwnerId. </summary>
		OwnerId,
		///<summary>PickupAddress. </summary>
		PickupAddress,
		///<summary>ProvinceId. </summary>
		ProvinceId,
		///<summary>Rating. </summary>
		Rating,
		///<summary>Slug. </summary>
		Slug,
		///<summary>WardId. </summary>
		WardId,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace DATN_2026.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: Shop. </summary>
	public partial class ShopRelations: RelationFactory
	{
		/// <summary>Returns a new IEntityRelation object, between ShopEntity and ProductEntity over the 1:n relation they have, using the relation between the fields: Shop.Id - Product.ShopId</summary>
		public virtual IEntityRelation ProductEntityUsingShopId
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "Products", true, new[] { ShopFields.Id, ProductFields.ShopId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between ShopEntity and ChatBoxEntity over the 1:n relation they have, using the relation between the fields: Shop.Id - ChatBox.ShopId</summary>
		public virtual IEntityRelation ChatBoxEntityUsingShopId
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "ChatBoxes", true, new[] { ShopFields.Id, ChatBoxFields.ShopId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between ShopEntity and StockTransactionEntity over the 1:n relation they have, using the relation between the fields: Shop.Id - StockTransaction.ShopId</summary>
		public virtual IEntityRelation StockTransactionEntityUsingShopId
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "StockTransactions", true, new[] { ShopFields.Id, StockTransactionFields.ShopId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between ShopEntity and VoucherEntity over the 1:n relation they have, using the relation between the fields: Shop.Id - Voucher.ShopId</summary>
		public virtual IEntityRelation VoucherEntityUsingShopId
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "Vouchers", true, new[] { ShopFields.Id, VoucherFields.ShopId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between ShopEntity and OrderEntity over the 1:n relation they have, using the relation between the fields: Shop.Id - Order.ShopId</summary>
		public virtual IEntityRelation OrderEntityUsingShopId
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "Orders", true, new[] { ShopFields.Id, OrderFields.ShopId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between ShopEntity and WalletLedgerEntity over the 1:n relation they have, using the relation between the fields: Shop.Id - WalletLedger.ShopId</summary>
		public virtual IEntityRelation WalletLedgerEntityUsingShopId
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "WalletLedgers", true, new[] { ShopFields.Id, WalletLedgerFields.ShopId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between ShopEntity and WithdrawRequestEntity over the 1:n relation they have, using the relation between the fields: Shop.Id - WithdrawRequest.ShopId</summary>
		public virtual IEntityRelation WithdrawRequestEntityUsingShopId
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "WithdrawRequests", true, new[] { ShopFields.Id, WithdrawRequestFields.ShopId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between ShopEntity and UserEntity over the m:1 relation they have, using the relation between the fields: Shop.OwnerId - User.Id</summary>
		public virtual IEntityRelation UserEntityUsingOwnerId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "User", false, new[] { UserFields.Id, ShopFields.OwnerId }); }
		}

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticShopRelations
	{
		internal static readonly IEntityRelation ProductEntityUsingShopIdStatic = new ShopRelations().ProductEntityUsingShopId;
		internal static readonly IEntityRelation ChatBoxEntityUsingShopIdStatic = new ShopRelations().ChatBoxEntityUsingShopId;
		internal static readonly IEntityRelation StockTransactionEntityUsingShopIdStatic = new ShopRelations().StockTransactionEntityUsingShopId;
		internal static readonly IEntityRelation VoucherEntityUsingShopIdStatic = new ShopRelations().VoucherEntityUsingShopId;
		internal static readonly IEntityRelation OrderEntityUsingShopIdStatic = new ShopRelations().OrderEntityUsingShopId;
		internal static readonly IEntityRelation WalletLedgerEntityUsingShopIdStatic = new ShopRelations().WalletLedgerEntityUsingShopId;
		internal static readonly IEntityRelation WithdrawRequestEntityUsingShopIdStatic = new ShopRelations().WithdrawRequestEntityUsingShopId;
		internal static readonly IEntityRelation UserEntityUsingOwnerIdStatic = new ShopRelations().UserEntityUsingOwnerId;

		/// <summary>CTor</summary>
		static StaticShopRelations() { }
	}
}
