//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.12.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using DATN_2026.HelperClasses;
using DATN_2026.FactoryClasses;
using DATN_2026.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace DATN_2026.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END
	/// <summary>Entity class which represents the entity 'Transaction'.<br/><br/></summary>
	[Serializable]
	public partial class TransactionEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END	
	{
		private EntityCollection<WalletLedgerEntity> _walletLedgers;
		private OrderEntity _order;

		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END
		private static TransactionEntityStaticMetaData _staticMetaData = new TransactionEntityStaticMetaData();
		private static TransactionRelations _relationsFactory = new TransactionRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name Order</summary>
			public static readonly string Order = "Order";
			/// <summary>Member name WalletLedgers</summary>
			public static readonly string WalletLedgers = "WalletLedgers";
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class TransactionEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public TransactionEntityStaticMetaData()
			{
				SetEntityCoreInfo("TransactionEntity", InheritanceHierarchyType.None, false, (int)DATN_2026.EntityType.TransactionEntity, typeof(TransactionEntity), typeof(TransactionEntityFactory), false);
				AddNavigatorMetaData<TransactionEntity, EntityCollection<WalletLedgerEntity>>("WalletLedgers", a => a._walletLedgers, (a, b) => a._walletLedgers = b, a => a.WalletLedgers, () => new TransactionRelations().WalletLedgerEntityUsingTransactionId, typeof(WalletLedgerEntity), (int)DATN_2026.EntityType.WalletLedgerEntity);
				AddNavigatorMetaData<TransactionEntity, OrderEntity>("Order", "Transactions", (a, b) => a._order = b, a => a._order, (a, b) => a.Order = b, DATN_2026.RelationClasses.StaticTransactionRelations.OrderEntityUsingOrderIdStatic, ()=>new TransactionRelations().OrderEntityUsingOrderId, null, new int[] { (int)TransactionFieldIndex.OrderId }, null, true, (int)DATN_2026.EntityType.OrderEntity);
			}
		}

		/// <summary>Static ctor</summary>
		static TransactionEntity()
		{
		}

		/// <summary> CTor</summary>
		public TransactionEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public TransactionEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this TransactionEntity</param>
		public TransactionEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for Transaction which data should be fetched into this Transaction object</param>
		public TransactionEntity(System.Guid id) : this(id, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for Transaction which data should be fetched into this Transaction object</param>
		/// <param name="validator">The custom validator object for this TransactionEntity</param>
		public TransactionEntity(System.Guid id, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.Id = id;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected TransactionEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'WalletLedger' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoWalletLedgers() { return CreateRelationInfoForNavigator("WalletLedgers"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'Order' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoOrder() { return CreateRelationInfoForNavigator("Order"); }
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END
			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this TransactionEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static TransactionRelations Relations { get { return _relationsFactory; } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'WalletLedger' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathWalletLedgers { get { return _staticMetaData.GetPrefetchPathElement("WalletLedgers", CommonEntityBase.CreateEntityCollection<WalletLedgerEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'Order' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathOrder { get { return _staticMetaData.GetPrefetchPathElement("Order", CommonEntityBase.CreateEntityCollection<OrderEntity>()); } }

		/// <summary>The Amount property of the Entity Transaction<br/><br/></summary>
		/// <remarks>Mapped on  table field: "transactions"."amount".<br/>Table field type characteristics (type, precision, scale, length): Numeric, 18, 2, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Decimal Amount
		{
			get { return (System.Decimal)GetValue((int)TransactionFieldIndex.Amount, true); }
			set { SetValue((int)TransactionFieldIndex.Amount, value); }
		}

		/// <summary>The CreatedAt property of the Entity Transaction<br/><br/></summary>
		/// <remarks>Mapped on  table field: "transactions"."created_at".<br/>Table field type characteristics (type, precision, scale, length): TimestampTz, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.DateTime> CreatedAt
		{
			get { return (Nullable<System.DateTime>)GetValue((int)TransactionFieldIndex.CreatedAt, false); }
			set { SetValue((int)TransactionFieldIndex.CreatedAt, value); }
		}

		/// <summary>The ExternalTransactionNo property of the Entity Transaction<br/><br/></summary>
		/// <remarks>Mapped on  table field: "transactions"."external_transaction_no".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 100.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String ExternalTransactionNo
		{
			get { return (System.String)GetValue((int)TransactionFieldIndex.ExternalTransactionNo, true); }
			set { SetValue((int)TransactionFieldIndex.ExternalTransactionNo, value); }
		}

		/// <summary>The Id property of the Entity Transaction<br/><br/></summary>
		/// <remarks>Mapped on  table field: "transactions"."id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, false</remarks>
		public virtual System.Guid Id
		{
			get { return (System.Guid)GetValue((int)TransactionFieldIndex.Id, true); }
			set { SetValue((int)TransactionFieldIndex.Id, value); }
		}

		/// <summary>The OrderId property of the Entity Transaction<br/><br/></summary>
		/// <remarks>Mapped on  table field: "transactions"."order_id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Guid> OrderId
		{
			get { return (Nullable<System.Guid>)GetValue((int)TransactionFieldIndex.OrderId, false); }
			set { SetValue((int)TransactionFieldIndex.OrderId, value); }
		}

		/// <summary>The Provider property of the Entity Transaction<br/><br/></summary>
		/// <remarks>Mapped on  table field: "transactions"."provider".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 20.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Provider
		{
			get { return (System.String)GetValue((int)TransactionFieldIndex.Provider, true); }
			set { SetValue((int)TransactionFieldIndex.Provider, value); }
		}

		/// <summary>The RawResponse property of the Entity Transaction<br/><br/></summary>
		/// <remarks>Mapped on  table field: "transactions"."raw_response".<br/>Table field type characteristics (type, precision, scale, length): Jsonb, 0, 0, 2147483647.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String RawResponse
		{
			get { return (System.String)GetValue((int)TransactionFieldIndex.RawResponse, true); }
			set { SetValue((int)TransactionFieldIndex.RawResponse, value); }
		}

		/// <summary>The ReferenceId property of the Entity Transaction<br/><br/></summary>
		/// <remarks>Mapped on  table field: "transactions"."reference_id".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 100.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String ReferenceId
		{
			get { return (System.String)GetValue((int)TransactionFieldIndex.ReferenceId, true); }
			set { SetValue((int)TransactionFieldIndex.ReferenceId, value); }
		}

		/// <summary>The Status property of the Entity Transaction<br/><br/></summary>
		/// <remarks>Mapped on  table field: "transactions"."status".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 20.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Status
		{
			get { return (System.String)GetValue((int)TransactionFieldIndex.Status, true); }
			set { SetValue((int)TransactionFieldIndex.Status, value); }
		}

		/// <summary>The TransactionType property of the Entity Transaction<br/><br/></summary>
		/// <remarks>Mapped on  table field: "transactions"."transaction_type".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 50.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String TransactionType
		{
			get { return (System.String)GetValue((int)TransactionFieldIndex.TransactionType, true); }
			set { SetValue((int)TransactionFieldIndex.TransactionType, value); }
		}

		/// <summary>Gets the EntityCollection with the related entities of type 'WalletLedgerEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(WalletLedgerEntity))]
		public virtual EntityCollection<WalletLedgerEntity> WalletLedgers { get { return GetOrCreateEntityCollection<WalletLedgerEntity, WalletLedgerEntityFactory>("Transaction", true, false, ref _walletLedgers); } }

		/// <summary>Gets / sets related entity of type 'OrderEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual OrderEntity Order
		{
			get { return _order; }
			set { SetSingleRelatedEntityNavigator(value, "Order"); }
		}

		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END

	}
}

namespace DATN_2026
{
	public enum TransactionFieldIndex
	{
		///<summary>Amount. </summary>
		Amount,
		///<summary>CreatedAt. </summary>
		CreatedAt,
		///<summary>ExternalTransactionNo. </summary>
		ExternalTransactionNo,
		///<summary>Id. </summary>
		Id,
		///<summary>OrderId. </summary>
		OrderId,
		///<summary>Provider. </summary>
		Provider,
		///<summary>RawResponse. </summary>
		RawResponse,
		///<summary>ReferenceId. </summary>
		ReferenceId,
		///<summary>Status. </summary>
		Status,
		///<summary>TransactionType. </summary>
		TransactionType,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace DATN_2026.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: Transaction. </summary>
	public partial class TransactionRelations: RelationFactory
	{
		/// <summary>Returns a new IEntityRelation object, between TransactionEntity and WalletLedgerEntity over the 1:n relation they have, using the relation between the fields: Transaction.Id - WalletLedger.TransactionId</summary>
		public virtual IEntityRelation WalletLedgerEntityUsingTransactionId
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "WalletLedgers", true, new[] { TransactionFields.Id, WalletLedgerFields.TransactionId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between TransactionEntity and OrderEntity over the m:1 relation they have, using the relation between the fields: Transaction.OrderId - Order.Id</summary>
		public virtual IEntityRelation OrderEntityUsingOrderId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "Order", false, new[] { OrderFields.Id, TransactionFields.OrderId }); }
		}

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticTransactionRelations
	{
		internal static readonly IEntityRelation WalletLedgerEntityUsingTransactionIdStatic = new TransactionRelations().WalletLedgerEntityUsingTransactionId;
		internal static readonly IEntityRelation OrderEntityUsingOrderIdStatic = new TransactionRelations().OrderEntityUsingOrderId;

		/// <summary>CTor</summary>
		static StaticTransactionRelations() { }
	}
}
