//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.12.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using DATN_2026.HelperClasses;
using DATN_2026.FactoryClasses;
using DATN_2026.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace DATN_2026.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END

	/// <summary>Entity class which represents the entity 'UserAddress'.<br/><br/></summary>
	[Serializable]
	public partial class UserAddressEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END
	
	{
		private UserEntity _user;
		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END

		private static UserAddressEntityStaticMetaData _staticMetaData = new UserAddressEntityStaticMetaData();
		private static UserAddressRelations _relationsFactory = new UserAddressRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name User</summary>
			public static readonly string User = "User";
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class UserAddressEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public UserAddressEntityStaticMetaData()
			{
				SetEntityCoreInfo("UserAddressEntity", InheritanceHierarchyType.None, false, (int)DATN_2026.EntityType.UserAddressEntity, typeof(UserAddressEntity), typeof(UserAddressEntityFactory), false);
				AddNavigatorMetaData<UserAddressEntity, UserEntity>("User", "UserAddresses", (a, b) => a._user = b, a => a._user, (a, b) => a.User = b, DATN_2026.RelationClasses.StaticUserAddressRelations.UserEntityUsingUserIdStatic, ()=>new UserAddressRelations().UserEntityUsingUserId, null, new int[] { (int)UserAddressFieldIndex.UserId }, null, true, (int)DATN_2026.EntityType.UserEntity);
			}
		}

		/// <summary>Static ctor</summary>
		static UserAddressEntity()
		{
		}

		/// <summary> CTor</summary>
		public UserAddressEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public UserAddressEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this UserAddressEntity</param>
		public UserAddressEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for UserAddress which data should be fetched into this UserAddress object</param>
		public UserAddressEntity(System.Guid id) : this(id, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for UserAddress which data should be fetched into this UserAddress object</param>
		/// <param name="validator">The custom validator object for this UserAddressEntity</param>
		public UserAddressEntity(System.Guid id, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.Id = id;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected UserAddressEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'User' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoUser() { return CreateRelationInfoForNavigator("User"); }
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this UserAddressEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END


			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static UserAddressRelations Relations { get { return _relationsFactory; } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'User' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathUser { get { return _staticMetaData.GetPrefetchPathElement("User", CommonEntityBase.CreateEntityCollection<UserEntity>()); } }

		/// <summary>The CreatedAt property of the Entity UserAddress<br/><br/></summary>
		/// <remarks>Mapped on  table field: "user_addresses"."created_at".<br/>Table field type characteristics (type, precision, scale, length): TimestampTz, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.DateTime> CreatedAt
		{
			get { return (Nullable<System.DateTime>)GetValue((int)UserAddressFieldIndex.CreatedAt, false); }
			set { SetValue((int)UserAddressFieldIndex.CreatedAt, value); }
		}

		/// <summary>The DetailedAddress property of the Entity UserAddress<br/><br/></summary>
		/// <remarks>Mapped on  table field: "user_addresses"."detailed_address".<br/>Table field type characteristics (type, precision, scale, length): Text, 0, 0, 1073741824.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String DetailedAddress
		{
			get { return (System.String)GetValue((int)UserAddressFieldIndex.DetailedAddress, true); }
			set { SetValue((int)UserAddressFieldIndex.DetailedAddress, value); }
		}

		/// <summary>The DistrictId property of the Entity UserAddress<br/><br/></summary>
		/// <remarks>Mapped on  table field: "user_addresses"."district_id".<br/>Table field type characteristics (type, precision, scale, length): Integer, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> DistrictId
		{
			get { return (Nullable<System.Int32>)GetValue((int)UserAddressFieldIndex.DistrictId, false); }
			set { SetValue((int)UserAddressFieldIndex.DistrictId, value); }
		}

		/// <summary>The FullName property of the Entity UserAddress<br/><br/></summary>
		/// <remarks>Mapped on  table field: "user_addresses"."full_name".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 255.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String FullName
		{
			get { return (System.String)GetValue((int)UserAddressFieldIndex.FullName, true); }
			set { SetValue((int)UserAddressFieldIndex.FullName, value); }
		}

		/// <summary>The Id property of the Entity UserAddress<br/><br/></summary>
		/// <remarks>Mapped on  table field: "user_addresses"."id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, false</remarks>
		public virtual System.Guid Id
		{
			get { return (System.Guid)GetValue((int)UserAddressFieldIndex.Id, true); }
			set { SetValue((int)UserAddressFieldIndex.Id, value); }
		}

		/// <summary>The IsDefault property of the Entity UserAddress<br/><br/></summary>
		/// <remarks>Mapped on  table field: "user_addresses"."is_default".<br/>Table field type characteristics (type, precision, scale, length): Boolean, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Boolean> IsDefault
		{
			get { return (Nullable<System.Boolean>)GetValue((int)UserAddressFieldIndex.IsDefault, false); }
			set { SetValue((int)UserAddressFieldIndex.IsDefault, value); }
		}

		/// <summary>The PhoneNumber property of the Entity UserAddress<br/><br/></summary>
		/// <remarks>Mapped on  table field: "user_addresses"."phone_number".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 20.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String PhoneNumber
		{
			get { return (System.String)GetValue((int)UserAddressFieldIndex.PhoneNumber, true); }
			set { SetValue((int)UserAddressFieldIndex.PhoneNumber, value); }
		}

		/// <summary>The ProvinceId property of the Entity UserAddress<br/><br/></summary>
		/// <remarks>Mapped on  table field: "user_addresses"."province_id".<br/>Table field type characteristics (type, precision, scale, length): Integer, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> ProvinceId
		{
			get { return (Nullable<System.Int32>)GetValue((int)UserAddressFieldIndex.ProvinceId, false); }
			set { SetValue((int)UserAddressFieldIndex.ProvinceId, value); }
		}

		/// <summary>The UserId property of the Entity UserAddress<br/><br/></summary>
		/// <remarks>Mapped on  table field: "user_addresses"."user_id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Guid> UserId
		{
			get { return (Nullable<System.Guid>)GetValue((int)UserAddressFieldIndex.UserId, false); }
			set { SetValue((int)UserAddressFieldIndex.UserId, value); }
		}

		/// <summary>The WardId property of the Entity UserAddress<br/><br/></summary>
		/// <remarks>Mapped on  table field: "user_addresses"."ward_id".<br/>Table field type characteristics (type, precision, scale, length): Integer, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> WardId
		{
			get { return (Nullable<System.Int32>)GetValue((int)UserAddressFieldIndex.WardId, false); }
			set { SetValue((int)UserAddressFieldIndex.WardId, value); }
		}

		/// <summary>Gets / sets related entity of type 'UserEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual UserEntity User
		{
			get { return _user; }
			set { SetSingleRelatedEntityNavigator(value, "User"); }
		}
		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END


	}
}

namespace DATN_2026
{
	public enum UserAddressFieldIndex
	{
		///<summary>CreatedAt. </summary>
		CreatedAt,
		///<summary>DetailedAddress. </summary>
		DetailedAddress,
		///<summary>DistrictId. </summary>
		DistrictId,
		///<summary>FullName. </summary>
		FullName,
		///<summary>Id. </summary>
		Id,
		///<summary>IsDefault. </summary>
		IsDefault,
		///<summary>PhoneNumber. </summary>
		PhoneNumber,
		///<summary>ProvinceId. </summary>
		ProvinceId,
		///<summary>UserId. </summary>
		UserId,
		///<summary>WardId. </summary>
		WardId,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace DATN_2026.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: UserAddress. </summary>
	public partial class UserAddressRelations: RelationFactory
	{

		/// <summary>Returns a new IEntityRelation object, between UserAddressEntity and UserEntity over the m:1 relation they have, using the relation between the fields: UserAddress.UserId - User.Id</summary>
		public virtual IEntityRelation UserEntityUsingUserId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "User", false, new[] { UserFields.Id, UserAddressFields.UserId }); }
		}

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticUserAddressRelations
	{
		internal static readonly IEntityRelation UserEntityUsingUserIdStatic = new UserAddressRelations().UserEntityUsingUserId;

		/// <summary>CTor</summary>
		static StaticUserAddressRelations() { }
	}
}
