//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.12.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using DATN_2026.HelperClasses;
using DATN_2026.FactoryClasses;
using DATN_2026.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace DATN_2026.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END
	/// <summary>Entity class which represents the entity 'Voucher'.<br/><br/></summary>
	[Serializable]
	public partial class VoucherEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END	
	{
		private EntityCollection<UserVoucherEntity> _userVouchers;
		private ShopEntity _shop;

		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END
		private static VoucherEntityStaticMetaData _staticMetaData = new VoucherEntityStaticMetaData();
		private static VoucherRelations _relationsFactory = new VoucherRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name Shop</summary>
			public static readonly string Shop = "Shop";
			/// <summary>Member name UserVouchers</summary>
			public static readonly string UserVouchers = "UserVouchers";
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class VoucherEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public VoucherEntityStaticMetaData()
			{
				SetEntityCoreInfo("VoucherEntity", InheritanceHierarchyType.None, false, (int)DATN_2026.EntityType.VoucherEntity, typeof(VoucherEntity), typeof(VoucherEntityFactory), false);
				AddNavigatorMetaData<VoucherEntity, EntityCollection<UserVoucherEntity>>("UserVouchers", a => a._userVouchers, (a, b) => a._userVouchers = b, a => a.UserVouchers, () => new VoucherRelations().UserVoucherEntityUsingVoucherId, typeof(UserVoucherEntity), (int)DATN_2026.EntityType.UserVoucherEntity);
				AddNavigatorMetaData<VoucherEntity, ShopEntity>("Shop", "Vouchers", (a, b) => a._shop = b, a => a._shop, (a, b) => a.Shop = b, DATN_2026.RelationClasses.StaticVoucherRelations.ShopEntityUsingShopIdStatic, ()=>new VoucherRelations().ShopEntityUsingShopId, null, new int[] { (int)VoucherFieldIndex.ShopId }, null, true, (int)DATN_2026.EntityType.ShopEntity);
			}
		}

		/// <summary>Static ctor</summary>
		static VoucherEntity()
		{
		}

		/// <summary> CTor</summary>
		public VoucherEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public VoucherEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this VoucherEntity</param>
		public VoucherEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for Voucher which data should be fetched into this Voucher object</param>
		public VoucherEntity(System.Guid id) : this(id, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for Voucher which data should be fetched into this Voucher object</param>
		/// <param name="validator">The custom validator object for this VoucherEntity</param>
		public VoucherEntity(System.Guid id, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.Id = id;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected VoucherEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		/// <summary>Method which will construct a filter (predicate expression) for the unique constraint defined on the fields: Code .</summary>
		/// <returns>true if succeeded and the contents is read, false otherwise</returns>
		public IPredicateExpression ConstructFilterForUCCode()
		{
			var filter = new PredicateExpression();
			filter.Add(DATN_2026.HelperClasses.VoucherFields.Code == this.Fields.GetCurrentValue((int)VoucherFieldIndex.Code));
 			return filter;
		}

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'UserVoucher' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoUserVouchers() { return CreateRelationInfoForNavigator("UserVouchers"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'Shop' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoShop() { return CreateRelationInfoForNavigator("Shop"); }
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END
			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this VoucherEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static VoucherRelations Relations { get { return _relationsFactory; } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'UserVoucher' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathUserVouchers { get { return _staticMetaData.GetPrefetchPathElement("UserVouchers", CommonEntityBase.CreateEntityCollection<UserVoucherEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'Shop' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathShop { get { return _staticMetaData.GetPrefetchPathElement("Shop", CommonEntityBase.CreateEntityCollection<ShopEntity>()); } }

		/// <summary>The Code property of the Entity Voucher<br/><br/></summary>
		/// <remarks>Mapped on  table field: "vouchers"."code".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 50.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String Code
		{
			get { return (System.String)GetValue((int)VoucherFieldIndex.Code, true); }
			set { SetValue((int)VoucherFieldIndex.Code, value); }
		}

		/// <summary>The DiscountType property of the Entity Voucher<br/><br/></summary>
		/// <remarks>Mapped on  table field: "vouchers"."discount_type".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 20.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String DiscountType
		{
			get { return (System.String)GetValue((int)VoucherFieldIndex.DiscountType, true); }
			set { SetValue((int)VoucherFieldIndex.DiscountType, value); }
		}

		/// <summary>The DiscountValue property of the Entity Voucher<br/><br/></summary>
		/// <remarks>Mapped on  table field: "vouchers"."discount_value".<br/>Table field type characteristics (type, precision, scale, length): Numeric, 18, 2, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Decimal DiscountValue
		{
			get { return (System.Decimal)GetValue((int)VoucherFieldIndex.DiscountValue, true); }
			set { SetValue((int)VoucherFieldIndex.DiscountValue, value); }
		}

		/// <summary>The EndDate property of the Entity Voucher<br/><br/></summary>
		/// <remarks>Mapped on  table field: "vouchers"."end_date".<br/>Table field type characteristics (type, precision, scale, length): TimestampTz, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.DateTime EndDate
		{
			get { return (System.DateTime)GetValue((int)VoucherFieldIndex.EndDate, true); }
			set { SetValue((int)VoucherFieldIndex.EndDate, value); }
		}

		/// <summary>The Id property of the Entity Voucher<br/><br/></summary>
		/// <remarks>Mapped on  table field: "vouchers"."id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, false</remarks>
		public virtual System.Guid Id
		{
			get { return (System.Guid)GetValue((int)VoucherFieldIndex.Id, true); }
			set { SetValue((int)VoucherFieldIndex.Id, value); }
		}

		/// <summary>The IsActive property of the Entity Voucher<br/><br/></summary>
		/// <remarks>Mapped on  table field: "vouchers"."is_active".<br/>Table field type characteristics (type, precision, scale, length): Boolean, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Boolean> IsActive
		{
			get { return (Nullable<System.Boolean>)GetValue((int)VoucherFieldIndex.IsActive, false); }
			set { SetValue((int)VoucherFieldIndex.IsActive, value); }
		}

		/// <summary>The MaxDiscountValue property of the Entity Voucher<br/><br/></summary>
		/// <remarks>Mapped on  table field: "vouchers"."max_discount_value".<br/>Table field type characteristics (type, precision, scale, length): Numeric, 18, 2, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Decimal> MaxDiscountValue
		{
			get { return (Nullable<System.Decimal>)GetValue((int)VoucherFieldIndex.MaxDiscountValue, false); }
			set { SetValue((int)VoucherFieldIndex.MaxDiscountValue, value); }
		}

		/// <summary>The MinOrderValue property of the Entity Voucher<br/><br/></summary>
		/// <remarks>Mapped on  table field: "vouchers"."min_order_value".<br/>Table field type characteristics (type, precision, scale, length): Numeric, 18, 2, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Decimal> MinOrderValue
		{
			get { return (Nullable<System.Decimal>)GetValue((int)VoucherFieldIndex.MinOrderValue, false); }
			set { SetValue((int)VoucherFieldIndex.MinOrderValue, value); }
		}

		/// <summary>The Name property of the Entity Voucher<br/><br/></summary>
		/// <remarks>Mapped on  table field: "vouchers"."name".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 255.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String Name
		{
			get { return (System.String)GetValue((int)VoucherFieldIndex.Name, true); }
			set { SetValue((int)VoucherFieldIndex.Name, value); }
		}

		/// <summary>The ShopId property of the Entity Voucher<br/><br/></summary>
		/// <remarks>Mapped on  table field: "vouchers"."shop_id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Guid> ShopId
		{
			get { return (Nullable<System.Guid>)GetValue((int)VoucherFieldIndex.ShopId, false); }
			set { SetValue((int)VoucherFieldIndex.ShopId, value); }
		}

		/// <summary>The StartDate property of the Entity Voucher<br/><br/></summary>
		/// <remarks>Mapped on  table field: "vouchers"."start_date".<br/>Table field type characteristics (type, precision, scale, length): TimestampTz, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.DateTime StartDate
		{
			get { return (System.DateTime)GetValue((int)VoucherFieldIndex.StartDate, true); }
			set { SetValue((int)VoucherFieldIndex.StartDate, value); }
		}

		/// <summary>The UsageLimit property of the Entity Voucher<br/><br/></summary>
		/// <remarks>Mapped on  table field: "vouchers"."usage_limit".<br/>Table field type characteristics (type, precision, scale, length): Integer, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Int32 UsageLimit
		{
			get { return (System.Int32)GetValue((int)VoucherFieldIndex.UsageLimit, true); }
			set { SetValue((int)VoucherFieldIndex.UsageLimit, value); }
		}

		/// <summary>The UsedCount property of the Entity Voucher<br/><br/></summary>
		/// <remarks>Mapped on  table field: "vouchers"."used_count".<br/>Table field type characteristics (type, precision, scale, length): Integer, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> UsedCount
		{
			get { return (Nullable<System.Int32>)GetValue((int)VoucherFieldIndex.UsedCount, false); }
			set { SetValue((int)VoucherFieldIndex.UsedCount, value); }
		}

		/// <summary>Gets the EntityCollection with the related entities of type 'UserVoucherEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(UserVoucherEntity))]
		public virtual EntityCollection<UserVoucherEntity> UserVouchers { get { return GetOrCreateEntityCollection<UserVoucherEntity, UserVoucherEntityFactory>("Voucher", true, false, ref _userVouchers); } }

		/// <summary>Gets / sets related entity of type 'ShopEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual ShopEntity Shop
		{
			get { return _shop; }
			set { SetSingleRelatedEntityNavigator(value, "Shop"); }
		}

		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END

	}
}

namespace DATN_2026
{
	public enum VoucherFieldIndex
	{
		///<summary>Code. </summary>
		Code,
		///<summary>DiscountType. </summary>
		DiscountType,
		///<summary>DiscountValue. </summary>
		DiscountValue,
		///<summary>EndDate. </summary>
		EndDate,
		///<summary>Id. </summary>
		Id,
		///<summary>IsActive. </summary>
		IsActive,
		///<summary>MaxDiscountValue. </summary>
		MaxDiscountValue,
		///<summary>MinOrderValue. </summary>
		MinOrderValue,
		///<summary>Name. </summary>
		Name,
		///<summary>ShopId. </summary>
		ShopId,
		///<summary>StartDate. </summary>
		StartDate,
		///<summary>UsageLimit. </summary>
		UsageLimit,
		///<summary>UsedCount. </summary>
		UsedCount,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace DATN_2026.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: Voucher. </summary>
	public partial class VoucherRelations: RelationFactory
	{
		/// <summary>Returns a new IEntityRelation object, between VoucherEntity and UserVoucherEntity over the 1:n relation they have, using the relation between the fields: Voucher.Id - UserVoucher.VoucherId</summary>
		public virtual IEntityRelation UserVoucherEntityUsingVoucherId
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "UserVouchers", true, new[] { VoucherFields.Id, UserVoucherFields.VoucherId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between VoucherEntity and ShopEntity over the m:1 relation they have, using the relation between the fields: Voucher.ShopId - Shop.Id</summary>
		public virtual IEntityRelation ShopEntityUsingShopId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "Shop", false, new[] { ShopFields.Id, VoucherFields.ShopId }); }
		}

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticVoucherRelations
	{
		internal static readonly IEntityRelation UserVoucherEntityUsingVoucherIdStatic = new VoucherRelations().UserVoucherEntityUsingVoucherId;
		internal static readonly IEntityRelation ShopEntityUsingShopIdStatic = new VoucherRelations().ShopEntityUsingShopId;

		/// <summary>CTor</summary>
		static StaticVoucherRelations() { }
	}
}
