//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.12.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using DATN_2026.HelperClasses;
using DATN_2026.FactoryClasses;
using DATN_2026.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace DATN_2026.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END
	/// <summary>Entity class which represents the entity 'WalletLedger'.<br/><br/></summary>
	[Serializable]
	public partial class WalletLedgerEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END	
	{
		private ShopEntity _shop;
		private TransactionEntity _transaction;

		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END
		private static WalletLedgerEntityStaticMetaData _staticMetaData = new WalletLedgerEntityStaticMetaData();
		private static WalletLedgerRelations _relationsFactory = new WalletLedgerRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name Shop</summary>
			public static readonly string Shop = "Shop";
			/// <summary>Member name Transaction</summary>
			public static readonly string Transaction = "Transaction";
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class WalletLedgerEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public WalletLedgerEntityStaticMetaData()
			{
				SetEntityCoreInfo("WalletLedgerEntity", InheritanceHierarchyType.None, false, (int)DATN_2026.EntityType.WalletLedgerEntity, typeof(WalletLedgerEntity), typeof(WalletLedgerEntityFactory), false);
				AddNavigatorMetaData<WalletLedgerEntity, ShopEntity>("Shop", "WalletLedgers", (a, b) => a._shop = b, a => a._shop, (a, b) => a.Shop = b, DATN_2026.RelationClasses.StaticWalletLedgerRelations.ShopEntityUsingShopIdStatic, ()=>new WalletLedgerRelations().ShopEntityUsingShopId, null, new int[] { (int)WalletLedgerFieldIndex.ShopId }, null, true, (int)DATN_2026.EntityType.ShopEntity);
				AddNavigatorMetaData<WalletLedgerEntity, TransactionEntity>("Transaction", "WalletLedgers", (a, b) => a._transaction = b, a => a._transaction, (a, b) => a.Transaction = b, DATN_2026.RelationClasses.StaticWalletLedgerRelations.TransactionEntityUsingTransactionIdStatic, ()=>new WalletLedgerRelations().TransactionEntityUsingTransactionId, null, new int[] { (int)WalletLedgerFieldIndex.TransactionId }, null, true, (int)DATN_2026.EntityType.TransactionEntity);
			}
		}

		/// <summary>Static ctor</summary>
		static WalletLedgerEntity()
		{
		}

		/// <summary> CTor</summary>
		public WalletLedgerEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public WalletLedgerEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this WalletLedgerEntity</param>
		public WalletLedgerEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for WalletLedger which data should be fetched into this WalletLedger object</param>
		public WalletLedgerEntity(System.Guid id) : this(id, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for WalletLedger which data should be fetched into this WalletLedger object</param>
		/// <param name="validator">The custom validator object for this WalletLedgerEntity</param>
		public WalletLedgerEntity(System.Guid id, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.Id = id;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected WalletLedgerEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'Shop' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoShop() { return CreateRelationInfoForNavigator("Shop"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'Transaction' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoTransaction() { return CreateRelationInfoForNavigator("Transaction"); }
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END
			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this WalletLedgerEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static WalletLedgerRelations Relations { get { return _relationsFactory; } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'Shop' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathShop { get { return _staticMetaData.GetPrefetchPathElement("Shop", CommonEntityBase.CreateEntityCollection<ShopEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'Transaction' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathTransaction { get { return _staticMetaData.GetPrefetchPathElement("Transaction", CommonEntityBase.CreateEntityCollection<TransactionEntity>()); } }

		/// <summary>The Amount property of the Entity WalletLedger<br/><br/></summary>
		/// <remarks>Mapped on  table field: "wallet_ledgers"."amount".<br/>Table field type characteristics (type, precision, scale, length): Numeric, 18, 2, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Decimal Amount
		{
			get { return (System.Decimal)GetValue((int)WalletLedgerFieldIndex.Amount, true); }
			set { SetValue((int)WalletLedgerFieldIndex.Amount, value); }
		}

		/// <summary>The BalanceAfter property of the Entity WalletLedger<br/><br/></summary>
		/// <remarks>Mapped on  table field: "wallet_ledgers"."balance_after".<br/>Table field type characteristics (type, precision, scale, length): Numeric, 18, 2, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Decimal BalanceAfter
		{
			get { return (System.Decimal)GetValue((int)WalletLedgerFieldIndex.BalanceAfter, true); }
			set { SetValue((int)WalletLedgerFieldIndex.BalanceAfter, value); }
		}

		/// <summary>The BalanceBefore property of the Entity WalletLedger<br/><br/></summary>
		/// <remarks>Mapped on  table field: "wallet_ledgers"."balance_before".<br/>Table field type characteristics (type, precision, scale, length): Numeric, 18, 2, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Decimal BalanceBefore
		{
			get { return (System.Decimal)GetValue((int)WalletLedgerFieldIndex.BalanceBefore, true); }
			set { SetValue((int)WalletLedgerFieldIndex.BalanceBefore, value); }
		}

		/// <summary>The CreatedAt property of the Entity WalletLedger<br/><br/></summary>
		/// <remarks>Mapped on  table field: "wallet_ledgers"."created_at".<br/>Table field type characteristics (type, precision, scale, length): TimestampTz, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.DateTime> CreatedAt
		{
			get { return (Nullable<System.DateTime>)GetValue((int)WalletLedgerFieldIndex.CreatedAt, false); }
			set { SetValue((int)WalletLedgerFieldIndex.CreatedAt, value); }
		}

		/// <summary>The Description property of the Entity WalletLedger<br/><br/></summary>
		/// <remarks>Mapped on  table field: "wallet_ledgers"."description".<br/>Table field type characteristics (type, precision, scale, length): Text, 0, 0, 1073741824.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Description
		{
			get { return (System.String)GetValue((int)WalletLedgerFieldIndex.Description, true); }
			set { SetValue((int)WalletLedgerFieldIndex.Description, value); }
		}

		/// <summary>The Id property of the Entity WalletLedger<br/><br/></summary>
		/// <remarks>Mapped on  table field: "wallet_ledgers"."id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, false</remarks>
		public virtual System.Guid Id
		{
			get { return (System.Guid)GetValue((int)WalletLedgerFieldIndex.Id, true); }
			set { SetValue((int)WalletLedgerFieldIndex.Id, value); }
		}

		/// <summary>The ShopId property of the Entity WalletLedger<br/><br/></summary>
		/// <remarks>Mapped on  table field: "wallet_ledgers"."shop_id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Guid ShopId
		{
			get { return (System.Guid)GetValue((int)WalletLedgerFieldIndex.ShopId, true); }
			set { SetValue((int)WalletLedgerFieldIndex.ShopId, value); }
		}

		/// <summary>The TransactionId property of the Entity WalletLedger<br/><br/></summary>
		/// <remarks>Mapped on  table field: "wallet_ledgers"."transaction_id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Guid> TransactionId
		{
			get { return (Nullable<System.Guid>)GetValue((int)WalletLedgerFieldIndex.TransactionId, false); }
			set { SetValue((int)WalletLedgerFieldIndex.TransactionId, value); }
		}

		/// <summary>Gets / sets related entity of type 'ShopEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual ShopEntity Shop
		{
			get { return _shop; }
			set { SetSingleRelatedEntityNavigator(value, "Shop"); }
		}

		/// <summary>Gets / sets related entity of type 'TransactionEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual TransactionEntity Transaction
		{
			get { return _transaction; }
			set { SetSingleRelatedEntityNavigator(value, "Transaction"); }
		}

		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END

	}
}

namespace DATN_2026
{
	public enum WalletLedgerFieldIndex
	{
		///<summary>Amount. </summary>
		Amount,
		///<summary>BalanceAfter. </summary>
		BalanceAfter,
		///<summary>BalanceBefore. </summary>
		BalanceBefore,
		///<summary>CreatedAt. </summary>
		CreatedAt,
		///<summary>Description. </summary>
		Description,
		///<summary>Id. </summary>
		Id,
		///<summary>ShopId. </summary>
		ShopId,
		///<summary>TransactionId. </summary>
		TransactionId,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace DATN_2026.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: WalletLedger. </summary>
	public partial class WalletLedgerRelations: RelationFactory
	{

		/// <summary>Returns a new IEntityRelation object, between WalletLedgerEntity and ShopEntity over the m:1 relation they have, using the relation between the fields: WalletLedger.ShopId - Shop.Id</summary>
		public virtual IEntityRelation ShopEntityUsingShopId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "Shop", false, new[] { ShopFields.Id, WalletLedgerFields.ShopId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between WalletLedgerEntity and TransactionEntity over the m:1 relation they have, using the relation between the fields: WalletLedger.TransactionId - Transaction.Id</summary>
		public virtual IEntityRelation TransactionEntityUsingTransactionId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "Transaction", false, new[] { TransactionFields.Id, WalletLedgerFields.TransactionId }); }
		}

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticWalletLedgerRelations
	{
		internal static readonly IEntityRelation ShopEntityUsingShopIdStatic = new WalletLedgerRelations().ShopEntityUsingShopId;
		internal static readonly IEntityRelation TransactionEntityUsingTransactionIdStatic = new WalletLedgerRelations().TransactionEntityUsingTransactionId;

		/// <summary>CTor</summary>
		static StaticWalletLedgerRelations() { }
	}
}
