//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.12.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using DATN.HelperClasses;
using DATN.FactoryClasses;
using DATN.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace DATN.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END
	/// <summary>Entity class which represents the entity 'Wishlist'.<br/><br/></summary>
	[Serializable]
	public partial class WishlistEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END	
	{
		private GameEntity _game;

		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END
		private static WishlistEntityStaticMetaData _staticMetaData = new WishlistEntityStaticMetaData();
		private static WishlistRelations _relationsFactory = new WishlistRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name Game</summary>
			public static readonly string Game = "Game";
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class WishlistEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public WishlistEntityStaticMetaData()
			{
				SetEntityCoreInfo("WishlistEntity", InheritanceHierarchyType.None, false, (int)DATN.EntityType.WishlistEntity, typeof(WishlistEntity), typeof(WishlistEntityFactory), false);
				AddNavigatorMetaData<WishlistEntity, GameEntity>("Game", "Wishlists", (a, b) => a._game = b, a => a._game, (a, b) => a.Game = b, DATN.RelationClasses.StaticWishlistRelations.GameEntityUsingGameIdStatic, ()=>new WishlistRelations().GameEntityUsingGameId, null, new int[] { (int)WishlistFieldIndex.GameId }, null, true, (int)DATN.EntityType.GameEntity);
			}
		}

		/// <summary>Static ctor</summary>
		static WishlistEntity()
		{
		}

		/// <summary> CTor</summary>
		public WishlistEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public WishlistEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this WishlistEntity</param>
		public WishlistEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="gameId">PK value for Wishlist which data should be fetched into this Wishlist object</param>
		/// <param name="userId">PK value for Wishlist which data should be fetched into this Wishlist object</param>
		public WishlistEntity(System.Guid gameId, System.Guid userId) : this(gameId, userId, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="gameId">PK value for Wishlist which data should be fetched into this Wishlist object</param>
		/// <param name="userId">PK value for Wishlist which data should be fetched into this Wishlist object</param>
		/// <param name="validator">The custom validator object for this WishlistEntity</param>
		public WishlistEntity(System.Guid gameId, System.Guid userId, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.GameId = gameId;
			this.UserId = userId;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected WishlistEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'Game' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoGame() { return CreateRelationInfoForNavigator("Game"); }
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END
			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this WishlistEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static WishlistRelations Relations { get { return _relationsFactory; } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'Game' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathGame { get { return _staticMetaData.GetPrefetchPathElement("Game", CommonEntityBase.CreateEntityCollection<GameEntity>()); } }

		/// <summary>The CreatedAt property of the Entity Wishlist<br/><br/></summary>
		/// <remarks>Mapped on  table field: "wishlists"."created_at".<br/>Table field type characteristics (type, precision, scale, length): Timestamp, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.DateTime> CreatedAt
		{
			get { return (Nullable<System.DateTime>)GetValue((int)WishlistFieldIndex.CreatedAt, false); }
			set { SetValue((int)WishlistFieldIndex.CreatedAt, value); }
		}

		/// <summary>The GameId property of the Entity Wishlist<br/><br/></summary>
		/// <remarks>Mapped on  table field: "wishlists"."game_id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, false</remarks>
		public virtual System.Guid GameId
		{
			get { return (System.Guid)GetValue((int)WishlistFieldIndex.GameId, true); }
			set { SetValue((int)WishlistFieldIndex.GameId, value); }
		}

		/// <summary>The UserId property of the Entity Wishlist<br/><br/></summary>
		/// <remarks>Mapped on  table field: "wishlists"."user_id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, false</remarks>
		public virtual System.Guid UserId
		{
			get { return (System.Guid)GetValue((int)WishlistFieldIndex.UserId, true); }
			set { SetValue((int)WishlistFieldIndex.UserId, value); }
		}

		/// <summary>Gets / sets related entity of type 'GameEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual GameEntity Game
		{
			get { return _game; }
			set { SetSingleRelatedEntityNavigator(value, "Game"); }
		}

		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END

	}
}

namespace DATN
{
	public enum WishlistFieldIndex
	{
		///<summary>CreatedAt. </summary>
		CreatedAt,
		///<summary>GameId. </summary>
		GameId,
		///<summary>UserId. </summary>
		UserId,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace DATN.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: Wishlist. </summary>
	public partial class WishlistRelations: RelationFactory
	{

		/// <summary>Returns a new IEntityRelation object, between WishlistEntity and GameEntity over the m:1 relation they have, using the relation between the fields: Wishlist.GameId - Game.Id</summary>
		public virtual IEntityRelation GameEntityUsingGameId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "Game", false, new[] { GameFields.Id, WishlistFields.GameId }); }
		}

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticWishlistRelations
	{
		internal static readonly IEntityRelation GameEntityUsingGameIdStatic = new WishlistRelations().GameEntityUsingGameId;

		/// <summary>CTor</summary>
		static StaticWishlistRelations() { }
	}
}
