//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.12.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using DATN_2026.HelperClasses;
using DATN_2026.FactoryClasses;
using DATN_2026.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace DATN_2026.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END
	/// <summary>Entity class which represents the entity 'WithdrawRequest'.<br/><br/></summary>
	[Serializable]
	public partial class WithdrawRequestEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END	
	{
		private ShopEntity _shop;

		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END
		private static WithdrawRequestEntityStaticMetaData _staticMetaData = new WithdrawRequestEntityStaticMetaData();
		private static WithdrawRequestRelations _relationsFactory = new WithdrawRequestRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name Shop</summary>
			public static readonly string Shop = "Shop";
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class WithdrawRequestEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public WithdrawRequestEntityStaticMetaData()
			{
				SetEntityCoreInfo("WithdrawRequestEntity", InheritanceHierarchyType.None, false, (int)DATN_2026.EntityType.WithdrawRequestEntity, typeof(WithdrawRequestEntity), typeof(WithdrawRequestEntityFactory), false);
				AddNavigatorMetaData<WithdrawRequestEntity, ShopEntity>("Shop", "WithdrawRequests", (a, b) => a._shop = b, a => a._shop, (a, b) => a.Shop = b, DATN_2026.RelationClasses.StaticWithdrawRequestRelations.ShopEntityUsingShopIdStatic, ()=>new WithdrawRequestRelations().ShopEntityUsingShopId, null, new int[] { (int)WithdrawRequestFieldIndex.ShopId }, null, true, (int)DATN_2026.EntityType.ShopEntity);
			}
		}

		/// <summary>Static ctor</summary>
		static WithdrawRequestEntity()
		{
		}

		/// <summary> CTor</summary>
		public WithdrawRequestEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public WithdrawRequestEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this WithdrawRequestEntity</param>
		public WithdrawRequestEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for WithdrawRequest which data should be fetched into this WithdrawRequest object</param>
		public WithdrawRequestEntity(System.Guid id) : this(id, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for WithdrawRequest which data should be fetched into this WithdrawRequest object</param>
		/// <param name="validator">The custom validator object for this WithdrawRequestEntity</param>
		public WithdrawRequestEntity(System.Guid id, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.Id = id;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected WithdrawRequestEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'Shop' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoShop() { return CreateRelationInfoForNavigator("Shop"); }
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END
			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this WithdrawRequestEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static WithdrawRequestRelations Relations { get { return _relationsFactory; } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'Shop' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathShop { get { return _staticMetaData.GetPrefetchPathElement("Shop", CommonEntityBase.CreateEntityCollection<ShopEntity>()); } }

		/// <summary>The Amount property of the Entity WithdrawRequest<br/><br/></summary>
		/// <remarks>Mapped on  table field: "withdraw_requests"."amount".<br/>Table field type characteristics (type, precision, scale, length): Numeric, 18, 2, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Decimal Amount
		{
			get { return (System.Decimal)GetValue((int)WithdrawRequestFieldIndex.Amount, true); }
			set { SetValue((int)WithdrawRequestFieldIndex.Amount, value); }
		}

		/// <summary>The BankInfo property of the Entity WithdrawRequest<br/><br/></summary>
		/// <remarks>Mapped on  table field: "withdraw_requests"."bank_info".<br/>Table field type characteristics (type, precision, scale, length): Jsonb, 0, 0, 2147483647.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String BankInfo
		{
			get { return (System.String)GetValue((int)WithdrawRequestFieldIndex.BankInfo, true); }
			set { SetValue((int)WithdrawRequestFieldIndex.BankInfo, value); }
		}

		/// <summary>The CreatedAt property of the Entity WithdrawRequest<br/><br/></summary>
		/// <remarks>Mapped on  table field: "withdraw_requests"."created_at".<br/>Table field type characteristics (type, precision, scale, length): TimestampTz, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.DateTime> CreatedAt
		{
			get { return (Nullable<System.DateTime>)GetValue((int)WithdrawRequestFieldIndex.CreatedAt, false); }
			set { SetValue((int)WithdrawRequestFieldIndex.CreatedAt, value); }
		}

		/// <summary>The Id property of the Entity WithdrawRequest<br/><br/></summary>
		/// <remarks>Mapped on  table field: "withdraw_requests"."id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, false</remarks>
		public virtual System.Guid Id
		{
			get { return (System.Guid)GetValue((int)WithdrawRequestFieldIndex.Id, true); }
			set { SetValue((int)WithdrawRequestFieldIndex.Id, value); }
		}

		/// <summary>The Note property of the Entity WithdrawRequest<br/><br/></summary>
		/// <remarks>Mapped on  table field: "withdraw_requests"."note".<br/>Table field type characteristics (type, precision, scale, length): Text, 0, 0, 1073741824.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Note
		{
			get { return (System.String)GetValue((int)WithdrawRequestFieldIndex.Note, true); }
			set { SetValue((int)WithdrawRequestFieldIndex.Note, value); }
		}

		/// <summary>The ShopId property of the Entity WithdrawRequest<br/><br/></summary>
		/// <remarks>Mapped on  table field: "withdraw_requests"."shop_id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Guid ShopId
		{
			get { return (System.Guid)GetValue((int)WithdrawRequestFieldIndex.ShopId, true); }
			set { SetValue((int)WithdrawRequestFieldIndex.ShopId, value); }
		}

		/// <summary>The Status property of the Entity WithdrawRequest<br/><br/></summary>
		/// <remarks>Mapped on  table field: "withdraw_requests"."status".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 20.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Status
		{
			get { return (System.String)GetValue((int)WithdrawRequestFieldIndex.Status, true); }
			set { SetValue((int)WithdrawRequestFieldIndex.Status, value); }
		}

		/// <summary>The UpdatedAt property of the Entity WithdrawRequest<br/><br/></summary>
		/// <remarks>Mapped on  table field: "withdraw_requests"."updated_at".<br/>Table field type characteristics (type, precision, scale, length): TimestampTz, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.DateTime> UpdatedAt
		{
			get { return (Nullable<System.DateTime>)GetValue((int)WithdrawRequestFieldIndex.UpdatedAt, false); }
			set { SetValue((int)WithdrawRequestFieldIndex.UpdatedAt, value); }
		}

		/// <summary>Gets / sets related entity of type 'ShopEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual ShopEntity Shop
		{
			get { return _shop; }
			set { SetSingleRelatedEntityNavigator(value, "Shop"); }
		}

		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END

	}
}

namespace DATN_2026
{
	public enum WithdrawRequestFieldIndex
	{
		///<summary>Amount. </summary>
		Amount,
		///<summary>BankInfo. </summary>
		BankInfo,
		///<summary>CreatedAt. </summary>
		CreatedAt,
		///<summary>Id. </summary>
		Id,
		///<summary>Note. </summary>
		Note,
		///<summary>ShopId. </summary>
		ShopId,
		///<summary>Status. </summary>
		Status,
		///<summary>UpdatedAt. </summary>
		UpdatedAt,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace DATN_2026.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: WithdrawRequest. </summary>
	public partial class WithdrawRequestRelations: RelationFactory
	{

		/// <summary>Returns a new IEntityRelation object, between WithdrawRequestEntity and ShopEntity over the m:1 relation they have, using the relation between the fields: WithdrawRequest.ShopId - Shop.Id</summary>
		public virtual IEntityRelation ShopEntityUsingShopId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "Shop", false, new[] { ShopFields.Id, WithdrawRequestFields.ShopId }); }
		}

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticWithdrawRequestRelations
	{
		internal static readonly IEntityRelation ShopEntityUsingShopIdStatic = new WithdrawRequestRelations().ShopEntityUsingShopId;

		/// <summary>CTor</summary>
		static StaticWithdrawRequestRelations() { }
	}
}
