<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>DATN_2026</RootNamespace>
    <AssemblyName>DATN_2026</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SD.LLBLGen.Pro.ORMSupportClasses" Version="5.12.2-hotfix-20251212" />
  </ItemGroup>
</Project>