//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro v5.12.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;

namespace DATN.TypedViewClasses
{
	/// <summary>Class which represents a row in the typed view 'Auth2.auth2RolePermission'.</summary>
	/// <remarks>This class is a result class for a query, which is produced with the property <see cref="DATN.FactoryClasses.QueryFactory.auth2RolePermission"/>. </remarks>
	[Serializable]
	public partial class auth2RolePermissionRow 
	{
		partial void OnCreated();
		
		/// <summary>Initializes a new instance of the <see cref="auth2RolePermissionRow"/> class.</summary>
		public auth2RolePermissionRow()
		{
			OnCreated();
		}

		/// <summary>Gets or sets the PermissionId field.</summary>
		public System.Guid PermissionId { get; set; }
		/// <summary>Gets or sets the RoleId field.</summary>
		public System.Guid RoleId { get; set; }
	}
}

