//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro v5.12.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;

namespace DATN.TypedViewClasses
{
	/// <summary>Class which represents a row in the typed view 'Auth2.auth2User'.</summary>
	/// <remarks>This class is a result class for a query, which is produced with the property <see cref="DATN.FactoryClasses.QueryFactory.auth2User"/>. </remarks>
	[Serializable]
	public partial class auth2UserRow 
	{
		partial void OnCreated();
		
		/// <summary>Initializes a new instance of the <see cref="auth2UserRow"/> class.</summary>
		public auth2UserRow()
		{
			OnCreated();
		}

		/// <summary>Gets or sets the AvatarUrl field.</summary>
		public System.String AvatarUrl { get; set; }
		/// <summary>Gets or sets the CreatedAt field.</summary>
		public System.DateTime CreatedAt { get; set; }
		/// <summary>Gets or sets the Email field.</summary>
		public System.String Email { get; set; }
		/// <summary>Gets or sets the FailedLoginCount field.</summary>
		public System.Int32 FailedLoginCount { get; set; }
		/// <summary>Gets or sets the Id field.</summary>
		public System.Guid Id { get; set; }
		/// <summary>Gets or sets the LockoutEnd field.</summary>
		public Nullable<System.DateTime> LockoutEnd { get; set; }
		/// <summary>Gets or sets the PasswordHash field.</summary>
		public System.String PasswordHash { get; set; }
		/// <summary>Gets or sets the Status field.</summary>
		public System.String Status { get; set; }
		/// <summary>Gets or sets the UpdatedAt field.</summary>
		public Nullable<System.DateTime> UpdatedAt { get; set; }
		/// <summary>Gets or sets the Username field.</summary>
		public System.String Username { get; set; }
	}
}

