//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro v5.12.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;

namespace DATN_2026.TypedViewClasses
{
	/// <summary>Class which represents a row in the typed view 'Auth2.auth2PasswordResetToken'.</summary>
	/// <remarks>This class is a result class for a query, which is produced with the property <see cref="DATN_2026.FactoryClasses.QueryFactory.auth2PasswordResetToken"/>. </remarks>
	[Serializable]
	public partial class auth2PasswordResetTokenRow 
	{
		partial void OnCreated();
		
		/// <summary>Initializes a new instance of the <see cref="auth2PasswordResetTokenRow"/> class.</summary>
		public auth2PasswordResetTokenRow()
		{
			OnCreated();
		}

		/// <summary>Gets or sets the CreatedAt field.</summary>
		public System.DateTime CreatedAt { get; set; }
		/// <summary>Gets or sets the ExpiresAt field.</summary>
		public System.DateTime ExpiresAt { get; set; }
		/// <summary>Gets or sets the Id field.</summary>
		public System.Guid Id { get; set; }
		/// <summary>Gets or sets the IpAddress field.</summary>
		public System.String IpAddress { get; set; }
		/// <summary>Gets or sets the IsUsed field.</summary>
		public System.Boolean IsUsed { get; set; }
		/// <summary>Gets or sets the TokenHash field.</summary>
		public System.String TokenHash { get; set; }
		/// <summary>Gets or sets the UsedAt field.</summary>
		public Nullable<System.DateTime> UsedAt { get; set; }
		/// <summary>Gets or sets the UserId field.</summary>
		public System.Guid UserId { get; set; }
	}
}

