//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro v5.12.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;

namespace DATN_2026.TypedViewClasses
{
	/// <summary>Class which represents a row in the typed view 'Catalog.catalogProduct'.</summary>
	/// <remarks>This class is a result class for a query, which is produced with the property <see cref="DATN_2026.FactoryClasses.QueryFactory.catalogProduct"/>. </remarks>
	[Serializable]
	public partial class catalogProductRow 
	{
		partial void OnCreated();
		
		/// <summary>Initializes a new instance of the <see cref="catalogProductRow"/> class.</summary>
		public catalogProductRow()
		{
			OnCreated();
		}

		/// <summary>Gets or sets the AverageRating field.</summary>
		public Nullable<System.Decimal> AverageRating { get; set; }
		/// <summary>Gets or sets the BaseAttributes field.</summary>
		public System.String BaseAttributes { get; set; }
		/// <summary>Gets or sets the BrandId field.</summary>
		public Nullable<System.Guid> BrandId { get; set; }
		/// <summary>Gets or sets the CategoryId field.</summary>
		public Nullable<System.Guid> CategoryId { get; set; }
		/// <summary>Gets or sets the CreatedAt field.</summary>
		public Nullable<System.DateTime> CreatedAt { get; set; }
		/// <summary>Gets or sets the Description field.</summary>
		public System.String Description { get; set; }
		/// <summary>Gets or sets the Id field.</summary>
		public System.Guid Id { get; set; }
		/// <summary>Gets or sets the Name field.</summary>
		public System.String Name { get; set; }
		/// <summary>Gets or sets the ReviewCount field.</summary>
		public Nullable<System.Int32> ReviewCount { get; set; }
		/// <summary>Gets or sets the ShopId field.</summary>
		public Nullable<System.Guid> ShopId { get; set; }
		/// <summary>Gets or sets the Sku field.</summary>
		public System.String Sku { get; set; }
		/// <summary>Gets or sets the Slug field.</summary>
		public System.String Slug { get; set; }
		/// <summary>Gets or sets the Status field.</summary>
		public System.String Status { get; set; }
		/// <summary>Gets or sets the Summary field.</summary>
		public System.String Summary { get; set; }
		/// <summary>Gets or sets the UpdatedAt field.</summary>
		public Nullable<System.DateTime> UpdatedAt { get; set; }
		/// <summary>Gets or sets the ViewCount field.</summary>
		public Nullable<System.Int32> ViewCount { get; set; }
	}
}

