//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro v5.12.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;

namespace DATN_2026.TypedViewClasses
{
	/// <summary>Class which represents a row in the typed view 'Catalog.catalogShop'.</summary>
	/// <remarks>This class is a result class for a query, which is produced with the property <see cref="DATN_2026.FactoryClasses.QueryFactory.catalogShop"/>. </remarks>
	[Serializable]
	public partial class catalogShopRow 
	{
		partial void OnCreated();
		
		/// <summary>Initializes a new instance of the <see cref="catalogShopRow"/> class.</summary>
		public catalogShopRow()
		{
			OnCreated();
		}

		/// <summary>Gets or sets the AvailableBalance field.</summary>
		public Nullable<System.Decimal> AvailableBalance { get; set; }
		/// <summary>Gets or sets the CoverUrl field.</summary>
		public System.String CoverUrl { get; set; }
		/// <summary>Gets or sets the CreatedAt field.</summary>
		public Nullable<System.DateTime> CreatedAt { get; set; }
		/// <summary>Gets or sets the Description field.</summary>
		public System.String Description { get; set; }
		/// <summary>Gets or sets the DistrictId field.</summary>
		public Nullable<System.Int32> DistrictId { get; set; }
		/// <summary>Gets or sets the Id field.</summary>
		public System.Guid Id { get; set; }
		/// <summary>Gets or sets the IsActive field.</summary>
		public Nullable<System.Boolean> IsActive { get; set; }
		/// <summary>Gets or sets the LockedBalance field.</summary>
		public Nullable<System.Decimal> LockedBalance { get; set; }
		/// <summary>Gets or sets the LogoUrl field.</summary>
		public System.String LogoUrl { get; set; }
		/// <summary>Gets or sets the Name field.</summary>
		public System.String Name { get; set; }
		/// <summary>Gets or sets the OwnerId field.</summary>
		public Nullable<System.Guid> OwnerId { get; set; }
		/// <summary>Gets or sets the PickupAddress field.</summary>
		public System.String PickupAddress { get; set; }
		/// <summary>Gets or sets the ProvinceId field.</summary>
		public Nullable<System.Int32> ProvinceId { get; set; }
		/// <summary>Gets or sets the Rating field.</summary>
		public Nullable<System.Decimal> Rating { get; set; }
		/// <summary>Gets or sets the Slug field.</summary>
		public System.String Slug { get; set; }
		/// <summary>Gets or sets the WardId field.</summary>
		public Nullable<System.Int32> WardId { get; set; }
	}
}

