//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro v5.12.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;

namespace DATN_2026.TypedViewClasses
{
	/// <summary>Class which represents a row in the typed view 'Engagement.engagementChatBox'.</summary>
	/// <remarks>This class is a result class for a query, which is produced with the property <see cref="DATN_2026.FactoryClasses.QueryFactory.engagementChatBox"/>. </remarks>
	[Serializable]
	public partial class engagementChatBoxRow 
	{
		partial void OnCreated();
		
		/// <summary>Initializes a new instance of the <see cref="engagementChatBoxRow"/> class.</summary>
		public engagementChatBoxRow()
		{
			OnCreated();
		}

		/// <summary>Gets or sets the Id field.</summary>
		public System.Guid Id { get; set; }
		/// <summary>Gets or sets the LastActivity field.</summary>
		public Nullable<System.DateTime> LastActivity { get; set; }
		/// <summary>Gets or sets the LastMessage field.</summary>
		public System.String LastMessage { get; set; }
		/// <summary>Gets or sets the ShopId field.</summary>
		public Nullable<System.Guid> ShopId { get; set; }
		/// <summary>Gets or sets the UserId field.</summary>
		public Nullable<System.Guid> UserId { get; set; }
	}
}

