//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro v5.12.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;

namespace DATN_2026.TypedViewClasses
{
	/// <summary>Class which represents a row in the typed view 'Engagement.engagementNotification'.</summary>
	/// <remarks>This class is a result class for a query, which is produced with the property <see cref="DATN_2026.FactoryClasses.QueryFactory.engagementNotification"/>. </remarks>
	[Serializable]
	public partial class engagementNotificationRow 
	{
		partial void OnCreated();
		
		/// <summary>Initializes a new instance of the <see cref="engagementNotificationRow"/> class.</summary>
		public engagementNotificationRow()
		{
			OnCreated();
		}

		/// <summary>Gets or sets the Body field.</summary>
		public System.String Body { get; set; }
		/// <summary>Gets or sets the CreatedAt field.</summary>
		public Nullable<System.DateTime> CreatedAt { get; set; }
		/// <summary>Gets or sets the Id field.</summary>
		public System.Guid Id { get; set; }
		/// <summary>Gets or sets the IsRead field.</summary>
		public Nullable<System.Boolean> IsRead { get; set; }
		/// <summary>Gets or sets the Metadata field.</summary>
		public System.String Metadata { get; set; }
		/// <summary>Gets or sets the Title field.</summary>
		public System.String Title { get; set; }
		/// <summary>Gets or sets the Type field.</summary>
		public System.String Type { get; set; }
		/// <summary>Gets or sets the UserId field.</summary>
		public Nullable<System.Guid> UserId { get; set; }
	}
}

