//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro v5.12.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;

namespace DATN_2026.TypedViewClasses
{
	/// <summary>Class which represents a row in the typed view 'Engagement.engagementChatMessage'.</summary>
	/// <remarks>This class is a result class for a query, which is produced with the property <see cref="DATN_2026.FactoryClasses.QueryFactory.engagementChatMessage"/>. </remarks>
	[Serializable]
	public partial class engagementChatMessageRow 
	{
		partial void OnCreated();
		
		/// <summary>Initializes a new instance of the <see cref="engagementChatMessageRow"/> class.</summary>
		public engagementChatMessageRow()
		{
			OnCreated();
		}

		/// <summary>Gets or sets the Content field.</summary>
		public System.String Content { get; set; }
		/// <summary>Gets or sets the CreatedAt field.</summary>
		public Nullable<System.DateTime> CreatedAt { get; set; }
		/// <summary>Gets or sets the Id field.</summary>
		public System.Guid Id { get; set; }
		/// <summary>Gets or sets the IsRead field.</summary>
		public Nullable<System.Boolean> IsRead { get; set; }
		/// <summary>Gets or sets the MessageType field.</summary>
		public System.String MessageType { get; set; }
		/// <summary>Gets or sets the RoomId field.</summary>
		public Nullable<System.Guid> RoomId { get; set; }
		/// <summary>Gets or sets the SenderId field.</summary>
		public Nullable<System.Guid> SenderId { get; set; }
	}
}

