//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro v5.12.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;

namespace DATN.TypedViewClasses
{
	/// <summary>Class which represents a row in the typed view 'Engagement.engagementReview1'.</summary>
	/// <remarks>This class is a result class for a query, which is produced with the property <see cref="DATN.FactoryClasses.QueryFactory.engagementReview1"/>. </remarks>
	[Serializable]
	public partial class engagementReview1Row 
	{
		partial void OnCreated();
		
		/// <summary>Initializes a new instance of the <see cref="engagementReview1Row"/> class.</summary>
		public engagementReview1Row()
		{
			OnCreated();
		}

		/// <summary>Gets or sets the Comment field.</summary>
		public System.String Comment { get; set; }
		/// <summary>Gets or sets the CreatedAt field.</summary>
		public Nullable<System.DateTime> CreatedAt { get; set; }
		/// <summary>Gets or sets the Id field.</summary>
		public System.Guid Id { get; set; }
		/// <summary>Gets or sets the Images field.</summary>
		public System.String Images { get; set; }
		/// <summary>Gets or sets the OrderId field.</summary>
		public Nullable<System.Guid> OrderId { get; set; }
		/// <summary>Gets or sets the Rating field.</summary>
		public Nullable<System.Int32> Rating { get; set; }
		/// <summary>Gets or sets the UserId field.</summary>
		public Nullable<System.Guid> UserId { get; set; }
		/// <summary>Gets or sets the VariantId field.</summary>
		public Nullable<System.Guid> VariantId { get; set; }
	}
}

