//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro v5.12.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;

namespace DATN_2026.TypedViewClasses
{
	/// <summary>Class which represents a row in the typed view 'Marketing.marketingUserVoucher'.</summary>
	/// <remarks>This class is a result class for a query, which is produced with the property <see cref="DATN_2026.FactoryClasses.QueryFactory.marketingUserVoucher"/>. </remarks>
	[Serializable]
	public partial class marketingUserVoucherRow 
	{
		partial void OnCreated();
		
		/// <summary>Initializes a new instance of the <see cref="marketingUserVoucherRow"/> class.</summary>
		public marketingUserVoucherRow()
		{
			OnCreated();
		}

		/// <summary>Gets or sets the IsUsed field.</summary>
		public Nullable<System.Boolean> IsUsed { get; set; }
		/// <summary>Gets or sets the SavedAt field.</summary>
		public Nullable<System.DateTime> SavedAt { get; set; }
		/// <summary>Gets or sets the UserId field.</summary>
		public System.Guid UserId { get; set; }
		/// <summary>Gets or sets the VoucherId field.</summary>
		public System.Guid VoucherId { get; set; }
	}
}

