//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro v5.12.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;

namespace DATN.TypedViewClasses
{
	/// <summary>Class which represents a row in the typed view 'Sales.salesOrder1'.</summary>
	/// <remarks>This class is a result class for a query, which is produced with the property <see cref="DATN.FactoryClasses.QueryFactory.salesOrder1"/>. </remarks>
	[Serializable]
	public partial class salesOrder1Row 
	{
		partial void OnCreated();
		
		/// <summary>Initializes a new instance of the <see cref="salesOrder1Row"/> class.</summary>
		public salesOrder1Row()
		{
			OnCreated();
		}

		/// <summary>Gets or sets the BuyerId field.</summary>
		public Nullable<System.Guid> BuyerId { get; set; }
		/// <summary>Gets or sets the CreatedAt field.</summary>
		public Nullable<System.DateTime> CreatedAt { get; set; }
		/// <summary>Gets or sets the CustomerNote field.</summary>
		public System.String CustomerNote { get; set; }
		/// <summary>Gets or sets the Id field.</summary>
		public System.Guid Id { get; set; }
		/// <summary>Gets or sets the OrderCode field.</summary>
		public System.String OrderCode { get; set; }
		/// <summary>Gets or sets the OrderStatus field.</summary>
		public System.String OrderStatus { get; set; }
		/// <summary>Gets or sets the PaymentMethod field.</summary>
		public System.String PaymentMethod { get; set; }
		/// <summary>Gets or sets the PaymentStatus field.</summary>
		public System.String PaymentStatus { get; set; }
		/// <summary>Gets or sets the ShippingAddress field.</summary>
		public System.String ShippingAddress { get; set; }
		/// <summary>Gets or sets the ShippingFee field.</summary>
		public Nullable<System.Decimal> ShippingFee { get; set; }
		/// <summary>Gets or sets the TotalAmount field.</summary>
		public System.Decimal TotalAmount { get; set; }
	}
}

