//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro v5.12.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;

namespace DATN.TypedViewClasses
{
	/// <summary>Class which represents a row in the typed view 'Sales.salesOrderItem1'.</summary>
	/// <remarks>This class is a result class for a query, which is produced with the property <see cref="DATN.FactoryClasses.QueryFactory.salesOrderItem1"/>. </remarks>
	[Serializable]
	public partial class salesOrderItem1Row 
	{
		partial void OnCreated();
		
		/// <summary>Initializes a new instance of the <see cref="salesOrderItem1Row"/> class.</summary>
		public salesOrderItem1Row()
		{
			OnCreated();
		}

		/// <summary>Gets or sets the Id field.</summary>
		public System.Guid Id { get; set; }
		/// <summary>Gets or sets the OrderId field.</summary>
		public Nullable<System.Guid> OrderId { get; set; }
		/// <summary>Gets or sets the ProductNameSnapshot field.</summary>
		public System.String ProductNameSnapshot { get; set; }
		/// <summary>Gets or sets the Quantity field.</summary>
		public System.Int32 Quantity { get; set; }
		/// <summary>Gets or sets the UnitPrice field.</summary>
		public System.Decimal UnitPrice { get; set; }
		/// <summary>Gets or sets the VariantId field.</summary>
		public Nullable<System.Guid> VariantId { get; set; }
	}
}

