//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro v5.12.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;

namespace DATN_2026.TypedViewClasses
{
	/// <summary>Class which represents a row in the typed view 'Sales.salesShipment'.</summary>
	/// <remarks>This class is a result class for a query, which is produced with the property <see cref="DATN_2026.FactoryClasses.QueryFactory.salesShipment"/>. </remarks>
	[Serializable]
	public partial class salesShipmentRow 
	{
		partial void OnCreated();
		
		/// <summary>Initializes a new instance of the <see cref="salesShipmentRow"/> class.</summary>
		public salesShipmentRow()
		{
			OnCreated();
		}

		/// <summary>Gets or sets the CreatedAt field.</summary>
		public Nullable<System.DateTime> CreatedAt { get; set; }
		/// <summary>Gets or sets the ExpectedDeliveryDate field.</summary>
		public Nullable<System.DateTime> ExpectedDeliveryDate { get; set; }
		/// <summary>Gets or sets the GhnOrderCode field.</summary>
		public System.String GhnOrderCode { get; set; }
		/// <summary>Gets or sets the Id field.</summary>
		public System.Guid Id { get; set; }
		/// <summary>Gets or sets the OrderId field.</summary>
		public System.Guid OrderId { get; set; }
		/// <summary>Gets or sets the Provider field.</summary>
		public System.String Provider { get; set; }
		/// <summary>Gets or sets the ShippingFee field.</summary>
		public Nullable<System.Decimal> ShippingFee { get; set; }
		/// <summary>Gets or sets the Status field.</summary>
		public System.String Status { get; set; }
		/// <summary>Gets or sets the TrackingCode field.</summary>
		public System.String TrackingCode { get; set; }
		/// <summary>Gets or sets the UpdatedAt field.</summary>
		public Nullable<System.DateTime> UpdatedAt { get; set; }
	}
}

