//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro v5.12.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;

namespace DATN_2026.TypedViewClasses
{
	/// <summary>Class which represents a row in the typed view 'Sales.salesShippingTracking'.</summary>
	/// <remarks>This class is a result class for a query, which is produced with the property <see cref="DATN_2026.FactoryClasses.QueryFactory.salesShippingTracking"/>. </remarks>
	[Serializable]
	public partial class salesShippingTrackingRow 
	{
		partial void OnCreated();
		
		/// <summary>Initializes a new instance of the <see cref="salesShippingTrackingRow"/> class.</summary>
		public salesShippingTrackingRow()
		{
			OnCreated();
		}

		/// <summary>Gets or sets the Description field.</summary>
		public System.String Description { get; set; }
		/// <summary>Gets or sets the Id field.</summary>
		public System.Guid Id { get; set; }
		/// <summary>Gets or sets the Location field.</summary>
		public System.String Location { get; set; }
		/// <summary>Gets or sets the OrderId field.</summary>
		public Nullable<System.Guid> OrderId { get; set; }
		/// <summary>Gets or sets the Status field.</summary>
		public System.String Status { get; set; }
		/// <summary>Gets or sets the UpdatedAt field.</summary>
		public Nullable<System.DateTime> UpdatedAt { get; set; }
	}
}

