//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro v5.12.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;

namespace DATN_2026.TypedViewClasses
{
	/// <summary>Class which represents a row in the typed view 'Sales.salesWithdrawRequest'.</summary>
	/// <remarks>This class is a result class for a query, which is produced with the property <see cref="DATN_2026.FactoryClasses.QueryFactory.salesWithdrawRequest"/>. </remarks>
	[Serializable]
	public partial class salesWithdrawRequestRow 
	{
		partial void OnCreated();
		
		/// <summary>Initializes a new instance of the <see cref="salesWithdrawRequestRow"/> class.</summary>
		public salesWithdrawRequestRow()
		{
			OnCreated();
		}

		/// <summary>Gets or sets the Amount field.</summary>
		public System.Decimal Amount { get; set; }
		/// <summary>Gets or sets the BankInfo field.</summary>
		public System.String BankInfo { get; set; }
		/// <summary>Gets or sets the CreatedAt field.</summary>
		public Nullable<System.DateTime> CreatedAt { get; set; }
		/// <summary>Gets or sets the Id field.</summary>
		public System.Guid Id { get; set; }
		/// <summary>Gets or sets the Note field.</summary>
		public System.String Note { get; set; }
		/// <summary>Gets or sets the ShopId field.</summary>
		public System.Guid ShopId { get; set; }
		/// <summary>Gets or sets the Status field.</summary>
		public System.String Status { get; set; }
		/// <summary>Gets or sets the UpdatedAt field.</summary>
		public Nullable<System.DateTime> UpdatedAt { get; set; }
	}
}

