//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro v5.12.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;

namespace DATN.TypedViewClasses
{
	/// <summary>Class which represents a row in the typed view 'Store.storeDiscount'.</summary>
	/// <remarks>This class is a result class for a query, which is produced with the property <see cref="DATN.FactoryClasses.QueryFactory.storeDiscount"/>. </remarks>
	[Serializable]
	public partial class storeDiscountRow 
	{
		partial void OnCreated();
		
		/// <summary>Initializes a new instance of the <see cref="storeDiscountRow"/> class.</summary>
		public storeDiscountRow()
		{
			OnCreated();
		}

		/// <summary>Gets or sets the DiscountPercent field.</summary>
		public System.Int32 DiscountPercent { get; set; }
		/// <summary>Gets or sets the EndDate field.</summary>
		public System.DateTime EndDate { get; set; }
		/// <summary>Gets or sets the GameId field.</summary>
		public System.Guid GameId { get; set; }
		/// <summary>Gets or sets the Id field.</summary>
		public System.Guid Id { get; set; }
		/// <summary>Gets or sets the StartDate field.</summary>
		public System.DateTime StartDate { get; set; }
	}
}

