//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro v5.12.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;

namespace DATN.TypedViewClasses
{
	/// <summary>Class which represents a row in the typed view 'Store.storeOrder'.</summary>
	/// <remarks>This class is a result class for a query, which is produced with the property <see cref="DATN.FactoryClasses.QueryFactory.storeOrder"/>. </remarks>
	[Serializable]
	public partial class storeOrderRow 
	{
		partial void OnCreated();
		
		/// <summary>Initializes a new instance of the <see cref="storeOrderRow"/> class.</summary>
		public storeOrderRow()
		{
			OnCreated();
		}

		/// <summary>Gets or sets the CreatedAt field.</summary>
		public Nullable<System.DateTime> CreatedAt { get; set; }
		/// <summary>Gets or sets the Id field.</summary>
		public System.Guid Id { get; set; }
		/// <summary>Gets or sets the Status field.</summary>
		public System.String Status { get; set; }
		/// <summary>Gets or sets the TotalAmount field.</summary>
		public System.Decimal TotalAmount { get; set; }
		/// <summary>Gets or sets the UserId field.</summary>
		public System.Guid UserId { get; set; }
	}
}

