//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro v5.12.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;

namespace DATN.TypedViewClasses
{
	/// <summary>Class which represents a row in the typed view 'Store.storeUserGame'.</summary>
	/// <remarks>This class is a result class for a query, which is produced with the property <see cref="DATN.FactoryClasses.QueryFactory.storeUserGame"/>. </remarks>
	[Serializable]
	public partial class storeUserGameRow 
	{
		partial void OnCreated();
		
		/// <summary>Initializes a new instance of the <see cref="storeUserGameRow"/> class.</summary>
		public storeUserGameRow()
		{
			OnCreated();
		}

		/// <summary>Gets or sets the GameId field.</summary>
		public System.Guid GameId { get; set; }
		/// <summary>Gets or sets the PlaytimeMinutes field.</summary>
		public Nullable<System.Int32> PlaytimeMinutes { get; set; }
		/// <summary>Gets or sets the PurchasedAt field.</summary>
		public Nullable<System.DateTime> PurchasedAt { get; set; }
		/// <summary>Gets or sets the UserId field.</summary>
		public System.Guid UserId { get; set; }
	}
}

