//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro v5.12.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;

namespace DATN.TypedViewClasses
{
	/// <summary>Class which represents a row in the typed view 'Store.storeTag'.</summary>
	/// <remarks>This class is a result class for a query, which is produced with the property <see cref="DATN.FactoryClasses.QueryFactory.storeTag"/>. </remarks>
	[Serializable]
	public partial class storeTagRow 
	{
		partial void OnCreated();
		
		/// <summary>Initializes a new instance of the <see cref="storeTagRow"/> class.</summary>
		public storeTagRow()
		{
			OnCreated();
		}

		/// <summary>Gets or sets the Id field.</summary>
		public System.Guid Id { get; set; }
		/// <summary>Gets or sets the Name field.</summary>
		public System.String Name { get; set; }
	}
}

